apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../../base/kvrocks

secretGenerator:
  - name: kvrocks-auth
    literals:
      - redis-password=change-me

generatorOptions:
  disableNameSuffixHash: true