version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/dashboard"
      schedule:
          interval: "weekly"
      labels:
          - "dependencies"
      commit-message:
          prefix: "build"
          include: "scope"

    - package-ecosystem: "gomod"
      directories:
          - "/api"
          - "/browser-controller"
          - "/cache/helpers"
          - "/contentwriter"
          - "/ctl"
          - "/dns-resolver"
          - "/frontier-queue-workers"
          - "/log-service"
          - "/metrics"
          - "/ooshandler"
          - "/recorderproxy"
          - "/robots-evaluator"
          - "/scopeservice"
      schedule:
          interval: "weekly"
      labels:
          - "dependencies"
      commit-message:
          prefix: "build"
          include: "scope"

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
      labels:
          - "dependencies"
      commit-message:
          prefix: "build"
          include: "scope"
    
    - package-ecosystem: "docker"
      directories:
          - "/cache"
      schedule:
          interval: "weekly"
      labels:
          - "dependencies"
      commit-message:
          prefix: "build"
          include: "scope"
