apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: infra

build:
  local:
    push: false
  artifacts:
    - image: ghcr.io/nationallibraryofnorway/veidemann/rethinkdbadapter
      context: .
      jib:
        project: rethinkdbadapter
    - image: ghcr.io/nationallibraryofnorway/veidemann/olricd
      context: ./olricd
      docker: {}
    - image: ghcr.io/nationallibraryofnorway/veidemann/rethinkdb
      context: ./rethinkdb
      docker: {}

manifests:
  kustomize:
    paths:
      - deploy/k8s/overlays/dev/rethinkdb
      - deploy/k8s/overlays/dev/olric
      - deploy/k8s/overlays/dev/rethinkdbadapter/
      - deploy/k8s/overlays/dev/kvrocks

deploy:
  kubeContext: minikube
  statusCheck: true
  helm:
    releases:
      - name: cert-manager
        remoteChart: oci://quay.io/jetstack/charts/cert-manager
        version: 1.20.2
        namespace: cert-manager
        createNamespace: true
        setValues:
          crds.enabled: true
      - name: redis
        remoteChart: oci://registry-1.docker.io/cloudpirates/redis
        version: 0.27.1
        namespace: default
        setValues:
          auth.enabled: false
          persistence.enabled: false
  kubectl: {}

---

apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: app

build:
  local:
    push: false
  artifacts:
    - image: ghcr.io/nationallibraryofnorway/veidemann/recorderproxy
      context: ./recorderproxy
      ko: {}
    - image: ghcr.io/nationallibraryofnorway/veidemann/contentwriter
      context: ./contentwriter
      ko: {}
    - image: ghcr.io/nationallibraryofnorway/veidemann/robots-evaluator
      context: ./robots-evaluator
      ko: {}
    - image: ghcr.io/nationallibraryofnorway/veidemann/scopeservice
      context: ./scopeservice
      ko: {}
    - image: ghcr.io/nationallibraryofnorway/veidemann/dns-resolver
      context: ./dns-resolver
      ko: {}
    - image: ghcr.io/nationallibraryofnorway/veidemann/log-service
      context: ./log-service
      ko: {}
    - image: ghcr.io/nationallibraryofnorway/veidemann/browser-controller
      context: ./browser-controller
      ko: {}
    - image: ghcr.io/nationallibraryofnorway/veidemann/metrics
      context: ./metrics
      ko: {}
    - image: ghcr.io/nationallibraryofnorway/veidemann/ooshandler
      context: ./ooshandler
      ko: {}
    - image: ghcr.io/nationallibraryofnorway/veidemann/frontier-queue-workers
      context: ./frontier-queue-workers
      ko: {}
    - image: ghcr.io/nationallibraryofnorway/veidemann/dashboard
      context: ./dashboard
      docker: {}
    - image: ghcr.io/nationallibraryofnorway/veidemann/rethinkdb-ast-service
      context: ./rethinkdb-ast-service
      docker: {}
    - image: ghcr.io/nationallibraryofnorway/veidemann/cache
      context: ./cache
      docker: {}
    - image: ghcr.io/nationallibraryofnorway/veidemann/frontier
      context: .
      jib:
        project: frontier
    - image: ghcr.io/nationallibraryofnorway/veidemann/controller
      context: .
      jib:
        project: controller


manifests:
  kustomize:
    paths:
      - deploy/k8s/overlays/dev

deploy:
  kubeContext: minikube
  statusCheck: true
  kubectl: {}

profiles:
  - name: auth
    manifests:
      helm:
        releases:
          - name: dex
            repo: https://charts.dexidp.io
            remoteChart: dex
            version: 0.24.0
            valuesFiles:
              - deploy/k8s/overlays/auth/dex/values.yaml
      kustomize:
        paths:
          - kubernetes/overlays/auth

  - name: no-build
    patches:
      - op: remove
        path: /build