apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: infra

build:
  local:
    push: false
    useBuildkit: true
  artifacts:
    - image: ghcr.io/nationallibraryofnorway/veidemann/olricd
      context: ./olricd
      docker: {}
    - image: ghcr.io/nationallibraryofnorway/veidemann/rethinkdb
      context: ./rethinkdb
      docker: {}

manifests:
  kustomize:
    paths:
      - deploy/k8s/overlays/dev/rethinkdb
      - deploy/k8s/overlays/dev/olric
      - deploy/k8s/overlays/dev/kvrocks

deploy:
  kubeContext: minikube
  statusCheck: true
  helm:
    releases:
      - name: cert-manager
        remoteChart: oci://quay.io/jetstack/charts/cert-manager
        version: 1.21.1
        namespace: cert-manager
        createNamespace: true
        setValues:
          crds.enabled: true
      - name: redis
        remoteChart: oci://registry-1.docker.io/cloudpirates/redis
        version: 0.33.6
        namespace: default
        setValues:
          metrics.enabled: true
          metrics.serviceMonitor.enabled: false
          auth.enabled: false
          auth.metrics: false
          persistence.enabled: false
  kubectl: {}

---

apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: app

build:
  local:
    useBuildkit: true
    push: false
  artifacts:
    - image: ghcr.io/nationallibraryofnorway/veidemann/recorderproxy
      context: ./recorderproxy
      ko: {}
    - image: ghcr.io/nationallibraryofnorway/veidemann/contentwriter
      context: ./contentwriter
      ko: {}
    - image: ghcr.io/nationallibraryofnorway/veidemann/robots-evaluator
      context: ./robots-evaluator
      ko: {}
    - image: ghcr.io/nationallibraryofnorway/veidemann/scopeservice
      context: ./scopeservice
      ko: {}
    - image: ghcr.io/nationallibraryofnorway/veidemann/dns-resolver
      context: ./dns-resolver
      ko: {}
    - image: ghcr.io/nationallibraryofnorway/veidemann/log-service
      context: ./log-service
      ko: {}
    - image: ghcr.io/nationallibraryofnorway/veidemann/browser-controller
      context: ./browser-controller
      ko: {}
    - image: ghcr.io/nationallibraryofnorway/veidemann/metrics
      context: ./metrics
      ko: {}
    - image: ghcr.io/nationallibraryofnorway/veidemann/ooshandler
      context: ./ooshandler
      ko: {}
    - image: ghcr.io/nationallibraryofnorway/veidemann/frontier-queue-workers
      context: ./frontier-queue-workers
      ko: {}
    - image: ghcr.io/nationallibraryofnorway/veidemann/dashboard
      context: ./dashboard
      docker: {}
    - image: ghcr.io/nationallibraryofnorway/veidemann/rethinkdb-ast-service
      context: ./rethinkdb-ast-service
      docker: {}
    - image: ghcr.io/nationallibraryofnorway/veidemann/cache
      context: ./cache
      docker: {}
    - image: ghcr.io/nationallibraryofnorway/veidemann/frontier
      context: .
      jib:
        project: frontier
    - image: ghcr.io/nationallibraryofnorway/veidemann/controller
      context: .
      jib:
        project: controller
    - image: ghcr.io/nationallibraryofnorway/veidemann/rethinkdbadapter
      context: .
      jib:
        project: rethinkdbadapter

manifests:
  kustomize:
    paths:
      - deploy/k8s/overlays/dev

deploy:
  kubeContext: minikube
  statusCheck: true
  kubectl: {}

profiles:
  - name: auth
    manifests:
      helm:
        releases:
          - name: dex
            repo: https://charts.dexidp.io
            remoteChart: dex
            version: 0.24.1
            valuesFiles:
              - deploy/helm/dex/values.yaml
    patches:
      - op: replace
        path: /manifests/kustomize/paths/0
        value: deploy/k8s/overlays/auth

  - name: monitoring
    patches:
      - op: add
        path: /requires
        value:
          - path: skaffold.monitoring.yaml
            configs:
              - monitoring

  - name: no-build
    patches:
      - op: remove
        path: /build

---

apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: dashboard

build:
  local:
    useBuildkit: true
    push: false
  artifacts:
    - image: ghcr.io/nationallibraryofnorway/veidemann/dashboard
      context: ./dashboard
      docker: {}

manifests:
  kustomize:
    paths:
      - deploy/k8s/overlays/dev/dashboard

deploy:
  kubeContext: minikube
  statusCheck: true
  kubectl: {}
