apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: monitoring

manifests:
  kustomize:
    paths:
      - deploy/k8s/addons/monitoring

deploy:
  kubeContext: minikube
  statusCheck: true
  kubectl: {}
  helm:
    releases:
      - name: kube-prometheus-stack
        repo: https://prometheus-community.github.io/helm-charts
        remoteChart: kube-prometheus-stack
        version: 84.3.0
        namespace: monitoring
        createNamespace: true
        wait: true
        valuesFiles:
          - deploy/helm/kube-prometheus-stack/values.yaml
