---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: olricd

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: olricd
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: olricd
subjects:
  - kind: ServiceAccount
    name: olricd
    namespace: default
roleRef:
  kind: Role
  name: olricd
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: olricd
  name: olricd
spec:
  selector:
    matchLabels:
      run: olricd
  replicas: 3
  template:
    metadata:
      labels:
        run: olricd
    spec:
      serviceAccountName: olricd
      containers:
        - name: olricd
          image: harbor.nb.no/nettarkivet/olricd:main
          imagePullPolicy: Always
          ports:
            - containerPort: 3320
            - containerPort: 3322
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              memory: 128Mi
              cpu: 200m
          volumeMounts:
            - name: olricd-config-volume
              mountPath: /etc/olricd/config.yaml
              readOnly: true
              subPath: config.yaml
          env:
            - name: OLRICD_CONFIG
              value: "/etc/olricd/config.yaml"
      volumes:
        - name: olricd-config-volume
          configMap:
            name: olricd-config
            items:
              - key: config.yaml
                path: config.yaml

---

apiVersion: v1
kind: Service
metadata:
  name: memberlist
spec:
  selector:
    run: olricd
  clusterIP: None
  ports:
    - port: 3322
      protocol: TCP
      targetPort: 3322

---

apiVersion: v1
kind: Service
metadata:
  name: olricd
spec:
  selector:
    run: olricd
  ports:
    - port: 3320
      protocol: TCP
      targetPort: 3320

