// source: uricanonicalizer/v1/uricanonicalizer.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var commons_v1_resources_pb = require('../../commons/v1/resources_pb.js');
goog.object.extend(proto, commons_v1_resources_pb);
goog.exportSymbol('proto.veidemann.api.uricanonicalizer.v1.CanonicalizeRequest', null, global);
goog.exportSymbol('proto.veidemann.api.uricanonicalizer.v1.CanonicalizeResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.veidemann.api.uricanonicalizer.v1.CanonicalizeRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.veidemann.api.uricanonicalizer.v1.CanonicalizeRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.veidemann.api.uricanonicalizer.v1.CanonicalizeRequest.displayName = 'proto.veidemann.api.uricanonicalizer.v1.CanonicalizeRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.veidemann.api.uricanonicalizer.v1.CanonicalizeResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.veidemann.api.uricanonicalizer.v1.CanonicalizeResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.veidemann.api.uricanonicalizer.v1.CanonicalizeResponse.displayName = 'proto.veidemann.api.uricanonicalizer.v1.CanonicalizeResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.veidemann.api.uricanonicalizer.v1.CanonicalizeRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.veidemann.api.uricanonicalizer.v1.CanonicalizeRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.veidemann.api.uricanonicalizer.v1.CanonicalizeRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.veidemann.api.uricanonicalizer.v1.CanonicalizeRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
uri: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.veidemann.api.uricanonicalizer.v1.CanonicalizeRequest}
 */
proto.veidemann.api.uricanonicalizer.v1.CanonicalizeRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.veidemann.api.uricanonicalizer.v1.CanonicalizeRequest;
  return proto.veidemann.api.uricanonicalizer.v1.CanonicalizeRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.veidemann.api.uricanonicalizer.v1.CanonicalizeRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.veidemann.api.uricanonicalizer.v1.CanonicalizeRequest}
 */
proto.veidemann.api.uricanonicalizer.v1.CanonicalizeRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUri(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.veidemann.api.uricanonicalizer.v1.CanonicalizeRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.veidemann.api.uricanonicalizer.v1.CanonicalizeRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.veidemann.api.uricanonicalizer.v1.CanonicalizeRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.veidemann.api.uricanonicalizer.v1.CanonicalizeRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUri();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string uri = 1;
 * @return {string}
 */
proto.veidemann.api.uricanonicalizer.v1.CanonicalizeRequest.prototype.getUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.veidemann.api.uricanonicalizer.v1.CanonicalizeRequest} returns this
 */
proto.veidemann.api.uricanonicalizer.v1.CanonicalizeRequest.prototype.setUri = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.veidemann.api.uricanonicalizer.v1.CanonicalizeResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.veidemann.api.uricanonicalizer.v1.CanonicalizeResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.veidemann.api.uricanonicalizer.v1.CanonicalizeResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.veidemann.api.uricanonicalizer.v1.CanonicalizeResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
uri: (f = msg.getUri()) && commons_v1_resources_pb.ParsedUri.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.veidemann.api.uricanonicalizer.v1.CanonicalizeResponse}
 */
proto.veidemann.api.uricanonicalizer.v1.CanonicalizeResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.veidemann.api.uricanonicalizer.v1.CanonicalizeResponse;
  return proto.veidemann.api.uricanonicalizer.v1.CanonicalizeResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.veidemann.api.uricanonicalizer.v1.CanonicalizeResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.veidemann.api.uricanonicalizer.v1.CanonicalizeResponse}
 */
proto.veidemann.api.uricanonicalizer.v1.CanonicalizeResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new commons_v1_resources_pb.ParsedUri;
      reader.readMessage(value,commons_v1_resources_pb.ParsedUri.deserializeBinaryFromReader);
      msg.setUri(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.veidemann.api.uricanonicalizer.v1.CanonicalizeResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.veidemann.api.uricanonicalizer.v1.CanonicalizeResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.veidemann.api.uricanonicalizer.v1.CanonicalizeResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.veidemann.api.uricanonicalizer.v1.CanonicalizeResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUri();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      commons_v1_resources_pb.ParsedUri.serializeBinaryToWriter
    );
  }
};


/**
 * optional veidemann.api.commons.v1.ParsedUri uri = 1;
 * @return {?proto.veidemann.api.commons.v1.ParsedUri}
 */
proto.veidemann.api.uricanonicalizer.v1.CanonicalizeResponse.prototype.getUri = function() {
  return /** @type{?proto.veidemann.api.commons.v1.ParsedUri} */ (
    jspb.Message.getWrapperField(this, commons_v1_resources_pb.ParsedUri, 1));
};


/**
 * @param {?proto.veidemann.api.commons.v1.ParsedUri|undefined} value
 * @return {!proto.veidemann.api.uricanonicalizer.v1.CanonicalizeResponse} returns this
*/
proto.veidemann.api.uricanonicalizer.v1.CanonicalizeResponse.prototype.setUri = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.veidemann.api.uricanonicalizer.v1.CanonicalizeResponse} returns this
 */
proto.veidemann.api.uricanonicalizer.v1.CanonicalizeResponse.prototype.clearUri = function() {
  return this.setUri(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.veidemann.api.uricanonicalizer.v1.CanonicalizeResponse.prototype.hasUri = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.veidemann.api.uricanonicalizer.v1);
