name: Golang Test
description: Test Golang code

inputs:
  working-directory:
    required: true
    description: "The path to the component to test"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - run: go test ./...
      shell: bash
      working-directory: ${{ inputs.working-directory }}
