---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harvester
spec:
  template:
    spec:
      # volumes:
      #   - name: chromium-policy
      #     configMap:
      #       name: chromium-policy
      containers:
        - name: browser-controller
          env:
            - name: LOG_LEVEL
              value: INFO
        # - name: browser
        #   volumeMounts:
        #     - name: chromium-policy
        #       mountPath: /etc/chromium/policies/managed
        #       readOnly: true
