{
 "title": "RethinkDB",
 "tags": [
  "kubernetes",
  "prometheus",
  "kube-prometheus-stack",
  "datastore",
  "rethinkdb",
  "database",
  "infrastructure"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "server_var", "label": "Server", "query": "label_values(server)" },
   { "name": "db_var", "label": "Database", "query": "label_values(db)" },
   {
    "name": "table_var",
    "label": "Table",
    "query": "label_values({db=~\"$db_var\"}, table)"
   }
  ]
 },
 "panels": [
  { "title": "Stats collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Stat collection duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "scrape_latency", "legendFormat": "duration" }
   ]
  },
  {
   "title": "Stat collection errors count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scrape_errors", "legendFormat": "errors count" }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Cluster Docs per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cluster_docs_per_second", "legendFormat": "{{operation}}" }
   ]
  },
  {
   "title": "Cluster client connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cluster_client_connections", "legendFormat": "connections count" }
   ]
  },
  { "title": "Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Server Queries per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "server_queries_per_second{server=~\"$server_var\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Server client connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "server_client_connections{server=~\"$server_var\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Server Docs per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "server_docs_per_second{server=~\"$server_var\"}",
     "legendFormat": "{{server}}::{{operation}}"
    }
   ]
  },
  { "title": "Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Table Docs per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "table_docs_per_second{db=~\"$db_var\", table=~\"$table_var\"}",
     "legendFormat": "{{db}}.{{table}}::{{operation}}"
    }
   ]
  },
  {
   "title": "Table replica Docs per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tablereplica_docs_per_second{db=~\"$db_var\", table=~\"$table_var\", server=~\"$server_var\"}",
     "legendFormat": "{{db}}.{{table}}::{{operation}}::{{server}}"
    }
   ]
  },
  {
   "title": "Table Rows count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "table_rows_count{db=~\"$db_var\", table=~\"$table_var\"}",
     "legendFormat": "{{db}}.{{table}}"
    }
   ]
  },
  {
   "title": "Table replica Cache bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "tablereplica_cache_bytes{db=~\"$db_var\", table=~\"$table_var\", server=~\"$server_var\"}",
     "legendFormat": "{{db}}.{{table}}::{{server}}"
    }
   ]
  },
  {
   "title": "Table replica disk io bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "tablereplica_io{db=~\"$db_var\", table=~\"$table_var\", server=~\"$server_var\"}",
     "legendFormat": "{{db}}.{{table}}::{{operation}}::{{server}}"
    }
   ]
  },
  {
   "title": "Table replica Disk data bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "tablereplica_data_bytes{db=~\"$db_var\", table=~\"$table_var\", server=~\"$server_var\"}",
     "legendFormat": "{{db}}.{{table}}::{{server}}"
    }
   ]
  }
 ]
}