{
 "title": "Veidemann / Job Status",
 "tags": [
  "veidemann",
  "kubernetes",
  "prometheus",
  "kube-prometheus-stack",
  "application",
  "veidemann-job-status",
  "service"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job_name",
    "label": "Job Name",
    "query": "label_values(veidemann_job_status_total, job_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Gjenværende seeds å høste",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(veidemann_job_status_total{job_name=~\"$job_name\", status=~\"FETCHING|SLEEPING|CREATED|FINISHED|FAILED\"}) - sum(veidemann_job_status_total{job_name=~\"$job_name\", status=~\"FINISHED|FAILED\"})",
     "legendFormat": "seeds"
    }
   ]
  },
  {
   "title": "Seeds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(veidemann_job_status_total{job_name=~\"$job_name\", status=~\"FINISHED|FAILED\"})",
     "legendFormat": "finished"
    },
    {
     "expr": "sum(veidemann_job_status_total{job_name=~\"$job_name\", status=~\"ABORTED\"})",
     "legendFormat": "aborted"
    },
    {
     "expr": "sum(veidemann_job_status_total{job_name=~\"$job_name\", status=~\"FETCHING|SLEEPING|CREATED|FINISHED|FAILED\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Pages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "veidemann_job_size_total{job_name=~\"$job_name\", type=~\"documents.*\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Bytes crawled",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "veidemann_job_size_total{job_name=~\"$job_name\", type=~\"bytesCrawled\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Out of Scope Handler requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(veidemann_oos_requests_total)",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(veidemann_oos_requests_total) - sum(veidemann_oos_requests_duplicate_total)",
     "legendFormat": "new"
    },
    {
     "expr": "sum(irate(veidemann_oos_requests_total[5m]))",
     "legendFormat": "requests/second"
    },
    {
     "expr": "sum(irate(veidemann_oos_requests_total[5m])) - sum(irate(veidemann_oos_requests_duplicate_total[5m]))",
     "legendFormat": "new/second"
    }
   ]
  }
 ]
}