{
 "title": "Veidemann / Cache",
 "tags": [
  "squid",
  "veidemann",
  "kubernetes",
  "prometheus",
  "kube-prometheus-stack",
  "application",
  "veidemann-cache",
  "service",
  "cache"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "child_pod",
    "label": "child pod",
    "query": "label_values(up{service=\"cache-balancer\"}, pod)"
   },
   {
    "name": "parent_pod",
    "label": "parent pod",
    "query": "label_values(up{service=\"cache\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Child Services Up",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{service=\"cache-balancer\",pod=~\"$child_pod\"})"
    }
   ]
  },
  {
   "title": "Parent Services Up",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{service=\"cache\",pod=~\"$parent_pod\"})"
    }
   ]
  },
  {
   "title": "Parent Cache Hit Rate",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(squid_client_http_hits_total{service=\"cache\",pod=~\"$parent_pod\"}) / sum(squid_client_http_requests_total{service=\"cache\",pod=~\"$parent_pod\"})",
     "legendFormat": "Hit rate"
    }
   ]
  },
  {
   "title": "Parent Bytes Hit Rate",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(squid_client_http_hit_kbytes_out_bytes_total{service=\"cache\",pod=~\"$parent_pod\"}) / sum(squid_client_http_kbytes_out_kbytes_total{service=\"cache\",pod=~\"$parent_pod\"})"
    }
   ]
  },
  {
   "title": "Child Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(squid_client_http_hits_total{service=\"cache-balancer\",pod=~\"$child_pod\"}[5m]))",
     "legendFormat": "Child HTTP hits"
    },
    {
     "expr": "sum(rate(squid_client_http_requests_total{service=\"cache-balancer\",pod=~\"$child_pod\"}[5m]))",
     "legendFormat": "Child requests"
    },
    {
     "expr": "sum(rate(squid_client_http_errors_total{service=\"cache-balancer\",pod=~\"$child_pod\"}[5m]))",
     "legendFormat": "Child errors"
    },
    {
     "expr": "rate(squid_client_http_requests_total{service=\"cache-balancer\",pod=~\"$child_pod\"}[5m])",
     "legendFormat": "Child {{ pod }}"
    }
   ]
  },
  {
   "title": "Parent Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(squid_client_http_kbytes_in_kbytes_total{service=\"cache\",pod=~\"$parent_pod\"}[5m])) * -1",
     "legendFormat": "Parent traffic in"
    },
    {
     "expr": "sum(rate(squid_client_http_kbytes_out_kbytes_total{service=\"cache\",pod=~\"$parent_pod\"}[5m]))",
     "legendFormat": "Parent traffic out"
    },
    {
     "expr": "sum(rate(squid_client_http_hit_kbytes_out_bytes_total{service=\"cache\",pod=~\"$parent_pod\"}[5m]))",
     "legendFormat": "Parent hit bytes out"
    }
   ]
  },
  {
   "title": "Parent Swap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(squid_swap_files_cleaned_total{service=\"cache\",pod=~\"$parent_pod\"}[5m]))",
     "legendFormat": "Parent swap files cleaned"
    },
    {
     "expr": "sum(rate(squid_swap_ins_total{service=\"cache\",pod=~\"$parent_pod\"}[5m]))",
     "legendFormat": "Parent swap ins"
    },
    {
     "expr": "sum(rate(squid_swap_outs_total{service=\"cache\",pod=~\"$parent_pod\"}[5m]))",
     "legendFormat": "Parent swap outs"
    }
   ]
  }
 ]
}