// @generated by protoc-gen-es v2.10.1 with parameter "target=ts,import_extension=none"
// @generated from file browsercontroller/v2/browsercontroller.proto (package veidemann.api.browsercontroller.v2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { ConfigRef } from "../../config/v1/resources_pb";
import { file_config_v1_resources } from "../../config/v1/resources_pb";
import type { CrawlLog } from "../../log/v1/resources_pb";
import { file_log_v1_resources } from "../../log/v1/resources_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file browsercontroller/v2/browsercontroller.proto.
 */
export const file_browsercontroller_v2_browsercontroller: GenFile = /*@__PURE__*/
  fileDesc("Cixicm93c2VyY29udHJvbGxlci92Mi9icm93c2VyY29udHJvbGxlci5wcm90bxIidmVpZGVtYW5uLmFwaS5icm93c2VyY29udHJvbGxlci52MiLOAQoXUmVnaXN0ZXJSZXNvdXJjZVJlcXVlc3QSEAoIcHJveHlfaWQYASABKAUSCwoDdXJpGAIgASgJEhoKEmNyYXdsX2V4ZWN1dGlvbl9pZBgDIAEoCRIYChBqb2JfZXhlY3V0aW9uX2lkGAQgASgJEjoKDmNvbGxlY3Rpb25fcmVmGAUgASgLMiIudmVpZGVtYW5uLmFwaS5jb25maWcudjEuQ29uZmlnUmVmEg4KBm1ldGhvZBgGIAEoCRISCgpyZXF1ZXN0X2lkGAcgASgJIoYBChJSZXNvdXJjZVJlZ2lzdGVyZWQSGgoSY3Jhd2xfZXhlY3V0aW9uX2lkGAEgASgJEhgKEGpvYl9leGVjdXRpb25faWQYAiABKAkSOgoOY29sbGVjdGlvbl9yZWYYAyABKAsyIi52ZWlkZW1hbm4uYXBpLmNvbmZpZy52MS5Db25maWdSZWYigQEKFVJlZ2lzdGVyUmVzb3VyY2VSZXBseRJMCgpyZWdpc3RlcmVkGAEgASgLMjYudmVpZGVtYW5uLmFwaS5icm93c2VyY29udHJvbGxlci52Mi5SZXNvdXJjZVJlZ2lzdGVyZWRIABIQCgZjYW5jZWwYAiABKAlIAEIICgZyZXN1bHQiggEKF0NvbXBsZXRlUmVzb3VyY2VSZXF1ZXN0EhAKCHByb3h5X2lkGAEgASgFEhIKCnJlcXVlc3RfaWQYAiABKAkSMQoJY3Jhd2xfbG9nGAMgASgLMh4udmVpZGVtYW5uLmFwaS5sb2cudjEuQ3Jhd2xMb2cSDgoGY2FjaGVkGAQgASgIIhcKFUNvbXBsZXRlUmVzb3VyY2VSZXBseTKxAgoRQnJvd3NlckNvbnRyb2xsZXISjAEKEHJlZ2lzdGVyUmVzb3VyY2USOy52ZWlkZW1hbm4uYXBpLmJyb3dzZXJjb250cm9sbGVyLnYyLlJlZ2lzdGVyUmVzb3VyY2VSZXF1ZXN0GjkudmVpZGVtYW5uLmFwaS5icm93c2VyY29udHJvbGxlci52Mi5SZWdpc3RlclJlc291cmNlUmVwbHkiABKMAQoQY29tcGxldGVSZXNvdXJjZRI7LnZlaWRlbWFubi5hcGkuYnJvd3NlcmNvbnRyb2xsZXIudjIuQ29tcGxldGVSZXNvdXJjZVJlcXVlc3QaOS52ZWlkZW1hbm4uYXBpLmJyb3dzZXJjb250cm9sbGVyLnYyLkNvbXBsZXRlUmVzb3VyY2VSZXBseSIAQkdaRWdpdGh1Yi5jb20vTmF0aW9uYWxMaWJyYXJ5T2ZOb3J3YXkvdmVpZGVtYW5uL2FwaS9icm93c2VyY29udHJvbGxlci92MmIGcHJvdG8z", [file_config_v1_resources, file_log_v1_resources]);

/**
 * @generated from message veidemann.api.browsercontroller.v2.RegisterResourceRequest
 */
export type RegisterResourceRequest = Message<"veidemann.api.browsercontroller.v2.RegisterResourceRequest"> & {
  /**
   * @generated from field: int32 proxy_id = 1;
   */
  proxyId: number;

  /**
   * @generated from field: string uri = 2;
   */
  uri: string;

  /**
   * @generated from field: string crawl_execution_id = 3;
   */
  crawlExecutionId: string;

  /**
   * @generated from field: string job_execution_id = 4;
   */
  jobExecutionId: string;

  /**
   * @generated from field: veidemann.api.config.v1.ConfigRef collection_ref = 5;
   */
  collectionRef?: ConfigRef;

  /**
   * @generated from field: string method = 6;
   */
  method: string;

  /**
   * @generated from field: string request_id = 7;
   */
  requestId: string;
};

/**
 * Describes the message veidemann.api.browsercontroller.v2.RegisterResourceRequest.
 * Use `create(RegisterResourceRequestSchema)` to create a new message.
 */
export const RegisterResourceRequestSchema: GenMessage<RegisterResourceRequest> = /*@__PURE__*/
  messageDesc(file_browsercontroller_v2_browsercontroller, 0);

/**
 * @generated from message veidemann.api.browsercontroller.v2.ResourceRegistered
 */
export type ResourceRegistered = Message<"veidemann.api.browsercontroller.v2.ResourceRegistered"> & {
  /**
   * @generated from field: string crawl_execution_id = 1;
   */
  crawlExecutionId: string;

  /**
   * @generated from field: string job_execution_id = 2;
   */
  jobExecutionId: string;

  /**
   * @generated from field: veidemann.api.config.v1.ConfigRef collection_ref = 3;
   */
  collectionRef?: ConfigRef;
};

/**
 * Describes the message veidemann.api.browsercontroller.v2.ResourceRegistered.
 * Use `create(ResourceRegisteredSchema)` to create a new message.
 */
export const ResourceRegisteredSchema: GenMessage<ResourceRegistered> = /*@__PURE__*/
  messageDesc(file_browsercontroller_v2_browsercontroller, 1);

/**
 * @generated from message veidemann.api.browsercontroller.v2.RegisterResourceReply
 */
export type RegisterResourceReply = Message<"veidemann.api.browsercontroller.v2.RegisterResourceReply"> & {
  /**
   * @generated from oneof veidemann.api.browsercontroller.v2.RegisterResourceReply.result
   */
  result: {
    /**
     * @generated from field: veidemann.api.browsercontroller.v2.ResourceRegistered registered = 1;
     */
    value: ResourceRegistered;
    case: "registered";
  } | {
    /**
     * @generated from field: string cancel = 2;
     */
    value: string;
    case: "cancel";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message veidemann.api.browsercontroller.v2.RegisterResourceReply.
 * Use `create(RegisterResourceReplySchema)` to create a new message.
 */
export const RegisterResourceReplySchema: GenMessage<RegisterResourceReply> = /*@__PURE__*/
  messageDesc(file_browsercontroller_v2_browsercontroller, 2);

/**
 * @generated from message veidemann.api.browsercontroller.v2.CompleteResourceRequest
 */
export type CompleteResourceRequest = Message<"veidemann.api.browsercontroller.v2.CompleteResourceRequest"> & {
  /**
   * @generated from field: int32 proxy_id = 1;
   */
  proxyId: number;

  /**
   * @generated from field: string request_id = 2;
   */
  requestId: string;

  /**
   * @generated from field: veidemann.api.log.v1.CrawlLog crawl_log = 3;
   */
  crawlLog?: CrawlLog;

  /**
   * @generated from field: bool cached = 4;
   */
  cached: boolean;
};

/**
 * Describes the message veidemann.api.browsercontroller.v2.CompleteResourceRequest.
 * Use `create(CompleteResourceRequestSchema)` to create a new message.
 */
export const CompleteResourceRequestSchema: GenMessage<CompleteResourceRequest> = /*@__PURE__*/
  messageDesc(file_browsercontroller_v2_browsercontroller, 3);

/**
 * @generated from message veidemann.api.browsercontroller.v2.CompleteResourceReply
 */
export type CompleteResourceReply = Message<"veidemann.api.browsercontroller.v2.CompleteResourceReply"> & {
};

/**
 * Describes the message veidemann.api.browsercontroller.v2.CompleteResourceReply.
 * Use `create(CompleteResourceReplySchema)` to create a new message.
 */
export const CompleteResourceReplySchema: GenMessage<CompleteResourceReply> = /*@__PURE__*/
  messageDesc(file_browsercontroller_v2_browsercontroller, 4);

/**
 * @generated from service veidemann.api.browsercontroller.v2.BrowserController
 */
export const BrowserController: GenService<{
  /**
   * @generated from rpc veidemann.api.browsercontroller.v2.BrowserController.registerResource
   */
  registerResource: {
    methodKind: "unary";
    input: typeof RegisterResourceRequestSchema;
    output: typeof RegisterResourceReplySchema;
  },
  /**
   * @generated from rpc veidemann.api.browsercontroller.v2.BrowserController.completeResource
   */
  completeResource: {
    methodKind: "unary";
    input: typeof CompleteResourceRequestSchema;
    output: typeof CompleteResourceReplySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_browsercontroller_v2_browsercontroller, 0);

