// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: controller/v1/controller.proto

package controller

import (
	context "context"
	frontier "github.com/NationalLibraryOfNorway/veidemann/api/frontier"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Controller_GetRolesForActiveUser_FullMethodName       = "/veidemann.api.controller.v1.Controller/GetRolesForActiveUser"
	Controller_RunCrawl_FullMethodName                    = "/veidemann.api.controller.v1.Controller/RunCrawl"
	Controller_AbortCrawlExecution_FullMethodName         = "/veidemann.api.controller.v1.Controller/AbortCrawlExecution"
	Controller_AbortJobExecution_FullMethodName           = "/veidemann.api.controller.v1.Controller/AbortJobExecution"
	Controller_GetOpenIdConnectIssuer_FullMethodName      = "/veidemann.api.controller.v1.Controller/GetOpenIdConnectIssuer"
	Controller_PauseCrawler_FullMethodName                = "/veidemann.api.controller.v1.Controller/PauseCrawler"
	Controller_UnPauseCrawler_FullMethodName              = "/veidemann.api.controller.v1.Controller/UnPauseCrawler"
	Controller_Status_FullMethodName                      = "/veidemann.api.controller.v1.Controller/Status"
	Controller_QueueCountForCrawlExecution_FullMethodName = "/veidemann.api.controller.v1.Controller/QueueCountForCrawlExecution"
	Controller_QueueCountForCrawlHostGroup_FullMethodName = "/veidemann.api.controller.v1.Controller/QueueCountForCrawlHostGroup"
)

// ControllerClient is the client API for Controller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for communicating with controller.
type ControllerClient interface {
	GetRolesForActiveUser(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RoleList, error)
	RunCrawl(ctx context.Context, in *RunCrawlRequest, opts ...grpc.CallOption) (*RunCrawlReply, error)
	// Abort a crawl execution
	AbortCrawlExecution(ctx context.Context, in *ExecutionId, opts ...grpc.CallOption) (*frontier.CrawlExecutionStatus, error)
	// Abort a job execution
	AbortJobExecution(ctx context.Context, in *ExecutionId, opts ...grpc.CallOption) (*frontier.JobExecutionStatus, error)
	// Get the configured OpenID connect issuer address
	GetOpenIdConnectIssuer(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OpenIdConnectIssuerReply, error)
	PauseCrawler(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UnPauseCrawler(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Status(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CrawlerStatus, error)
	// Number of queued URI's for a CrawlExecution
	QueueCountForCrawlExecution(ctx context.Context, in *frontier.CrawlExecutionId, opts ...grpc.CallOption) (*frontier.CountResponse, error)
	// Number of queued URI's for a CrawlHostGroup
	QueueCountForCrawlHostGroup(ctx context.Context, in *frontier.CrawlHostGroup, opts ...grpc.CallOption) (*frontier.CountResponse, error)
}

type controllerClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerClient(cc grpc.ClientConnInterface) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) GetRolesForActiveUser(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RoleList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoleList)
	err := c.cc.Invoke(ctx, Controller_GetRolesForActiveUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) RunCrawl(ctx context.Context, in *RunCrawlRequest, opts ...grpc.CallOption) (*RunCrawlReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunCrawlReply)
	err := c.cc.Invoke(ctx, Controller_RunCrawl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) AbortCrawlExecution(ctx context.Context, in *ExecutionId, opts ...grpc.CallOption) (*frontier.CrawlExecutionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(frontier.CrawlExecutionStatus)
	err := c.cc.Invoke(ctx, Controller_AbortCrawlExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) AbortJobExecution(ctx context.Context, in *ExecutionId, opts ...grpc.CallOption) (*frontier.JobExecutionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(frontier.JobExecutionStatus)
	err := c.cc.Invoke(ctx, Controller_AbortJobExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) GetOpenIdConnectIssuer(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OpenIdConnectIssuerReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenIdConnectIssuerReply)
	err := c.cc.Invoke(ctx, Controller_GetOpenIdConnectIssuer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) PauseCrawler(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Controller_PauseCrawler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) UnPauseCrawler(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Controller_UnPauseCrawler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) Status(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CrawlerStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrawlerStatus)
	err := c.cc.Invoke(ctx, Controller_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) QueueCountForCrawlExecution(ctx context.Context, in *frontier.CrawlExecutionId, opts ...grpc.CallOption) (*frontier.CountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(frontier.CountResponse)
	err := c.cc.Invoke(ctx, Controller_QueueCountForCrawlExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) QueueCountForCrawlHostGroup(ctx context.Context, in *frontier.CrawlHostGroup, opts ...grpc.CallOption) (*frontier.CountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(frontier.CountResponse)
	err := c.cc.Invoke(ctx, Controller_QueueCountForCrawlHostGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServer is the server API for Controller service.
// All implementations must embed UnimplementedControllerServer
// for forward compatibility.
//
// Service for communicating with controller.
type ControllerServer interface {
	GetRolesForActiveUser(context.Context, *emptypb.Empty) (*RoleList, error)
	RunCrawl(context.Context, *RunCrawlRequest) (*RunCrawlReply, error)
	// Abort a crawl execution
	AbortCrawlExecution(context.Context, *ExecutionId) (*frontier.CrawlExecutionStatus, error)
	// Abort a job execution
	AbortJobExecution(context.Context, *ExecutionId) (*frontier.JobExecutionStatus, error)
	// Get the configured OpenID connect issuer address
	GetOpenIdConnectIssuer(context.Context, *emptypb.Empty) (*OpenIdConnectIssuerReply, error)
	PauseCrawler(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	UnPauseCrawler(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	Status(context.Context, *emptypb.Empty) (*CrawlerStatus, error)
	// Number of queued URI's for a CrawlExecution
	QueueCountForCrawlExecution(context.Context, *frontier.CrawlExecutionId) (*frontier.CountResponse, error)
	// Number of queued URI's for a CrawlHostGroup
	QueueCountForCrawlHostGroup(context.Context, *frontier.CrawlHostGroup) (*frontier.CountResponse, error)
	mustEmbedUnimplementedControllerServer()
}

// UnimplementedControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControllerServer struct{}

func (UnimplementedControllerServer) GetRolesForActiveUser(context.Context, *emptypb.Empty) (*RoleList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRolesForActiveUser not implemented")
}
func (UnimplementedControllerServer) RunCrawl(context.Context, *RunCrawlRequest) (*RunCrawlReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunCrawl not implemented")
}
func (UnimplementedControllerServer) AbortCrawlExecution(context.Context, *ExecutionId) (*frontier.CrawlExecutionStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbortCrawlExecution not implemented")
}
func (UnimplementedControllerServer) AbortJobExecution(context.Context, *ExecutionId) (*frontier.JobExecutionStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbortJobExecution not implemented")
}
func (UnimplementedControllerServer) GetOpenIdConnectIssuer(context.Context, *emptypb.Empty) (*OpenIdConnectIssuerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOpenIdConnectIssuer not implemented")
}
func (UnimplementedControllerServer) PauseCrawler(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseCrawler not implemented")
}
func (UnimplementedControllerServer) UnPauseCrawler(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnPauseCrawler not implemented")
}
func (UnimplementedControllerServer) Status(context.Context, *emptypb.Empty) (*CrawlerStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedControllerServer) QueueCountForCrawlExecution(context.Context, *frontier.CrawlExecutionId) (*frontier.CountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueueCountForCrawlExecution not implemented")
}
func (UnimplementedControllerServer) QueueCountForCrawlHostGroup(context.Context, *frontier.CrawlHostGroup) (*frontier.CountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueueCountForCrawlHostGroup not implemented")
}
func (UnimplementedControllerServer) mustEmbedUnimplementedControllerServer() {}
func (UnimplementedControllerServer) testEmbeddedByValue()                    {}

// UnsafeControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerServer will
// result in compilation errors.
type UnsafeControllerServer interface {
	mustEmbedUnimplementedControllerServer()
}

func RegisterControllerServer(s grpc.ServiceRegistrar, srv ControllerServer) {
	// If the following call pancis, it indicates UnimplementedControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Controller_ServiceDesc, srv)
}

func _Controller_GetRolesForActiveUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).GetRolesForActiveUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_GetRolesForActiveUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).GetRolesForActiveUser(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_RunCrawl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunCrawlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).RunCrawl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_RunCrawl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).RunCrawl(ctx, req.(*RunCrawlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_AbortCrawlExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutionId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).AbortCrawlExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_AbortCrawlExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).AbortCrawlExecution(ctx, req.(*ExecutionId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_AbortJobExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutionId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).AbortJobExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_AbortJobExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).AbortJobExecution(ctx, req.(*ExecutionId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_GetOpenIdConnectIssuer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).GetOpenIdConnectIssuer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_GetOpenIdConnectIssuer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).GetOpenIdConnectIssuer(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_PauseCrawler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).PauseCrawler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_PauseCrawler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).PauseCrawler(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_UnPauseCrawler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).UnPauseCrawler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_UnPauseCrawler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).UnPauseCrawler(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).Status(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_QueueCountForCrawlExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(frontier.CrawlExecutionId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).QueueCountForCrawlExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_QueueCountForCrawlExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).QueueCountForCrawlExecution(ctx, req.(*frontier.CrawlExecutionId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_QueueCountForCrawlHostGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(frontier.CrawlHostGroup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).QueueCountForCrawlHostGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_QueueCountForCrawlHostGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).QueueCountForCrawlHostGroup(ctx, req.(*frontier.CrawlHostGroup))
	}
	return interceptor(ctx, in, info, handler)
}

// Controller_ServiceDesc is the grpc.ServiceDesc for Controller service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Controller_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "veidemann.api.controller.v1.Controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRolesForActiveUser",
			Handler:    _Controller_GetRolesForActiveUser_Handler,
		},
		{
			MethodName: "RunCrawl",
			Handler:    _Controller_RunCrawl_Handler,
		},
		{
			MethodName: "AbortCrawlExecution",
			Handler:    _Controller_AbortCrawlExecution_Handler,
		},
		{
			MethodName: "AbortJobExecution",
			Handler:    _Controller_AbortJobExecution_Handler,
		},
		{
			MethodName: "GetOpenIdConnectIssuer",
			Handler:    _Controller_GetOpenIdConnectIssuer_Handler,
		},
		{
			MethodName: "PauseCrawler",
			Handler:    _Controller_PauseCrawler_Handler,
		},
		{
			MethodName: "UnPauseCrawler",
			Handler:    _Controller_UnPauseCrawler_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Controller_Status_Handler,
		},
		{
			MethodName: "QueueCountForCrawlExecution",
			Handler:    _Controller_QueueCountForCrawlExecution_Handler,
		},
		{
			MethodName: "QueueCountForCrawlHostGroup",
			Handler:    _Controller_QueueCountForCrawlHostGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controller/v1/controller.proto",
}
