{
 "title": "Veidemann / Overview",
 "tags": [
  "veidemann",
  "kubernetes",
  "prometheus",
  "kube-prometheus-stack"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "URI requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(veidemann_uri_requests_total[5m]))",
     "legendFormat": "requests total"
    },
    {
     "expr": "sum(rate(veidemann_uri_requests_failed_total[5m]))  ",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(rate(veidemann_uri_record_type_total[5m])) by (type)",
     "legendFormat": "record type {{ type }}"
    }
   ]
  },
  {
   "title": "Page requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(veidemann_page_requests_total[5m]))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Response status codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(veidemann_uri_statuscode_total[5m])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Uri per side",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum(rate(veidemann_page_outlinks_total_sum[5m])) / sum(rate( veidemann_page_outlinks_total_count[5m]))",
     "legendFormat": "outlinks"
    },
    {
     "expr": " sum(rate(veidemann_page_resources_total_sum[5m])) / sum(rate( veidemann_page_resources_total_count[5m]))",
     "legendFormat": "resources"
    },
    {
     "expr": "sum(rate(veidemann_page_resources_cache_hit_total_sum[5m])) / sum(rate( veidemann_page_resources_total_count[5m]))",
     "legendFormat": "resource cache hits"
    },
    {
     "expr": "sum(rate(veidemann_page_resources_cache_miss_total_sum[5m])) / sum(rate( veidemann_page_resources_total_count[5m]))",
     "legendFormat": "resource cache miss"
    }
   ]
  },
  {
   "title": "Fetch time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(veidemann_uri_fetch_time_seconds_sum[5m]))/sum(rate(veidemann_uri_fetch_time_seconds_count[5m]))",
     "legendFormat": "fetch time"
    }
   ]
  },
  {
   "title": "Fetched bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(veidemann_uri_size_bytes_sum[5m]))/sum(rate(veidemann_uri_size_bytes_count[5m]))",
     "legendFormat": "bytes/uri"
    },
    {
     "expr": "sum(rate(veidemann_uri_size_bytes_sum[5m]))",
     "legendFormat": "bytes/sec"
    }
   ]
  },
  {
   "title": "Fordeling mime type siste døgn",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 25 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(veidemann_uri_mime_type_total) by (mime)",
     "legendFormat": "{{ mime }}"
    }
   ]
  },
  {
   "title": "Mime type",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 3, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(veidemann_uri_mime_type_total[5m])) by (mime)",
     "legendFormat": "{{ mime }}"
    }
   ]
  },
  {
   "title": "Cache hit rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 25 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(veidemann_page_resources_cache_hit_total_sum[1m]) / irate(veidemann_page_resources_total_sum[1m])",
     "legendFormat": "Cache hit rate"
    }
   ]
  },
  {
   "title": "URI/sec",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 14, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(veidemann_page_resources_total_sum[1m])) / sum(rate(veidemann_page_resources_total_count[1m]))"
    }
   ]
  },
  {
   "title": "Bytes/sec",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 25 },
   "format": "KBs",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(veidemann_uri_size_bytes_sum[1m])) / 1024"
    }
   ]
  },
  {
   "title": "Linker per sekund",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(veidemann_page_links_total[5m])) by (type)",
     "legendFormat": "{{ type }}"
    },
    {
     "expr": "sum(rate(veidemann_page_links_total[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Antall URI i kø",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "veidemann_uri_queue_count " }
   ]
  },
  {
   "title": "Antall Uri i kø",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(veidemann_uri_queue_count)", "legendFormat": "Uri i kø" }
   ]
  }
 ]
}