apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-service
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 300
      volumes:
        - name: recent-logs
          persistentVolumeClaim:
            claimName: log-service-recent-logs
      containers:
        - name: log-service
          env:
            - name: MODE
              value: recent
          volumeMounts:
            - mountPath: /recent-logs
              name: recent-logs
