apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-service
spec:
  template:
    spec:
      volumes:
        - name: parquet
          persistentVolumeClaim:
            claimName: log-service-parquet
      containers:
        - name: log-service
          env:
            - name: MAX_LINES_PER_FILE
              value: "100"
          volumeMounts:
            - mountPath: /parquet
              name: parquet
