apiVersion: v1
kind: Service
metadata:
  name: olric
  annotations:
    config.linkerd.io/opaque-ports: "3320"
spec:
  clusterIP: None
  selector:
    app: olric
  ports:
    - name: api
      port: 3320
      targetPort: api
      protocol: TCP
    - name: gossip-tcp
      port: 3322
      targetPort: gossip-tcp
      protocol: TCP
    - name: gossip-udp
      port: 3322
      targetPort: gossip-udp
      protocol: UDP

---

apiVersion: v1
kind: Service
metadata:
  name: olric-client
  annotations:
    config.linkerd.io/opaque-ports: "3320"
spec:
  type: ClusterIP
  selector:
    app: olric
  ports:
    - port: 3320
      protocol: TCP
      targetPort: api
