// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: dnsresolver/v1/dnsresolver.proto

package v1

import (
	v11 "github.com/NationalLibraryOfNorway/veidemann/api/commons/v1"
	v1 "github.com/NationalLibraryOfNorway/veidemann/api/config/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,6,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	CollectionRef *v1.ConfigRef          `protobuf:"bytes,7,opt,name=collection_ref,json=collectionRef,proto3" json:"collection_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_dnsresolver_v1_dnsresolver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dnsresolver_v1_dnsresolver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_dnsresolver_v1_dnsresolver_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ResolveRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ResolveRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ResolveRequest) GetCollectionRef() *v1.ConfigRef {
	if x != nil {
		return x.CollectionRef
	}
	return nil
}

type ResolveReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	TextualIp     string                 `protobuf:"bytes,3,opt,name=textual_ip,json=textualIp,proto3" json:"textual_ip,omitempty"`
	RawIp         []byte                 `protobuf:"bytes,4,opt,name=raw_ip,json=rawIp,proto3" json:"raw_ip,omitempty"`
	Error         *v11.Error             `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveReply) Reset() {
	*x = ResolveReply{}
	mi := &file_dnsresolver_v1_dnsresolver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveReply) ProtoMessage() {}

func (x *ResolveReply) ProtoReflect() protoreflect.Message {
	mi := &file_dnsresolver_v1_dnsresolver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveReply.ProtoReflect.Descriptor instead.
func (*ResolveReply) Descriptor() ([]byte, []int) {
	return file_dnsresolver_v1_dnsresolver_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveReply) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ResolveReply) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ResolveReply) GetTextualIp() string {
	if x != nil {
		return x.TextualIp
	}
	return ""
}

func (x *ResolveReply) GetRawIp() []byte {
	if x != nil {
		return x.RawIp
	}
	return nil
}

func (x *ResolveReply) GetError() *v11.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_dnsresolver_v1_dnsresolver_proto protoreflect.FileDescriptor

const file_dnsresolver_v1_dnsresolver_proto_rawDesc = "" +
	"\n" +
	" dnsresolver/v1/dnsresolver.proto\x12\x1cveidemann.api.dnsresolver.v1\x1a\x19config/v1/resources.proto\x1a\x1acommons/v1/resources.proto\"\xa6\x01\n" +
	"\x0eResolveRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12!\n" +
	"\fexecution_id\x18\x06 \x01(\tR\vexecutionId\x12I\n" +
	"\x0ecollection_ref\x18\a \x01(\v2\".veidemann.api.config.v1.ConfigRefR\rcollectionRef\"\xa3\x01\n" +
	"\fResolveReply\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1d\n" +
	"\n" +
	"textual_ip\x18\x03 \x01(\tR\ttextualIp\x12\x15\n" +
	"\x06raw_ip\x18\x04 \x01(\fR\x05rawIp\x125\n" +
	"\x05error\x18\x05 \x01(\v2\x1f.veidemann.api.commons.v1.ErrorR\x05error2t\n" +
	"\vDnsResolver\x12e\n" +
	"\aresolve\x12,.veidemann.api.dnsresolver.v1.ResolveRequest\x1a*.veidemann.api.dnsresolver.v1.ResolveReply\"\x00B\x88\x02\n" +
	" com.veidemann.api.dnsresolver.v1B\x10DnsresolverProtoP\x01Z?github.com/NationalLibraryOfNorway/veidemann/api/dnsresolver/v1\xa2\x02\x03VAD\xaa\x02\x1cVeidemann.Api.Dnsresolver.V1\xca\x02\x1cVeidemann\\Api\\Dnsresolver\\V1\xe2\x02(Veidemann\\Api\\Dnsresolver\\V1\\GPBMetadata\xea\x02\x1fVeidemann::Api::Dnsresolver::V1b\x06proto3"

var (
	file_dnsresolver_v1_dnsresolver_proto_rawDescOnce sync.Once
	file_dnsresolver_v1_dnsresolver_proto_rawDescData []byte
)

func file_dnsresolver_v1_dnsresolver_proto_rawDescGZIP() []byte {
	file_dnsresolver_v1_dnsresolver_proto_rawDescOnce.Do(func() {
		file_dnsresolver_v1_dnsresolver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dnsresolver_v1_dnsresolver_proto_rawDesc), len(file_dnsresolver_v1_dnsresolver_proto_rawDesc)))
	})
	return file_dnsresolver_v1_dnsresolver_proto_rawDescData
}

var file_dnsresolver_v1_dnsresolver_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dnsresolver_v1_dnsresolver_proto_goTypes = []any{
	(*ResolveRequest)(nil), // 0: veidemann.api.dnsresolver.v1.ResolveRequest
	(*ResolveReply)(nil),   // 1: veidemann.api.dnsresolver.v1.ResolveReply
	(*v1.ConfigRef)(nil),   // 2: veidemann.api.config.v1.ConfigRef
	(*v11.Error)(nil),      // 3: veidemann.api.commons.v1.Error
}
var file_dnsresolver_v1_dnsresolver_proto_depIdxs = []int32{
	2, // 0: veidemann.api.dnsresolver.v1.ResolveRequest.collection_ref:type_name -> veidemann.api.config.v1.ConfigRef
	3, // 1: veidemann.api.dnsresolver.v1.ResolveReply.error:type_name -> veidemann.api.commons.v1.Error
	0, // 2: veidemann.api.dnsresolver.v1.DnsResolver.resolve:input_type -> veidemann.api.dnsresolver.v1.ResolveRequest
	1, // 3: veidemann.api.dnsresolver.v1.DnsResolver.resolve:output_type -> veidemann.api.dnsresolver.v1.ResolveReply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dnsresolver_v1_dnsresolver_proto_init() }
func file_dnsresolver_v1_dnsresolver_proto_init() {
	if File_dnsresolver_v1_dnsresolver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dnsresolver_v1_dnsresolver_proto_rawDesc), len(file_dnsresolver_v1_dnsresolver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dnsresolver_v1_dnsresolver_proto_goTypes,
		DependencyIndexes: file_dnsresolver_v1_dnsresolver_proto_depIdxs,
		MessageInfos:      file_dnsresolver_v1_dnsresolver_proto_msgTypes,
	}.Build()
	File_dnsresolver_v1_dnsresolver_proto = out.File
	file_dnsresolver_v1_dnsresolver_proto_goTypes = nil
	file_dnsresolver_v1_dnsresolver_proto_depIdxs = nil
}
