// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: browsercontroller/v2/browsercontroller.proto

package v2

import (
	v1 "github.com/NationalLibraryOfNorway/veidemann/api/config/v1"
	v11 "github.com/NationalLibraryOfNorway/veidemann/api/log/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterResourceRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProxyId          int32                  `protobuf:"varint,1,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"`
	Uri              string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	CrawlExecutionId string                 `protobuf:"bytes,3,opt,name=crawl_execution_id,json=crawlExecutionId,proto3" json:"crawl_execution_id,omitempty"`
	JobExecutionId   string                 `protobuf:"bytes,4,opt,name=job_execution_id,json=jobExecutionId,proto3" json:"job_execution_id,omitempty"`
	CollectionRef    *v1.ConfigRef          `protobuf:"bytes,5,opt,name=collection_ref,json=collectionRef,proto3" json:"collection_ref,omitempty"`
	Method           string                 `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"`
	RequestId        string                 `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterResourceRequest) Reset() {
	*x = RegisterResourceRequest{}
	mi := &file_browsercontroller_v2_browsercontroller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResourceRequest) ProtoMessage() {}

func (x *RegisterResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browsercontroller_v2_browsercontroller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResourceRequest.ProtoReflect.Descriptor instead.
func (*RegisterResourceRequest) Descriptor() ([]byte, []int) {
	return file_browsercontroller_v2_browsercontroller_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterResourceRequest) GetProxyId() int32 {
	if x != nil {
		return x.ProxyId
	}
	return 0
}

func (x *RegisterResourceRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *RegisterResourceRequest) GetCrawlExecutionId() string {
	if x != nil {
		return x.CrawlExecutionId
	}
	return ""
}

func (x *RegisterResourceRequest) GetJobExecutionId() string {
	if x != nil {
		return x.JobExecutionId
	}
	return ""
}

func (x *RegisterResourceRequest) GetCollectionRef() *v1.ConfigRef {
	if x != nil {
		return x.CollectionRef
	}
	return nil
}

func (x *RegisterResourceRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RegisterResourceRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ResourceRegistered struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CrawlExecutionId string                 `protobuf:"bytes,1,opt,name=crawl_execution_id,json=crawlExecutionId,proto3" json:"crawl_execution_id,omitempty"`
	JobExecutionId   string                 `protobuf:"bytes,2,opt,name=job_execution_id,json=jobExecutionId,proto3" json:"job_execution_id,omitempty"`
	CollectionRef    *v1.ConfigRef          `protobuf:"bytes,3,opt,name=collection_ref,json=collectionRef,proto3" json:"collection_ref,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResourceRegistered) Reset() {
	*x = ResourceRegistered{}
	mi := &file_browsercontroller_v2_browsercontroller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRegistered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRegistered) ProtoMessage() {}

func (x *ResourceRegistered) ProtoReflect() protoreflect.Message {
	mi := &file_browsercontroller_v2_browsercontroller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRegistered.ProtoReflect.Descriptor instead.
func (*ResourceRegistered) Descriptor() ([]byte, []int) {
	return file_browsercontroller_v2_browsercontroller_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceRegistered) GetCrawlExecutionId() string {
	if x != nil {
		return x.CrawlExecutionId
	}
	return ""
}

func (x *ResourceRegistered) GetJobExecutionId() string {
	if x != nil {
		return x.JobExecutionId
	}
	return ""
}

func (x *ResourceRegistered) GetCollectionRef() *v1.ConfigRef {
	if x != nil {
		return x.CollectionRef
	}
	return nil
}

type RegisterResourceReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*RegisterResourceReply_Registered
	//	*RegisterResourceReply_Cancel
	Result        isRegisterResourceReply_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResourceReply) Reset() {
	*x = RegisterResourceReply{}
	mi := &file_browsercontroller_v2_browsercontroller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResourceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResourceReply) ProtoMessage() {}

func (x *RegisterResourceReply) ProtoReflect() protoreflect.Message {
	mi := &file_browsercontroller_v2_browsercontroller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResourceReply.ProtoReflect.Descriptor instead.
func (*RegisterResourceReply) Descriptor() ([]byte, []int) {
	return file_browsercontroller_v2_browsercontroller_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResourceReply) GetResult() isRegisterResourceReply_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RegisterResourceReply) GetRegistered() *ResourceRegistered {
	if x != nil {
		if x, ok := x.Result.(*RegisterResourceReply_Registered); ok {
			return x.Registered
		}
	}
	return nil
}

func (x *RegisterResourceReply) GetCancel() string {
	if x != nil {
		if x, ok := x.Result.(*RegisterResourceReply_Cancel); ok {
			return x.Cancel
		}
	}
	return ""
}

type isRegisterResourceReply_Result interface {
	isRegisterResourceReply_Result()
}

type RegisterResourceReply_Registered struct {
	Registered *ResourceRegistered `protobuf:"bytes,1,opt,name=registered,proto3,oneof"`
}

type RegisterResourceReply_Cancel struct {
	Cancel string `protobuf:"bytes,2,opt,name=cancel,proto3,oneof"`
}

func (*RegisterResourceReply_Registered) isRegisterResourceReply_Result() {}

func (*RegisterResourceReply_Cancel) isRegisterResourceReply_Result() {}

type CompleteResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProxyId       int32                  `protobuf:"varint,1,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	CrawlLog      *v11.CrawlLog          `protobuf:"bytes,3,opt,name=crawl_log,json=crawlLog,proto3" json:"crawl_log,omitempty"`
	Cached        bool                   `protobuf:"varint,4,opt,name=cached,proto3" json:"cached,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteResourceRequest) Reset() {
	*x = CompleteResourceRequest{}
	mi := &file_browsercontroller_v2_browsercontroller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteResourceRequest) ProtoMessage() {}

func (x *CompleteResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browsercontroller_v2_browsercontroller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteResourceRequest.ProtoReflect.Descriptor instead.
func (*CompleteResourceRequest) Descriptor() ([]byte, []int) {
	return file_browsercontroller_v2_browsercontroller_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteResourceRequest) GetProxyId() int32 {
	if x != nil {
		return x.ProxyId
	}
	return 0
}

func (x *CompleteResourceRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CompleteResourceRequest) GetCrawlLog() *v11.CrawlLog {
	if x != nil {
		return x.CrawlLog
	}
	return nil
}

func (x *CompleteResourceRequest) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

type CompleteResourceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteResourceReply) Reset() {
	*x = CompleteResourceReply{}
	mi := &file_browsercontroller_v2_browsercontroller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteResourceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteResourceReply) ProtoMessage() {}

func (x *CompleteResourceReply) ProtoReflect() protoreflect.Message {
	mi := &file_browsercontroller_v2_browsercontroller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteResourceReply.ProtoReflect.Descriptor instead.
func (*CompleteResourceReply) Descriptor() ([]byte, []int) {
	return file_browsercontroller_v2_browsercontroller_proto_rawDescGZIP(), []int{4}
}

var File_browsercontroller_v2_browsercontroller_proto protoreflect.FileDescriptor

const file_browsercontroller_v2_browsercontroller_proto_rawDesc = "" +
	"\n" +
	",browsercontroller/v2/browsercontroller.proto\x12\"veidemann.api.browsercontroller.v2\x1a\x19config/v1/resources.proto\x1a\x16log/v1/resources.proto\"\xa0\x02\n" +
	"\x17RegisterResourceRequest\x12\x19\n" +
	"\bproxy_id\x18\x01 \x01(\x05R\aproxyId\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12,\n" +
	"\x12crawl_execution_id\x18\x03 \x01(\tR\x10crawlExecutionId\x12(\n" +
	"\x10job_execution_id\x18\x04 \x01(\tR\x0ejobExecutionId\x12I\n" +
	"\x0ecollection_ref\x18\x05 \x01(\v2\".veidemann.api.config.v1.ConfigRefR\rcollectionRef\x12\x16\n" +
	"\x06method\x18\x06 \x01(\tR\x06method\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\"\xb7\x01\n" +
	"\x12ResourceRegistered\x12,\n" +
	"\x12crawl_execution_id\x18\x01 \x01(\tR\x10crawlExecutionId\x12(\n" +
	"\x10job_execution_id\x18\x02 \x01(\tR\x0ejobExecutionId\x12I\n" +
	"\x0ecollection_ref\x18\x03 \x01(\v2\".veidemann.api.config.v1.ConfigRefR\rcollectionRef\"\x95\x01\n" +
	"\x15RegisterResourceReply\x12X\n" +
	"\n" +
	"registered\x18\x01 \x01(\v26.veidemann.api.browsercontroller.v2.ResourceRegisteredH\x00R\n" +
	"registered\x12\x18\n" +
	"\x06cancel\x18\x02 \x01(\tH\x00R\x06cancelB\b\n" +
	"\x06result\"\xa8\x01\n" +
	"\x17CompleteResourceRequest\x12\x19\n" +
	"\bproxy_id\x18\x01 \x01(\x05R\aproxyId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12;\n" +
	"\tcrawl_log\x18\x03 \x01(\v2\x1e.veidemann.api.log.v1.CrawlLogR\bcrawlLog\x12\x16\n" +
	"\x06cached\x18\x04 \x01(\bR\x06cached\"\x17\n" +
	"\x15CompleteResourceReply2\xb1\x02\n" +
	"\x11BrowserController\x12\x8c\x01\n" +
	"\x10registerResource\x12;.veidemann.api.browsercontroller.v2.RegisterResourceRequest\x1a9.veidemann.api.browsercontroller.v2.RegisterResourceReply\"\x00\x12\x8c\x01\n" +
	"\x10completeResource\x12;.veidemann.api.browsercontroller.v2.CompleteResourceRequest\x1a9.veidemann.api.browsercontroller.v2.CompleteResourceReply\"\x00B\xb2\x02\n" +
	"&com.veidemann.api.browsercontroller.v2B\x16BrowsercontrollerProtoP\x01ZEgithub.com/NationalLibraryOfNorway/veidemann/api/browsercontroller/v2\xa2\x02\x03VAB\xaa\x02\"Veidemann.Api.Browsercontroller.V2\xca\x02\"Veidemann\\Api\\Browsercontroller\\V2\xe2\x02.Veidemann\\Api\\Browsercontroller\\V2\\GPBMetadata\xea\x02%Veidemann::Api::Browsercontroller::V2b\x06proto3"

var (
	file_browsercontroller_v2_browsercontroller_proto_rawDescOnce sync.Once
	file_browsercontroller_v2_browsercontroller_proto_rawDescData []byte
)

func file_browsercontroller_v2_browsercontroller_proto_rawDescGZIP() []byte {
	file_browsercontroller_v2_browsercontroller_proto_rawDescOnce.Do(func() {
		file_browsercontroller_v2_browsercontroller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_browsercontroller_v2_browsercontroller_proto_rawDesc), len(file_browsercontroller_v2_browsercontroller_proto_rawDesc)))
	})
	return file_browsercontroller_v2_browsercontroller_proto_rawDescData
}

var file_browsercontroller_v2_browsercontroller_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_browsercontroller_v2_browsercontroller_proto_goTypes = []any{
	(*RegisterResourceRequest)(nil), // 0: veidemann.api.browsercontroller.v2.RegisterResourceRequest
	(*ResourceRegistered)(nil),      // 1: veidemann.api.browsercontroller.v2.ResourceRegistered
	(*RegisterResourceReply)(nil),   // 2: veidemann.api.browsercontroller.v2.RegisterResourceReply
	(*CompleteResourceRequest)(nil), // 3: veidemann.api.browsercontroller.v2.CompleteResourceRequest
	(*CompleteResourceReply)(nil),   // 4: veidemann.api.browsercontroller.v2.CompleteResourceReply
	(*v1.ConfigRef)(nil),            // 5: veidemann.api.config.v1.ConfigRef
	(*v11.CrawlLog)(nil),            // 6: veidemann.api.log.v1.CrawlLog
}
var file_browsercontroller_v2_browsercontroller_proto_depIdxs = []int32{
	5, // 0: veidemann.api.browsercontroller.v2.RegisterResourceRequest.collection_ref:type_name -> veidemann.api.config.v1.ConfigRef
	5, // 1: veidemann.api.browsercontroller.v2.ResourceRegistered.collection_ref:type_name -> veidemann.api.config.v1.ConfigRef
	1, // 2: veidemann.api.browsercontroller.v2.RegisterResourceReply.registered:type_name -> veidemann.api.browsercontroller.v2.ResourceRegistered
	6, // 3: veidemann.api.browsercontroller.v2.CompleteResourceRequest.crawl_log:type_name -> veidemann.api.log.v1.CrawlLog
	0, // 4: veidemann.api.browsercontroller.v2.BrowserController.registerResource:input_type -> veidemann.api.browsercontroller.v2.RegisterResourceRequest
	3, // 5: veidemann.api.browsercontroller.v2.BrowserController.completeResource:input_type -> veidemann.api.browsercontroller.v2.CompleteResourceRequest
	2, // 6: veidemann.api.browsercontroller.v2.BrowserController.registerResource:output_type -> veidemann.api.browsercontroller.v2.RegisterResourceReply
	4, // 7: veidemann.api.browsercontroller.v2.BrowserController.completeResource:output_type -> veidemann.api.browsercontroller.v2.CompleteResourceReply
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_browsercontroller_v2_browsercontroller_proto_init() }
func file_browsercontroller_v2_browsercontroller_proto_init() {
	if File_browsercontroller_v2_browsercontroller_proto != nil {
		return
	}
	file_browsercontroller_v2_browsercontroller_proto_msgTypes[2].OneofWrappers = []any{
		(*RegisterResourceReply_Registered)(nil),
		(*RegisterResourceReply_Cancel)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_browsercontroller_v2_browsercontroller_proto_rawDesc), len(file_browsercontroller_v2_browsercontroller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_browsercontroller_v2_browsercontroller_proto_goTypes,
		DependencyIndexes: file_browsercontroller_v2_browsercontroller_proto_depIdxs,
		MessageInfos:      file_browsercontroller_v2_browsercontroller_proto_msgTypes,
	}.Build()
	File_browsercontroller_v2_browsercontroller_proto = out.File
	file_browsercontroller_v2_browsercontroller_proto_goTypes = nil
	file_browsercontroller_v2_browsercontroller_proto_depIdxs = nil
}
