// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: browsercontroller/v2/browsercontroller.proto

package v2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BrowserController_RegisterResource_FullMethodName = "/veidemann.api.browsercontroller.v2.BrowserController/registerResource"
	BrowserController_CompleteResource_FullMethodName = "/veidemann.api.browsercontroller.v2.BrowserController/completeResource"
)

// BrowserControllerClient is the client API for BrowserController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrowserControllerClient interface {
	RegisterResource(ctx context.Context, in *RegisterResourceRequest, opts ...grpc.CallOption) (*RegisterResourceReply, error)
	CompleteResource(ctx context.Context, in *CompleteResourceRequest, opts ...grpc.CallOption) (*CompleteResourceReply, error)
}

type browserControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewBrowserControllerClient(cc grpc.ClientConnInterface) BrowserControllerClient {
	return &browserControllerClient{cc}
}

func (c *browserControllerClient) RegisterResource(ctx context.Context, in *RegisterResourceRequest, opts ...grpc.CallOption) (*RegisterResourceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResourceReply)
	err := c.cc.Invoke(ctx, BrowserController_RegisterResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserControllerClient) CompleteResource(ctx context.Context, in *CompleteResourceRequest, opts ...grpc.CallOption) (*CompleteResourceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteResourceReply)
	err := c.cc.Invoke(ctx, BrowserController_CompleteResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrowserControllerServer is the server API for BrowserController service.
// All implementations should embed UnimplementedBrowserControllerServer
// for forward compatibility.
type BrowserControllerServer interface {
	RegisterResource(context.Context, *RegisterResourceRequest) (*RegisterResourceReply, error)
	CompleteResource(context.Context, *CompleteResourceRequest) (*CompleteResourceReply, error)
}

// UnimplementedBrowserControllerServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrowserControllerServer struct{}

func (UnimplementedBrowserControllerServer) RegisterResource(context.Context, *RegisterResourceRequest) (*RegisterResourceReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterResource not implemented")
}
func (UnimplementedBrowserControllerServer) CompleteResource(context.Context, *CompleteResourceRequest) (*CompleteResourceReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteResource not implemented")
}
func (UnimplementedBrowserControllerServer) testEmbeddedByValue() {}

// UnsafeBrowserControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrowserControllerServer will
// result in compilation errors.
type UnsafeBrowserControllerServer interface {
	mustEmbedUnimplementedBrowserControllerServer()
}

func RegisterBrowserControllerServer(s grpc.ServiceRegistrar, srv BrowserControllerServer) {
	// If the following call panics, it indicates UnimplementedBrowserControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BrowserController_ServiceDesc, srv)
}

func _BrowserController_RegisterResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserControllerServer).RegisterResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserController_RegisterResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserControllerServer).RegisterResource(ctx, req.(*RegisterResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserController_CompleteResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserControllerServer).CompleteResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserController_CompleteResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserControllerServer).CompleteResource(ctx, req.(*CompleteResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BrowserController_ServiceDesc is the grpc.ServiceDesc for BrowserController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrowserController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "veidemann.api.browsercontroller.v2.BrowserController",
	HandlerType: (*BrowserControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "registerResource",
			Handler:    _BrowserController_RegisterResource_Handler,
		},
		{
			MethodName: "completeResource",
			Handler:    _BrowserController_CompleteResource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "browsercontroller/v2/browsercontroller.proto",
}
