apiVersion: v1
kind: ConfigMap
metadata:
  name: dns-resolver
data:
  Corefile: |
    arpa {
        errors
        forward . /etc/resolv.conf
    }

    . {
        errors
        debug
        log
        resolve :8053
        prometheus :9153
        ready :8181
        loop
        reload
        archivingcache {
            eviction 5m
            olricAddress {$OLRIC_ADDRESS}
            olricDmap {$OLRIC_DMAP}
            contentWriterHost {$CONTENT_WRITER_HOST}
            contentWriterPort {$CONTENT_WRITER_PORT}
            logHost {$LOG_WRITER_HOST}
            logPort {$LOG_WRITER_PORT}
        }
        forward . {$DNS_SERVER}
    }