// @generated by protoc-gen-es v2.10.1 with parameter "target=ts,import_extension=none"
// @generated from file commons/v1/resources.proto (package veidemann.api.commons.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file commons/v1/resources.proto.
 */
export const file_commons_v1_resources: GenFile = /*@__PURE__*/
  fileDesc("Chpjb21tb25zL3YxL3Jlc291cmNlcy5wcm90bxIYdmVpZGVtYW5uLmFwaS5jb21tb25zLnYxIjIKBUVycm9yEgwKBGNvZGUYASABKAUSCwoDbXNnGAIgASgJEg4KBmRldGFpbBgDIAEoCSIaCglGaWVsZE1hc2sSDQoFcGF0aHMYASADKAkimAEKCVBhcnNlZFVyaRIMCgRocmVmGAEgASgJEg4KBnNjaGVtZRgCIAEoCRIMCgRob3N0GAMgASgJEgwKBHBvcnQYBCABKAUSEAoIdXNlcm5hbWUYBSABKAkSEAoIcGFzc3dvcmQYBiABKAkSDAoEcGF0aBgHIAEoCRINCgVxdWVyeRgIIAEoCRIQCghmcmFnbWVudBgJIAEoCSKrAQoNRXh0cmFjdGVkVGV4dBIPCgd3YXJjX2lkGAEgASgJEgwKBHRleHQYAiABKAkSFgoOc2VudGVuY2VfY291bnQYAyABKAMSEgoKd29yZF9jb3VudBgEIAEoAxIXCg9sb25nX3dvcmRfY291bnQYBSABKAMSFwoPY2hhcmFjdGVyX2NvdW50GAYgASgDEgsKA2xpeBgHIAEoAxIQCghsYW5ndWFnZRgIIAEoCUJ0CiJuby5uYi5ubmEudmVpZGVtYW5uLmFwaS5jb21tb25zLnYxQg9Db21tb25SZXNvdXJjZXNQAVo7Z2l0aHViLmNvbS9OYXRpb25hbExpYnJhcnlPZk5vcndheS92ZWlkZW1hbm4vYXBpL2NvbW1vbnMvdjFiBnByb3RvMw");

/**
 * @generated from message veidemann.api.commons.v1.Error
 */
export type Error = Message<"veidemann.api.commons.v1.Error"> & {
  /**
   * @generated from field: int32 code = 1;
   */
  code: number;

  /**
   * @generated from field: string msg = 2;
   */
  msg: string;

  /**
   * @generated from field: string detail = 3;
   */
  detail: string;
};

/**
 * Describes the message veidemann.api.commons.v1.Error.
 * Use `create(ErrorSchema)` to create a new message.
 */
export const ErrorSchema: GenMessage<Error> = /*@__PURE__*/
  messageDesc(file_commons_v1_resources, 0);

/**
 * @generated from message veidemann.api.commons.v1.FieldMask
 */
export type FieldMask = Message<"veidemann.api.commons.v1.FieldMask"> & {
  /**
   * @generated from field: repeated string paths = 1;
   */
  paths: string[];
};

/**
 * Describes the message veidemann.api.commons.v1.FieldMask.
 * Use `create(FieldMaskSchema)` to create a new message.
 */
export const FieldMaskSchema: GenMessage<FieldMask> = /*@__PURE__*/
  messageDesc(file_commons_v1_resources, 1);

/**
 * @generated from message veidemann.api.commons.v1.ParsedUri
 */
export type ParsedUri = Message<"veidemann.api.commons.v1.ParsedUri"> & {
  /**
   * The entire uri
   *
   * @generated from field: string href = 1;
   */
  href: string;

  /**
   * The scheme (protocol) part of the uri
   *
   * @generated from field: string scheme = 2;
   */
  scheme: string;

  /**
   * The hostname of the uri
   *
   * @generated from field: string host = 3;
   */
  host: string;

  /**
   * The port number of the uri
   *
   * @generated from field: int32 port = 4;
   */
  port: number;

  /**
   * The username part of the uri
   *
   * @generated from field: string username = 5;
   */
  username: string;

  /**
   * The password part of the uri
   *
   * @generated from field: string password = 6;
   */
  password: string;

  /**
   * The path part of the uri
   *
   * @generated from field: string path = 7;
   */
  path: string;

  /**
   * The query (search) part of the uri
   *
   * @generated from field: string query = 8;
   */
  query: string;

  /**
   * The fragment (hash) part of the uri
   *
   * @generated from field: string fragment = 9;
   */
  fragment: string;
};

/**
 * Describes the message veidemann.api.commons.v1.ParsedUri.
 * Use `create(ParsedUriSchema)` to create a new message.
 */
export const ParsedUriSchema: GenMessage<ParsedUri> = /*@__PURE__*/
  messageDesc(file_commons_v1_resources, 2);

/**
 * @generated from message veidemann.api.commons.v1.ExtractedText
 */
export type ExtractedText = Message<"veidemann.api.commons.v1.ExtractedText"> & {
  /**
   * @generated from field: string warc_id = 1;
   */
  warcId: string;

  /**
   * @generated from field: string text = 2;
   */
  text: string;

  /**
   * @generated from field: int64 sentence_count = 3;
   */
  sentenceCount: bigint;

  /**
   * @generated from field: int64 word_count = 4;
   */
  wordCount: bigint;

  /**
   * @generated from field: int64 long_word_count = 5;
   */
  longWordCount: bigint;

  /**
   * @generated from field: int64 character_count = 6;
   */
  characterCount: bigint;

  /**
   * @generated from field: int64 lix = 7;
   */
  lix: bigint;

  /**
   * @generated from field: string language = 8;
   */
  language: string;
};

/**
 * Describes the message veidemann.api.commons.v1.ExtractedText.
 * Use `create(ExtractedTextSchema)` to create a new message.
 */
export const ExtractedTextSchema: GenMessage<ExtractedText> = /*@__PURE__*/
  messageDesc(file_commons_v1_resources, 3);

