apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/instance: redis
      app.kubernetes.io/name: redis
      app.kubernetes.io/component: metrics