// @generated by protoc-gen-es v2.10.1 with parameter "target=ts,import_extension=none"
// @generated from file log/v1/log.proto (package veidemann.api.log.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { FieldMask } from "../../commons/v1/resources_pb";
import { file_commons_v1_resources } from "../../commons/v1/resources_pb";
import type { CrawlLog, CrawlLogSchema, PageLog, PageLog_Resource, PageLogSchema } from "./resources_pb";
import { file_log_v1_resources } from "./resources_pb";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file log/v1/log.proto.
 */
export const file_log_v1_log: GenFile = /*@__PURE__*/
  fileDesc("ChBsb2cvdjEvbG9nLnByb3RvEhR2ZWlkZW1hbm4uYXBpLmxvZy52MSK9AgoTQ3Jhd2xMb2dMaXN0UmVxdWVzdBIPCgd3YXJjX2lkGAIgAygJEjYKDnF1ZXJ5X3RlbXBsYXRlGAUgASgLMh4udmVpZGVtYW5uLmFwaS5sb2cudjEuQ3Jhd2xMb2cSNwoKcXVlcnlfbWFzaxgGIAEoCzIjLnZlaWRlbWFubi5hcGkuY29tbW9ucy52MS5GaWVsZE1hc2sSQQoUcmV0dXJuZWRfZmllbGRzX21hc2sYByABKAsyIy52ZWlkZW1hbm4uYXBpLmNvbW1vbnMudjEuRmllbGRNYXNrEhUKDW9yZGVyX2J5X3BhdGgYCCABKAkSGAoQb3JkZXJfZGVzY2VuZGluZxgJIAEoCBINCgV3YXRjaBgNIAEoCBIRCglwYWdlX3NpemUYDiABKAUSDgoGb2Zmc2V0GA8gASgFIrsCChJQYWdlTG9nTGlzdFJlcXVlc3QSDwoHd2FyY19pZBgCIAMoCRI1Cg5xdWVyeV90ZW1wbGF0ZRgFIAEoCzIdLnZlaWRlbWFubi5hcGkubG9nLnYxLlBhZ2VMb2cSNwoKcXVlcnlfbWFzaxgGIAEoCzIjLnZlaWRlbWFubi5hcGkuY29tbW9ucy52MS5GaWVsZE1hc2sSQQoUcmV0dXJuZWRfZmllbGRzX21hc2sYByABKAsyIy52ZWlkZW1hbm4uYXBpLmNvbW1vbnMudjEuRmllbGRNYXNrEhUKDW9yZGVyX2J5X3BhdGgYCCABKAkSGAoQb3JkZXJfZGVzY2VuZGluZxgJIAEoCBINCgV3YXRjaBgNIAEoCBIRCglwYWdlX3NpemUYDiABKAUSDgoGb2Zmc2V0GA8gASgFIqEBChNXcml0ZVBhZ2VMb2dSZXF1ZXN0EjIKCGNyYXdsTG9nGAEgASgLMh4udmVpZGVtYW5uLmFwaS5sb2cudjEuQ3Jhd2xMb2dIABI6CghyZXNvdXJjZRgCIAEoCzImLnZlaWRlbWFubi5hcGkubG9nLnYxLlBhZ2VMb2cuUmVzb3VyY2VIABIRCgdvdXRsaW5rGAMgASgJSABCBwoFdmFsdWUiSAoUV3JpdGVDcmF3bExvZ1JlcXVlc3QSMAoIY3Jhd2xMb2cYASABKAsyHi52ZWlkZW1hbm4uYXBpLmxvZy52MS5DcmF3bExvZzLyAgoDTG9nEl4KDUxpc3RDcmF3bExvZ3MSKS52ZWlkZW1hbm4uYXBpLmxvZy52MS5DcmF3bExvZ0xpc3RSZXF1ZXN0Gh4udmVpZGVtYW5uLmFwaS5sb2cudjEuQ3Jhd2xMb2ciADABElsKDExpc3RQYWdlTG9ncxIoLnZlaWRlbWFubi5hcGkubG9nLnYxLlBhZ2VMb2dMaXN0UmVxdWVzdBodLnZlaWRlbWFubi5hcGkubG9nLnYxLlBhZ2VMb2ciADABElcKDVdyaXRlQ3Jhd2xMb2cSKi52ZWlkZW1hbm4uYXBpLmxvZy52MS5Xcml0ZUNyYXdsTG9nUmVxdWVzdBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSIAKAESVQoMV3JpdGVQYWdlTG9nEikudmVpZGVtYW5uLmFwaS5sb2cudjEuV3JpdGVQYWdlTG9nUmVxdWVzdBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSIAKAFCZwoebm8ubmIubm5hLnZlaWRlbWFubi5hcGkubG9nLnYxQgpMb2dTZXJ2aWNlUAFaN2dpdGh1Yi5jb20vTmF0aW9uYWxMaWJyYXJ5T2ZOb3J3YXkvdmVpZGVtYW5uL2FwaS9sb2cvdjFiBnByb3RvMw", [file_commons_v1_resources, file_log_v1_resources, file_google_protobuf_empty]);

/**
 * Specification of which entities to get.
 *
 * @generated from message veidemann.api.log.v1.CrawlLogListRequest
 */
export type CrawlLogListRequest = Message<"veidemann.api.log.v1.CrawlLogListRequest"> & {
  /**
   * Select objects by one or more id's
   *
   * @generated from field: repeated string warc_id = 2;
   */
  warcId: string[];

  /**
   * @generated from field: veidemann.api.log.v1.CrawlLog query_template = 5;
   */
  queryTemplate?: CrawlLog;

  /**
   * @generated from field: veidemann.api.commons.v1.FieldMask query_mask = 6;
   */
  queryMask?: FieldMask;

  /**
   * @generated from field: veidemann.api.commons.v1.FieldMask returned_fields_mask = 7;
   */
  returnedFieldsMask?: FieldMask;

  /**
   * @generated from field: string order_by_path = 8;
   */
  orderByPath: string;

  /**
   * @generated from field: bool order_descending = 9;
   */
  orderDescending: boolean;

  /**
   * @generated from field: bool watch = 13;
   */
  watch: boolean;

  /**
   * @generated from field: int32 page_size = 14;
   */
  pageSize: number;

  /**
   * @generated from field: int32 offset = 15;
   */
  offset: number;
};

/**
 * Describes the message veidemann.api.log.v1.CrawlLogListRequest.
 * Use `create(CrawlLogListRequestSchema)` to create a new message.
 */
export const CrawlLogListRequestSchema: GenMessage<CrawlLogListRequest> = /*@__PURE__*/
  messageDesc(file_log_v1_log, 0);

/**
 * @generated from message veidemann.api.log.v1.PageLogListRequest
 */
export type PageLogListRequest = Message<"veidemann.api.log.v1.PageLogListRequest"> & {
  /**
   * Select objects by one or more id's
   *
   * @generated from field: repeated string warc_id = 2;
   */
  warcId: string[];

  /**
   * @generated from field: veidemann.api.log.v1.PageLog query_template = 5;
   */
  queryTemplate?: PageLog;

  /**
   * @generated from field: veidemann.api.commons.v1.FieldMask query_mask = 6;
   */
  queryMask?: FieldMask;

  /**
   * @generated from field: veidemann.api.commons.v1.FieldMask returned_fields_mask = 7;
   */
  returnedFieldsMask?: FieldMask;

  /**
   * @generated from field: string order_by_path = 8;
   */
  orderByPath: string;

  /**
   * @generated from field: bool order_descending = 9;
   */
  orderDescending: boolean;

  /**
   * @generated from field: bool watch = 13;
   */
  watch: boolean;

  /**
   * @generated from field: int32 page_size = 14;
   */
  pageSize: number;

  /**
   * @generated from field: int32 offset = 15;
   */
  offset: number;
};

/**
 * Describes the message veidemann.api.log.v1.PageLogListRequest.
 * Use `create(PageLogListRequestSchema)` to create a new message.
 */
export const PageLogListRequestSchema: GenMessage<PageLogListRequest> = /*@__PURE__*/
  messageDesc(file_log_v1_log, 1);

/**
 * @generated from message veidemann.api.log.v1.WritePageLogRequest
 */
export type WritePageLogRequest = Message<"veidemann.api.log.v1.WritePageLogRequest"> & {
  /**
   * @generated from oneof veidemann.api.log.v1.WritePageLogRequest.value
   */
  value: {
    /**
     * @generated from field: veidemann.api.log.v1.CrawlLog crawlLog = 1;
     */
    value: CrawlLog;
    case: "crawlLog";
  } | {
    /**
     * @generated from field: veidemann.api.log.v1.PageLog.Resource resource = 2;
     */
    value: PageLog_Resource;
    case: "resource";
  } | {
    /**
     * @generated from field: string outlink = 3;
     */
    value: string;
    case: "outlink";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message veidemann.api.log.v1.WritePageLogRequest.
 * Use `create(WritePageLogRequestSchema)` to create a new message.
 */
export const WritePageLogRequestSchema: GenMessage<WritePageLogRequest> = /*@__PURE__*/
  messageDesc(file_log_v1_log, 2);

/**
 * @generated from message veidemann.api.log.v1.WriteCrawlLogRequest
 */
export type WriteCrawlLogRequest = Message<"veidemann.api.log.v1.WriteCrawlLogRequest"> & {
  /**
   * @generated from field: veidemann.api.log.v1.CrawlLog crawlLog = 1;
   */
  crawlLog?: CrawlLog;
};

/**
 * Describes the message veidemann.api.log.v1.WriteCrawlLogRequest.
 * Use `create(WriteCrawlLogRequestSchema)` to create a new message.
 */
export const WriteCrawlLogRequestSchema: GenMessage<WriteCrawlLogRequest> = /*@__PURE__*/
  messageDesc(file_log_v1_log, 3);

/**
 * Service for crawl/page-log
 *
 * @generated from service veidemann.api.log.v1.Log
 */
export const Log: GenService<{
  /**
   * List crawl logs
   *
   * @generated from rpc veidemann.api.log.v1.Log.ListCrawlLogs
   */
  listCrawlLogs: {
    methodKind: "server_streaming";
    input: typeof CrawlLogListRequestSchema;
    output: typeof CrawlLogSchema;
  },
  /**
   * List page logs
   *
   * @generated from rpc veidemann.api.log.v1.Log.ListPageLogs
   */
  listPageLogs: {
    methodKind: "server_streaming";
    input: typeof PageLogListRequestSchema;
    output: typeof PageLogSchema;
  },
  /**
   * Write crawl logs
   *
   * @generated from rpc veidemann.api.log.v1.Log.WriteCrawlLog
   */
  writeCrawlLog: {
    methodKind: "client_streaming";
    input: typeof WriteCrawlLogRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Write page log
   *
   * @generated from rpc veidemann.api.log.v1.Log.WritePageLog
   */
  writePageLog: {
    methodKind: "client_streaming";
    input: typeof WritePageLogRequestSchema;
    output: typeof EmptySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_log_v1_log, 0);

