// @generated by protoc-gen-es v2.10.1 with parameter "target=ts,import_extension=none"
// @generated from file log/v1/resources.proto (package veidemann.api.log.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Error } from "../../commons/v1/resources_pb";
import { file_commons_v1_resources } from "../../commons/v1/resources_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file log/v1/resources.proto.
 */
export const file_log_v1_resources: GenFile = /*@__PURE__*/
  fileDesc("ChZsb2cvdjEvcmVzb3VyY2VzLnByb3RvEhR2ZWlkZW1hbm4uYXBpLmxvZy52MSLMBAoIQ3Jhd2xMb2cSDwoHd2FyY19pZBgBIAEoCRIuCgp0aW1lX3N0YW1wGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBITCgtzdGF0dXNfY29kZRgEIAEoBRIMCgRzaXplGAUgASgDEhUKDXJlcXVlc3RlZF91cmkYBiABKAkSFAoMcmVzcG9uc2VfdXJpGAcgASgJEhYKDmRpc2NvdmVyeV9wYXRoGAggASgJEhAKCHJlZmVycmVyGAkgASgJEhQKDGNvbnRlbnRfdHlwZRgKIAEoCRI0ChBmZXRjaF90aW1lX3N0YW1wGAsgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIVCg1mZXRjaF90aW1lX21zGAwgASgDEhQKDGJsb2NrX2RpZ2VzdBgNIAEoCRIWCg5wYXlsb2FkX2RpZ2VzdBgOIAEoCRITCgtzdG9yYWdlX3JlZhgPIAEoCRITCgtyZWNvcmRfdHlwZRgQIAEoCRIWCg53YXJjX3JlZmVyc190bxgRIAEoCRISCgppcF9hZGRyZXNzGBIgASgJEhQKDGV4ZWN1dGlvbl9pZBgTIAEoCRIPCgdyZXRyaWVzGBQgASgFEi4KBWVycm9yGBUgASgLMh8udmVpZGVtYW5uLmFwaS5jb21tb25zLnYxLkVycm9yEhgKEGpvYl9leGVjdXRpb25faWQYFiABKAkSHQoVY29sbGVjdGlvbl9maW5hbF9uYW1lGBcgASgJEg4KBm1ldGhvZBgYIAEoCSLiAwoHUGFnZUxvZxIPCgd3YXJjX2lkGAEgASgJEgsKA3VyaRgCIAEoCRIUCgxleGVjdXRpb25faWQYAyABKAkSEAoIcmVmZXJyZXIYBCABKAkSGAoQam9iX2V4ZWN1dGlvbl9pZBgFIAEoCRIdChVjb2xsZWN0aW9uX2ZpbmFsX25hbWUYBiABKAkSDgoGbWV0aG9kGAcgASgJEjgKCHJlc291cmNlGAogAygLMiYudmVpZGVtYW5uLmFwaS5sb2cudjEuUGFnZUxvZy5SZXNvdXJjZRIPCgdvdXRsaW5rGAsgAygJGvwBCghSZXNvdXJjZRILCgN1cmkYASABKAkSEgoKZnJvbV9jYWNoZRgCIAEoCBISCgpyZW5kZXJhYmxlGAMgASgIEhUKDXJlc291cmNlX3R5cGUYBCABKAkSFAoMY29udGVudF90eXBlGAUgASgJEhMKC3N0YXR1c19jb2RlGAYgASgFEhYKDmRpc2NvdmVyeV9wYXRoGAcgASgJEg8KB3dhcmNfaWQYCCABKAkSEAoIcmVmZXJyZXIYCSABKAkSLgoFZXJyb3IYCiABKAsyHy52ZWlkZW1hbm4uYXBpLmNvbW1vbnMudjEuRXJyb3ISDgoGbWV0aG9kGAsgASgJQmkKHm5vLm5iLm5uYS52ZWlkZW1hbm4uYXBpLmxvZy52MUIMTG9nUmVzb3VyY2VzUAFaN2dpdGh1Yi5jb20vTmF0aW9uYWxMaWJyYXJ5T2ZOb3J3YXkvdmVpZGVtYW5uL2FwaS9sb2cvdjFiBnByb3RvMw", [file_commons_v1_resources, file_google_protobuf_timestamp]);

/**
 * @generated from message veidemann.api.log.v1.CrawlLog
 */
export type CrawlLog = Message<"veidemann.api.log.v1.CrawlLog"> & {
  /**
   * @generated from field: string warc_id = 1;
   */
  warcId: string;

  /**
   * @generated from field: google.protobuf.Timestamp time_stamp = 2;
   */
  timeStamp?: Timestamp;

  /**
   * @generated from field: int32 status_code = 4;
   */
  statusCode: number;

  /**
   * @generated from field: int64 size = 5;
   */
  size: bigint;

  /**
   * @generated from field: string requested_uri = 6;
   */
  requestedUri: string;

  /**
   * @generated from field: string response_uri = 7;
   */
  responseUri: string;

  /**
   * *
   * Get the discoveryPath,
   *  R - Redirect
   *  E - Embed
   *  X - Speculative embed (aggressive/Javascript link extraction)
   *  L - Link
   *  P - Prerequisite (as for DNS or robots.txt before another URI)
   *
   * @generated from field: string discovery_path = 8;
   */
  discoveryPath: string;

  /**
   * @generated from field: string referrer = 9;
   */
  referrer: string;

  /**
   * @generated from field: string content_type = 10;
   */
  contentType: string;

  /**
   * @generated from field: google.protobuf.Timestamp fetch_time_stamp = 11;
   */
  fetchTimeStamp?: Timestamp;

  /**
   * @generated from field: int64 fetch_time_ms = 12;
   */
  fetchTimeMs: bigint;

  /**
   * @generated from field: string block_digest = 13;
   */
  blockDigest: string;

  /**
   * @generated from field: string payload_digest = 14;
   */
  payloadDigest: string;

  /**
   * @generated from field: string storage_ref = 15;
   */
  storageRef: string;

  /**
   * @generated from field: string record_type = 16;
   */
  recordType: string;

  /**
   * @generated from field: string warc_refers_to = 17;
   */
  warcRefersTo: string;

  /**
   * @generated from field: string ip_address = 18;
   */
  ipAddress: string;

  /**
   * @generated from field: string execution_id = 19;
   */
  executionId: string;

  /**
   * Number of times this uri has been retried. Zero means success on first attempt.
   *
   * @generated from field: int32 retries = 20;
   */
  retries: number;

  /**
   * Contains the error reason if fetch failed
   *
   * @generated from field: veidemann.api.commons.v1.Error error = 21;
   */
  error?: Error;

  /**
   * @generated from field: string job_execution_id = 22;
   */
  jobExecutionId: string;

  /**
   * @generated from field: string collection_final_name = 23;
   */
  collectionFinalName: string;

  /**
   * The HTTP method (GET, POST, HEAD, ...)
   *
   * @generated from field: string method = 24;
   */
  method: string;
};

/**
 * Describes the message veidemann.api.log.v1.CrawlLog.
 * Use `create(CrawlLogSchema)` to create a new message.
 */
export const CrawlLogSchema: GenMessage<CrawlLog> = /*@__PURE__*/
  messageDesc(file_log_v1_resources, 0);

/**
 * Log for each page including discovered resources and links
 *
 * @generated from message veidemann.api.log.v1.PageLog
 */
export type PageLog = Message<"veidemann.api.log.v1.PageLog"> & {
  /**
   * @generated from field: string warc_id = 1;
   */
  warcId: string;

  /**
   * @generated from field: string uri = 2;
   */
  uri: string;

  /**
   * @generated from field: string execution_id = 3;
   */
  executionId: string;

  /**
   * @generated from field: string referrer = 4;
   */
  referrer: string;

  /**
   * @generated from field: string job_execution_id = 5;
   */
  jobExecutionId: string;

  /**
   * @generated from field: string collection_final_name = 6;
   */
  collectionFinalName: string;

  /**
   * The HTTP method (GET, POST, HEAD, ...)
   *
   * @generated from field: string method = 7;
   */
  method: string;

  /**
   * @generated from field: repeated veidemann.api.log.v1.PageLog.Resource resource = 10;
   */
  resource: PageLog_Resource[];

  /**
   * @generated from field: repeated string outlink = 11;
   */
  outlink: string[];
};

/**
 * Describes the message veidemann.api.log.v1.PageLog.
 * Use `create(PageLogSchema)` to create a new message.
 */
export const PageLogSchema: GenMessage<PageLog> = /*@__PURE__*/
  messageDesc(file_log_v1_resources, 1);

/**
 * A resource used to complete a page. It might be embedded images, javascripts, stylesheets etc.
 *
 * @generated from message veidemann.api.log.v1.PageLog.Resource
 */
export type PageLog_Resource = Message<"veidemann.api.log.v1.PageLog.Resource"> & {
  /**
   * @generated from field: string uri = 1;
   */
  uri: string;

  /**
   * @generated from field: bool from_cache = 2;
   */
  fromCache: boolean;

  /**
   * @generated from field: bool renderable = 3;
   */
  renderable: boolean;

  /**
   * @generated from field: string resource_type = 4;
   */
  resourceType: string;

  /**
   * @generated from field: string content_type = 5;
   */
  contentType: string;

  /**
   * @generated from field: int32 status_code = 6;
   */
  statusCode: number;

  /**
   * @generated from field: string discovery_path = 7;
   */
  discoveryPath: string;

  /**
   * @generated from field: string warc_id = 8;
   */
  warcId: string;

  /**
   * @generated from field: string referrer = 9;
   */
  referrer: string;

  /**
   * Contains the error reason if fetch failed
   *
   * @generated from field: veidemann.api.commons.v1.Error error = 10;
   */
  error?: Error;

  /**
   * The HTTP method (GET, POST, HEAD, ...)
   *
   * @generated from field: string method = 11;
   */
  method: string;
};

/**
 * Describes the message veidemann.api.log.v1.PageLog.Resource.
 * Use `create(PageLog_ResourceSchema)` to create a new message.
 */
export const PageLog_ResourceSchema: GenMessage<PageLog_Resource> = /*@__PURE__*/
  messageDesc(file_log_v1_resources, 1, 0);

