// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: frontier/v1/frontier.proto

package v1

import (
	v11 "github.com/NationalLibraryOfNorway/veidemann/api/commons/v1"
	v1 "github.com/NationalLibraryOfNorway/veidemann/api/config/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CrawlSeedRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobExecutionId string                 `protobuf:"bytes,1,opt,name=job_execution_id,json=jobExecutionId,proto3" json:"job_execution_id,omitempty"`
	Job            *v1.ConfigObject       `protobuf:"bytes,5,opt,name=job,proto3" json:"job,omitempty"`
	Seed           *v1.ConfigObject       `protobuf:"bytes,6,opt,name=seed,proto3" json:"seed,omitempty"`
	// When this seed should stop crawling. Absence of this value indicates no timeout
	Timeout       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawlSeedRequest) Reset() {
	*x = CrawlSeedRequest{}
	mi := &file_frontier_v1_frontier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlSeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlSeedRequest) ProtoMessage() {}

func (x *CrawlSeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontier_v1_frontier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlSeedRequest.ProtoReflect.Descriptor instead.
func (*CrawlSeedRequest) Descriptor() ([]byte, []int) {
	return file_frontier_v1_frontier_proto_rawDescGZIP(), []int{0}
}

func (x *CrawlSeedRequest) GetJobExecutionId() string {
	if x != nil {
		return x.JobExecutionId
	}
	return ""
}

func (x *CrawlSeedRequest) GetJob() *v1.ConfigObject {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *CrawlSeedRequest) GetSeed() *v1.ConfigObject {
	if x != nil {
		return x.Seed
	}
	return nil
}

func (x *CrawlSeedRequest) GetTimeout() *timestamppb.Timestamp {
	if x != nil {
		return x.Timeout
	}
	return nil
}

// The execution id for a seed crawl
type CrawlExecutionId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawlExecutionId) Reset() {
	*x = CrawlExecutionId{}
	mi := &file_frontier_v1_frontier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlExecutionId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlExecutionId) ProtoMessage() {}

func (x *CrawlExecutionId) ProtoReflect() protoreflect.Message {
	mi := &file_frontier_v1_frontier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlExecutionId.ProtoReflect.Descriptor instead.
func (*CrawlExecutionId) Descriptor() ([]byte, []int) {
	return file_frontier_v1_frontier_proto_rawDescGZIP(), []int{1}
}

func (x *CrawlExecutionId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Message sent from Harvester to return the harvest result.
// When the fetch is done, a stream of PageHarvest objects are returned:
// The first object contains metrics.
// Subsequent objects contain outlinks until all outlinks are sent.
// Finally the client should complete the request.
type PageHarvest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*PageHarvest_Metrics_
	//	*PageHarvest_Outlink
	//	*PageHarvest_Error
	Msg isPageHarvest_Msg `protobuf_oneof:"msg"`
	// Session token from the PageHarvestSpec.
	SessionToken  string `protobuf:"bytes,5,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageHarvest) Reset() {
	*x = PageHarvest{}
	mi := &file_frontier_v1_frontier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageHarvest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageHarvest) ProtoMessage() {}

func (x *PageHarvest) ProtoReflect() protoreflect.Message {
	mi := &file_frontier_v1_frontier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageHarvest.ProtoReflect.Descriptor instead.
func (*PageHarvest) Descriptor() ([]byte, []int) {
	return file_frontier_v1_frontier_proto_rawDescGZIP(), []int{2}
}

func (x *PageHarvest) GetMsg() isPageHarvest_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *PageHarvest) GetMetrics() *PageHarvest_Metrics {
	if x != nil {
		if x, ok := x.Msg.(*PageHarvest_Metrics_); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *PageHarvest) GetOutlink() *QueuedUri {
	if x != nil {
		if x, ok := x.Msg.(*PageHarvest_Outlink); ok {
			return x.Outlink
		}
	}
	return nil
}

func (x *PageHarvest) GetError() *v11.Error {
	if x != nil {
		if x, ok := x.Msg.(*PageHarvest_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *PageHarvest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type isPageHarvest_Msg interface {
	isPageHarvest_Msg()
}

type PageHarvest_Metrics_ struct {
	// Collected metrics for the page fetched
	Metrics *PageHarvest_Metrics `protobuf:"bytes,2,opt,name=metrics,proto3,oneof"`
}

type PageHarvest_Outlink struct {
	// The outlinks found in the harvested page
	Outlink *QueuedUri `protobuf:"bytes,3,opt,name=outlink,proto3,oneof"`
}

type PageHarvest_Error struct {
	// If the overall page fetch failed. Should not be used for a singel uri failure
	Error *v11.Error `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*PageHarvest_Metrics_) isPageHarvest_Msg() {}

func (*PageHarvest_Outlink) isPageHarvest_Msg() {}

func (*PageHarvest_Error) isPageHarvest_Msg() {}

// A specification of the page to fetch.
type PageHarvestSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The URI to fetch
	QueuedUri *QueuedUri `protobuf:"bytes,1,opt,name=queued_uri,json=queuedUri,proto3" json:"queued_uri,omitempty"`
	// The configuration for the fetch
	CrawlConfig *v1.ConfigObject `protobuf:"bytes,2,opt,name=crawl_config,json=crawlConfig,proto3" json:"crawl_config,omitempty"`
	// Session token for this request.
	// The Harvester is responsible for setting the same session token in all responses to this request.
	SessionToken  string `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageHarvestSpec) Reset() {
	*x = PageHarvestSpec{}
	mi := &file_frontier_v1_frontier_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageHarvestSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageHarvestSpec) ProtoMessage() {}

func (x *PageHarvestSpec) ProtoReflect() protoreflect.Message {
	mi := &file_frontier_v1_frontier_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageHarvestSpec.ProtoReflect.Descriptor instead.
func (*PageHarvestSpec) Descriptor() ([]byte, []int) {
	return file_frontier_v1_frontier_proto_rawDescGZIP(), []int{3}
}

func (x *PageHarvestSpec) GetQueuedUri() *QueuedUri {
	if x != nil {
		return x.QueuedUri
	}
	return nil
}

func (x *PageHarvestSpec) GetCrawlConfig() *v1.ConfigObject {
	if x != nil {
		return x.CrawlConfig
	}
	return nil
}

func (x *PageHarvestSpec) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type CountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountResponse) Reset() {
	*x = CountResponse{}
	mi := &file_frontier_v1_frontier_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountResponse) ProtoMessage() {}

func (x *CountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontier_v1_frontier_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountResponse.ProtoReflect.Descriptor instead.
func (*CountResponse) Descriptor() ([]byte, []int) {
	return file_frontier_v1_frontier_proto_rawDescGZIP(), []int{4}
}

func (x *CountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type PageHarvest_Metrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The number of uri's downloaded. The requested uri + embedded resources
	UriCount int32 `protobuf:"varint,1,opt,name=uri_count,json=uriCount,proto3" json:"uri_count,omitempty"`
	// Byte count for the resources downloaded. Includes embedded resources
	BytesDownloaded int64 `protobuf:"varint,2,opt,name=bytes_downloaded,json=bytesDownloaded,proto3" json:"bytes_downloaded,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PageHarvest_Metrics) Reset() {
	*x = PageHarvest_Metrics{}
	mi := &file_frontier_v1_frontier_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageHarvest_Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageHarvest_Metrics) ProtoMessage() {}

func (x *PageHarvest_Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_frontier_v1_frontier_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageHarvest_Metrics.ProtoReflect.Descriptor instead.
func (*PageHarvest_Metrics) Descriptor() ([]byte, []int) {
	return file_frontier_v1_frontier_proto_rawDescGZIP(), []int{2, 0}
}

func (x *PageHarvest_Metrics) GetUriCount() int32 {
	if x != nil {
		return x.UriCount
	}
	return 0
}

func (x *PageHarvest_Metrics) GetBytesDownloaded() int64 {
	if x != nil {
		return x.BytesDownloaded
	}
	return 0
}

var File_frontier_v1_frontier_proto protoreflect.FileDescriptor

const file_frontier_v1_frontier_proto_rawDesc = "" +
	"\n" +
	"\x1afrontier/v1/frontier.proto\x12\x19veidemann.api.frontier.v1\x1a\x1acommons/v1/resources.proto\x1a\x19config/v1/resources.proto\x1a\x1bfrontier/v1/resources.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe6\x01\n" +
	"\x10CrawlSeedRequest\x12(\n" +
	"\x10job_execution_id\x18\x01 \x01(\tR\x0ejobExecutionId\x127\n" +
	"\x03job\x18\x05 \x01(\v2%.veidemann.api.config.v1.ConfigObjectR\x03job\x129\n" +
	"\x04seed\x18\x06 \x01(\v2%.veidemann.api.config.v1.ConfigObjectR\x04seed\x124\n" +
	"\atimeout\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\atimeout\"\"\n" +
	"\x10CrawlExecutionId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xd3\x02\n" +
	"\vPageHarvest\x12J\n" +
	"\ametrics\x18\x02 \x01(\v2..veidemann.api.frontier.v1.PageHarvest.MetricsH\x00R\ametrics\x12@\n" +
	"\aoutlink\x18\x03 \x01(\v2$.veidemann.api.frontier.v1.QueuedUriH\x00R\aoutlink\x127\n" +
	"\x05error\x18\x04 \x01(\v2\x1f.veidemann.api.commons.v1.ErrorH\x00R\x05error\x12#\n" +
	"\rsession_token\x18\x05 \x01(\tR\fsessionToken\x1aQ\n" +
	"\aMetrics\x12\x1b\n" +
	"\turi_count\x18\x01 \x01(\x05R\buriCount\x12)\n" +
	"\x10bytes_downloaded\x18\x02 \x01(\x03R\x0fbytesDownloadedB\x05\n" +
	"\x03msg\"\xc5\x01\n" +
	"\x0fPageHarvestSpec\x12C\n" +
	"\n" +
	"queued_uri\x18\x01 \x01(\v2$.veidemann.api.frontier.v1.QueuedUriR\tqueuedUri\x12H\n" +
	"\fcrawl_config\x18\x02 \x01(\v2%.veidemann.api.config.v1.ConfigObjectR\vcrawlConfig\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\"%\n" +
	"\rCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count2\xc1\x05\n" +
	"\bFrontier\x12g\n" +
	"\tCrawlSeed\x12+.veidemann.api.frontier.v1.CrawlSeedRequest\x1a+.veidemann.api.frontier.v1.CrawlExecutionId\"\x00\x12S\n" +
	"\vGetNextPage\x12\x16.google.protobuf.Empty\x1a*.veidemann.api.frontier.v1.PageHarvestSpec\"\x00\x12S\n" +
	"\rPageCompleted\x12&.veidemann.api.frontier.v1.PageHarvest\x1a\x16.google.protobuf.Empty\"\x00(\x01\x12]\n" +
	"\x17BusyCrawlHostGroupCount\x12\x16.google.protobuf.Empty\x1a(.veidemann.api.frontier.v1.CountResponse\"\x00\x12U\n" +
	"\x0fQueueCountTotal\x12\x16.google.protobuf.Empty\x1a(.veidemann.api.frontier.v1.CountResponse\"\x00\x12v\n" +
	"\x1bQueueCountForCrawlExecution\x12+.veidemann.api.frontier.v1.CrawlExecutionId\x1a(.veidemann.api.frontier.v1.CountResponse\"\x00\x12t\n" +
	"\x1bQueueCountForCrawlHostGroup\x12).veidemann.api.frontier.v1.CrawlHostGroup\x1a(.veidemann.api.frontier.v1.CountResponse\"\x00B\xf3\x01\n" +
	"\x1dcom.veidemann.api.frontier.v1B\rFrontierProtoP\x01Z<github.com/NationalLibraryOfNorway/veidemann/api/frontier/v1\xa2\x02\x03VAF\xaa\x02\x19Veidemann.Api.Frontier.V1\xca\x02\x19Veidemann\\Api\\Frontier\\V1\xe2\x02%Veidemann\\Api\\Frontier\\V1\\GPBMetadata\xea\x02\x1cVeidemann::Api::Frontier::V1b\x06proto3"

var (
	file_frontier_v1_frontier_proto_rawDescOnce sync.Once
	file_frontier_v1_frontier_proto_rawDescData []byte
)

func file_frontier_v1_frontier_proto_rawDescGZIP() []byte {
	file_frontier_v1_frontier_proto_rawDescOnce.Do(func() {
		file_frontier_v1_frontier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_frontier_v1_frontier_proto_rawDesc), len(file_frontier_v1_frontier_proto_rawDesc)))
	})
	return file_frontier_v1_frontier_proto_rawDescData
}

var file_frontier_v1_frontier_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_frontier_v1_frontier_proto_goTypes = []any{
	(*CrawlSeedRequest)(nil),      // 0: veidemann.api.frontier.v1.CrawlSeedRequest
	(*CrawlExecutionId)(nil),      // 1: veidemann.api.frontier.v1.CrawlExecutionId
	(*PageHarvest)(nil),           // 2: veidemann.api.frontier.v1.PageHarvest
	(*PageHarvestSpec)(nil),       // 3: veidemann.api.frontier.v1.PageHarvestSpec
	(*CountResponse)(nil),         // 4: veidemann.api.frontier.v1.CountResponse
	(*PageHarvest_Metrics)(nil),   // 5: veidemann.api.frontier.v1.PageHarvest.Metrics
	(*v1.ConfigObject)(nil),       // 6: veidemann.api.config.v1.ConfigObject
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*QueuedUri)(nil),             // 8: veidemann.api.frontier.v1.QueuedUri
	(*v11.Error)(nil),             // 9: veidemann.api.commons.v1.Error
	(*emptypb.Empty)(nil),         // 10: google.protobuf.Empty
	(*CrawlHostGroup)(nil),        // 11: veidemann.api.frontier.v1.CrawlHostGroup
}
var file_frontier_v1_frontier_proto_depIdxs = []int32{
	6,  // 0: veidemann.api.frontier.v1.CrawlSeedRequest.job:type_name -> veidemann.api.config.v1.ConfigObject
	6,  // 1: veidemann.api.frontier.v1.CrawlSeedRequest.seed:type_name -> veidemann.api.config.v1.ConfigObject
	7,  // 2: veidemann.api.frontier.v1.CrawlSeedRequest.timeout:type_name -> google.protobuf.Timestamp
	5,  // 3: veidemann.api.frontier.v1.PageHarvest.metrics:type_name -> veidemann.api.frontier.v1.PageHarvest.Metrics
	8,  // 4: veidemann.api.frontier.v1.PageHarvest.outlink:type_name -> veidemann.api.frontier.v1.QueuedUri
	9,  // 5: veidemann.api.frontier.v1.PageHarvest.error:type_name -> veidemann.api.commons.v1.Error
	8,  // 6: veidemann.api.frontier.v1.PageHarvestSpec.queued_uri:type_name -> veidemann.api.frontier.v1.QueuedUri
	6,  // 7: veidemann.api.frontier.v1.PageHarvestSpec.crawl_config:type_name -> veidemann.api.config.v1.ConfigObject
	0,  // 8: veidemann.api.frontier.v1.Frontier.CrawlSeed:input_type -> veidemann.api.frontier.v1.CrawlSeedRequest
	10, // 9: veidemann.api.frontier.v1.Frontier.GetNextPage:input_type -> google.protobuf.Empty
	2,  // 10: veidemann.api.frontier.v1.Frontier.PageCompleted:input_type -> veidemann.api.frontier.v1.PageHarvest
	10, // 11: veidemann.api.frontier.v1.Frontier.BusyCrawlHostGroupCount:input_type -> google.protobuf.Empty
	10, // 12: veidemann.api.frontier.v1.Frontier.QueueCountTotal:input_type -> google.protobuf.Empty
	1,  // 13: veidemann.api.frontier.v1.Frontier.QueueCountForCrawlExecution:input_type -> veidemann.api.frontier.v1.CrawlExecutionId
	11, // 14: veidemann.api.frontier.v1.Frontier.QueueCountForCrawlHostGroup:input_type -> veidemann.api.frontier.v1.CrawlHostGroup
	1,  // 15: veidemann.api.frontier.v1.Frontier.CrawlSeed:output_type -> veidemann.api.frontier.v1.CrawlExecutionId
	3,  // 16: veidemann.api.frontier.v1.Frontier.GetNextPage:output_type -> veidemann.api.frontier.v1.PageHarvestSpec
	10, // 17: veidemann.api.frontier.v1.Frontier.PageCompleted:output_type -> google.protobuf.Empty
	4,  // 18: veidemann.api.frontier.v1.Frontier.BusyCrawlHostGroupCount:output_type -> veidemann.api.frontier.v1.CountResponse
	4,  // 19: veidemann.api.frontier.v1.Frontier.QueueCountTotal:output_type -> veidemann.api.frontier.v1.CountResponse
	4,  // 20: veidemann.api.frontier.v1.Frontier.QueueCountForCrawlExecution:output_type -> veidemann.api.frontier.v1.CountResponse
	4,  // 21: veidemann.api.frontier.v1.Frontier.QueueCountForCrawlHostGroup:output_type -> veidemann.api.frontier.v1.CountResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_frontier_v1_frontier_proto_init() }
func file_frontier_v1_frontier_proto_init() {
	if File_frontier_v1_frontier_proto != nil {
		return
	}
	file_frontier_v1_resources_proto_init()
	file_frontier_v1_frontier_proto_msgTypes[2].OneofWrappers = []any{
		(*PageHarvest_Metrics_)(nil),
		(*PageHarvest_Outlink)(nil),
		(*PageHarvest_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_frontier_v1_frontier_proto_rawDesc), len(file_frontier_v1_frontier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_frontier_v1_frontier_proto_goTypes,
		DependencyIndexes: file_frontier_v1_frontier_proto_depIdxs,
		MessageInfos:      file_frontier_v1_frontier_proto_msgTypes,
	}.Build()
	File_frontier_v1_frontier_proto = out.File
	file_frontier_v1_frontier_proto_goTypes = nil
	file_frontier_v1_frontier_proto_depIdxs = nil
}
