// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: log/v1/log.proto

package v1

import (
	v1 "github.com/NationalLibraryOfNorway/veidemann/api/commons/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Specification of which entities to get.
type CrawlLogListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Select objects by one or more id's
	WarcId             []string      `protobuf:"bytes,2,rep,name=warc_id,json=warcId,proto3" json:"warc_id,omitempty"`
	QueryTemplate      *CrawlLog     `protobuf:"bytes,5,opt,name=query_template,json=queryTemplate,proto3" json:"query_template,omitempty"`
	QueryMask          *v1.FieldMask `protobuf:"bytes,6,opt,name=query_mask,json=queryMask,proto3" json:"query_mask,omitempty"`
	ReturnedFieldsMask *v1.FieldMask `protobuf:"bytes,7,opt,name=returned_fields_mask,json=returnedFieldsMask,proto3" json:"returned_fields_mask,omitempty"`
	OrderByPath        string        `protobuf:"bytes,8,opt,name=order_by_path,json=orderByPath,proto3" json:"order_by_path,omitempty"`
	OrderDescending    bool          `protobuf:"varint,9,opt,name=order_descending,json=orderDescending,proto3" json:"order_descending,omitempty"`
	Watch              bool          `protobuf:"varint,13,opt,name=watch,proto3" json:"watch,omitempty"`
	PageSize           int32         `protobuf:"varint,14,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Offset             int32         `protobuf:"varint,15,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CrawlLogListRequest) Reset() {
	*x = CrawlLogListRequest{}
	mi := &file_log_v1_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlLogListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlLogListRequest) ProtoMessage() {}

func (x *CrawlLogListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_v1_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlLogListRequest.ProtoReflect.Descriptor instead.
func (*CrawlLogListRequest) Descriptor() ([]byte, []int) {
	return file_log_v1_log_proto_rawDescGZIP(), []int{0}
}

func (x *CrawlLogListRequest) GetWarcId() []string {
	if x != nil {
		return x.WarcId
	}
	return nil
}

func (x *CrawlLogListRequest) GetQueryTemplate() *CrawlLog {
	if x != nil {
		return x.QueryTemplate
	}
	return nil
}

func (x *CrawlLogListRequest) GetQueryMask() *v1.FieldMask {
	if x != nil {
		return x.QueryMask
	}
	return nil
}

func (x *CrawlLogListRequest) GetReturnedFieldsMask() *v1.FieldMask {
	if x != nil {
		return x.ReturnedFieldsMask
	}
	return nil
}

func (x *CrawlLogListRequest) GetOrderByPath() string {
	if x != nil {
		return x.OrderByPath
	}
	return ""
}

func (x *CrawlLogListRequest) GetOrderDescending() bool {
	if x != nil {
		return x.OrderDescending
	}
	return false
}

func (x *CrawlLogListRequest) GetWatch() bool {
	if x != nil {
		return x.Watch
	}
	return false
}

func (x *CrawlLogListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *CrawlLogListRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type PageLogListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Select objects by one or more id's
	WarcId             []string      `protobuf:"bytes,2,rep,name=warc_id,json=warcId,proto3" json:"warc_id,omitempty"`
	QueryTemplate      *PageLog      `protobuf:"bytes,5,opt,name=query_template,json=queryTemplate,proto3" json:"query_template,omitempty"`
	QueryMask          *v1.FieldMask `protobuf:"bytes,6,opt,name=query_mask,json=queryMask,proto3" json:"query_mask,omitempty"`
	ReturnedFieldsMask *v1.FieldMask `protobuf:"bytes,7,opt,name=returned_fields_mask,json=returnedFieldsMask,proto3" json:"returned_fields_mask,omitempty"`
	OrderByPath        string        `protobuf:"bytes,8,opt,name=order_by_path,json=orderByPath,proto3" json:"order_by_path,omitempty"`
	OrderDescending    bool          `protobuf:"varint,9,opt,name=order_descending,json=orderDescending,proto3" json:"order_descending,omitempty"`
	Watch              bool          `protobuf:"varint,13,opt,name=watch,proto3" json:"watch,omitempty"`
	PageSize           int32         `protobuf:"varint,14,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Offset             int32         `protobuf:"varint,15,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PageLogListRequest) Reset() {
	*x = PageLogListRequest{}
	mi := &file_log_v1_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageLogListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageLogListRequest) ProtoMessage() {}

func (x *PageLogListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_v1_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageLogListRequest.ProtoReflect.Descriptor instead.
func (*PageLogListRequest) Descriptor() ([]byte, []int) {
	return file_log_v1_log_proto_rawDescGZIP(), []int{1}
}

func (x *PageLogListRequest) GetWarcId() []string {
	if x != nil {
		return x.WarcId
	}
	return nil
}

func (x *PageLogListRequest) GetQueryTemplate() *PageLog {
	if x != nil {
		return x.QueryTemplate
	}
	return nil
}

func (x *PageLogListRequest) GetQueryMask() *v1.FieldMask {
	if x != nil {
		return x.QueryMask
	}
	return nil
}

func (x *PageLogListRequest) GetReturnedFieldsMask() *v1.FieldMask {
	if x != nil {
		return x.ReturnedFieldsMask
	}
	return nil
}

func (x *PageLogListRequest) GetOrderByPath() string {
	if x != nil {
		return x.OrderByPath
	}
	return ""
}

func (x *PageLogListRequest) GetOrderDescending() bool {
	if x != nil {
		return x.OrderDescending
	}
	return false
}

func (x *PageLogListRequest) GetWatch() bool {
	if x != nil {
		return x.Watch
	}
	return false
}

func (x *PageLogListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageLogListRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type WritePageLogRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*WritePageLogRequest_CrawlLog
	//	*WritePageLogRequest_Resource
	//	*WritePageLogRequest_Outlink
	Value         isWritePageLogRequest_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WritePageLogRequest) Reset() {
	*x = WritePageLogRequest{}
	mi := &file_log_v1_log_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WritePageLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WritePageLogRequest) ProtoMessage() {}

func (x *WritePageLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_v1_log_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WritePageLogRequest.ProtoReflect.Descriptor instead.
func (*WritePageLogRequest) Descriptor() ([]byte, []int) {
	return file_log_v1_log_proto_rawDescGZIP(), []int{2}
}

func (x *WritePageLogRequest) GetValue() isWritePageLogRequest_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *WritePageLogRequest) GetCrawlLog() *CrawlLog {
	if x != nil {
		if x, ok := x.Value.(*WritePageLogRequest_CrawlLog); ok {
			return x.CrawlLog
		}
	}
	return nil
}

func (x *WritePageLogRequest) GetResource() *PageLog_Resource {
	if x != nil {
		if x, ok := x.Value.(*WritePageLogRequest_Resource); ok {
			return x.Resource
		}
	}
	return nil
}

func (x *WritePageLogRequest) GetOutlink() string {
	if x != nil {
		if x, ok := x.Value.(*WritePageLogRequest_Outlink); ok {
			return x.Outlink
		}
	}
	return ""
}

type isWritePageLogRequest_Value interface {
	isWritePageLogRequest_Value()
}

type WritePageLogRequest_CrawlLog struct {
	CrawlLog *CrawlLog `protobuf:"bytes,1,opt,name=crawlLog,proto3,oneof"`
}

type WritePageLogRequest_Resource struct {
	Resource *PageLog_Resource `protobuf:"bytes,2,opt,name=resource,proto3,oneof"`
}

type WritePageLogRequest_Outlink struct {
	Outlink string `protobuf:"bytes,3,opt,name=outlink,proto3,oneof"`
}

func (*WritePageLogRequest_CrawlLog) isWritePageLogRequest_Value() {}

func (*WritePageLogRequest_Resource) isWritePageLogRequest_Value() {}

func (*WritePageLogRequest_Outlink) isWritePageLogRequest_Value() {}

type WriteCrawlLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CrawlLog      *CrawlLog              `protobuf:"bytes,1,opt,name=crawlLog,proto3" json:"crawlLog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteCrawlLogRequest) Reset() {
	*x = WriteCrawlLogRequest{}
	mi := &file_log_v1_log_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteCrawlLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteCrawlLogRequest) ProtoMessage() {}

func (x *WriteCrawlLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_v1_log_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteCrawlLogRequest.ProtoReflect.Descriptor instead.
func (*WriteCrawlLogRequest) Descriptor() ([]byte, []int) {
	return file_log_v1_log_proto_rawDescGZIP(), []int{3}
}

func (x *WriteCrawlLogRequest) GetCrawlLog() *CrawlLog {
	if x != nil {
		return x.CrawlLog
	}
	return nil
}

var File_log_v1_log_proto protoreflect.FileDescriptor

const file_log_v1_log_proto_rawDesc = "" +
	"\n" +
	"\x10log/v1/log.proto\x12\x14veidemann.api.log.v1\x1a\x1acommons/v1/resources.proto\x1a\x16log/v1/resources.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xaa\x03\n" +
	"\x13CrawlLogListRequest\x12\x17\n" +
	"\awarc_id\x18\x02 \x03(\tR\x06warcId\x12E\n" +
	"\x0equery_template\x18\x05 \x01(\v2\x1e.veidemann.api.log.v1.CrawlLogR\rqueryTemplate\x12B\n" +
	"\n" +
	"query_mask\x18\x06 \x01(\v2#.veidemann.api.commons.v1.FieldMaskR\tqueryMask\x12U\n" +
	"\x14returned_fields_mask\x18\a \x01(\v2#.veidemann.api.commons.v1.FieldMaskR\x12returnedFieldsMask\x12\"\n" +
	"\rorder_by_path\x18\b \x01(\tR\vorderByPath\x12)\n" +
	"\x10order_descending\x18\t \x01(\bR\x0forderDescending\x12\x14\n" +
	"\x05watch\x18\r \x01(\bR\x05watch\x12\x1b\n" +
	"\tpage_size\x18\x0e \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06offset\x18\x0f \x01(\x05R\x06offset\"\xa8\x03\n" +
	"\x12PageLogListRequest\x12\x17\n" +
	"\awarc_id\x18\x02 \x03(\tR\x06warcId\x12D\n" +
	"\x0equery_template\x18\x05 \x01(\v2\x1d.veidemann.api.log.v1.PageLogR\rqueryTemplate\x12B\n" +
	"\n" +
	"query_mask\x18\x06 \x01(\v2#.veidemann.api.commons.v1.FieldMaskR\tqueryMask\x12U\n" +
	"\x14returned_fields_mask\x18\a \x01(\v2#.veidemann.api.commons.v1.FieldMaskR\x12returnedFieldsMask\x12\"\n" +
	"\rorder_by_path\x18\b \x01(\tR\vorderByPath\x12)\n" +
	"\x10order_descending\x18\t \x01(\bR\x0forderDescending\x12\x14\n" +
	"\x05watch\x18\r \x01(\bR\x05watch\x12\x1b\n" +
	"\tpage_size\x18\x0e \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06offset\x18\x0f \x01(\x05R\x06offset\"\xbe\x01\n" +
	"\x13WritePageLogRequest\x12<\n" +
	"\bcrawlLog\x18\x01 \x01(\v2\x1e.veidemann.api.log.v1.CrawlLogH\x00R\bcrawlLog\x12D\n" +
	"\bresource\x18\x02 \x01(\v2&.veidemann.api.log.v1.PageLog.ResourceH\x00R\bresource\x12\x1a\n" +
	"\aoutlink\x18\x03 \x01(\tH\x00R\aoutlinkB\a\n" +
	"\x05value\"R\n" +
	"\x14WriteCrawlLogRequest\x12:\n" +
	"\bcrawlLog\x18\x01 \x01(\v2\x1e.veidemann.api.log.v1.CrawlLogR\bcrawlLog2\xf2\x02\n" +
	"\x03Log\x12^\n" +
	"\rListCrawlLogs\x12).veidemann.api.log.v1.CrawlLogListRequest\x1a\x1e.veidemann.api.log.v1.CrawlLog\"\x000\x01\x12[\n" +
	"\fListPageLogs\x12(.veidemann.api.log.v1.PageLogListRequest\x1a\x1d.veidemann.api.log.v1.PageLog\"\x000\x01\x12W\n" +
	"\rWriteCrawlLog\x12*.veidemann.api.log.v1.WriteCrawlLogRequest\x1a\x16.google.protobuf.Empty\"\x00(\x01\x12U\n" +
	"\fWritePageLog\x12).veidemann.api.log.v1.WritePageLogRequest\x1a\x16.google.protobuf.Empty\"\x00(\x01B\xd0\x01\n" +
	"\x18com.veidemann.api.log.v1B\bLogProtoP\x01Z7github.com/NationalLibraryOfNorway/veidemann/api/log/v1\xa2\x02\x03VAL\xaa\x02\x14Veidemann.Api.Log.V1\xca\x02\x14Veidemann\\Api\\Log\\V1\xe2\x02 Veidemann\\Api\\Log\\V1\\GPBMetadata\xea\x02\x17Veidemann::Api::Log::V1b\x06proto3"

var (
	file_log_v1_log_proto_rawDescOnce sync.Once
	file_log_v1_log_proto_rawDescData []byte
)

func file_log_v1_log_proto_rawDescGZIP() []byte {
	file_log_v1_log_proto_rawDescOnce.Do(func() {
		file_log_v1_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_log_v1_log_proto_rawDesc), len(file_log_v1_log_proto_rawDesc)))
	})
	return file_log_v1_log_proto_rawDescData
}

var file_log_v1_log_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_log_v1_log_proto_goTypes = []any{
	(*CrawlLogListRequest)(nil),  // 0: veidemann.api.log.v1.CrawlLogListRequest
	(*PageLogListRequest)(nil),   // 1: veidemann.api.log.v1.PageLogListRequest
	(*WritePageLogRequest)(nil),  // 2: veidemann.api.log.v1.WritePageLogRequest
	(*WriteCrawlLogRequest)(nil), // 3: veidemann.api.log.v1.WriteCrawlLogRequest
	(*CrawlLog)(nil),             // 4: veidemann.api.log.v1.CrawlLog
	(*v1.FieldMask)(nil),         // 5: veidemann.api.commons.v1.FieldMask
	(*PageLog)(nil),              // 6: veidemann.api.log.v1.PageLog
	(*PageLog_Resource)(nil),     // 7: veidemann.api.log.v1.PageLog.Resource
	(*emptypb.Empty)(nil),        // 8: google.protobuf.Empty
}
var file_log_v1_log_proto_depIdxs = []int32{
	4,  // 0: veidemann.api.log.v1.CrawlLogListRequest.query_template:type_name -> veidemann.api.log.v1.CrawlLog
	5,  // 1: veidemann.api.log.v1.CrawlLogListRequest.query_mask:type_name -> veidemann.api.commons.v1.FieldMask
	5,  // 2: veidemann.api.log.v1.CrawlLogListRequest.returned_fields_mask:type_name -> veidemann.api.commons.v1.FieldMask
	6,  // 3: veidemann.api.log.v1.PageLogListRequest.query_template:type_name -> veidemann.api.log.v1.PageLog
	5,  // 4: veidemann.api.log.v1.PageLogListRequest.query_mask:type_name -> veidemann.api.commons.v1.FieldMask
	5,  // 5: veidemann.api.log.v1.PageLogListRequest.returned_fields_mask:type_name -> veidemann.api.commons.v1.FieldMask
	4,  // 6: veidemann.api.log.v1.WritePageLogRequest.crawlLog:type_name -> veidemann.api.log.v1.CrawlLog
	7,  // 7: veidemann.api.log.v1.WritePageLogRequest.resource:type_name -> veidemann.api.log.v1.PageLog.Resource
	4,  // 8: veidemann.api.log.v1.WriteCrawlLogRequest.crawlLog:type_name -> veidemann.api.log.v1.CrawlLog
	0,  // 9: veidemann.api.log.v1.Log.ListCrawlLogs:input_type -> veidemann.api.log.v1.CrawlLogListRequest
	1,  // 10: veidemann.api.log.v1.Log.ListPageLogs:input_type -> veidemann.api.log.v1.PageLogListRequest
	3,  // 11: veidemann.api.log.v1.Log.WriteCrawlLog:input_type -> veidemann.api.log.v1.WriteCrawlLogRequest
	2,  // 12: veidemann.api.log.v1.Log.WritePageLog:input_type -> veidemann.api.log.v1.WritePageLogRequest
	4,  // 13: veidemann.api.log.v1.Log.ListCrawlLogs:output_type -> veidemann.api.log.v1.CrawlLog
	6,  // 14: veidemann.api.log.v1.Log.ListPageLogs:output_type -> veidemann.api.log.v1.PageLog
	8,  // 15: veidemann.api.log.v1.Log.WriteCrawlLog:output_type -> google.protobuf.Empty
	8,  // 16: veidemann.api.log.v1.Log.WritePageLog:output_type -> google.protobuf.Empty
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_log_v1_log_proto_init() }
func file_log_v1_log_proto_init() {
	if File_log_v1_log_proto != nil {
		return
	}
	file_log_v1_resources_proto_init()
	file_log_v1_log_proto_msgTypes[2].OneofWrappers = []any{
		(*WritePageLogRequest_CrawlLog)(nil),
		(*WritePageLogRequest_Resource)(nil),
		(*WritePageLogRequest_Outlink)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_log_v1_log_proto_rawDesc), len(file_log_v1_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_log_v1_log_proto_goTypes,
		DependencyIndexes: file_log_v1_log_proto_depIdxs,
		MessageInfos:      file_log_v1_log_proto_msgTypes,
	}.Build()
	File_log_v1_log_proto = out.File
	file_log_v1_log_proto_goTypes = nil
	file_log_v1_log_proto_depIdxs = nil
}
