// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: browsercontroller/v1/browsercontroller.proto

package v1

import (
	v1 "github.com/NationalLibraryOfNorway/veidemann/api/config/v1"
	v11 "github.com/NationalLibraryOfNorway/veidemann/api/log/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotifyActivity_Activity int32

const (
	NotifyActivity_DATA_RECEIVED     NotifyActivity_Activity = 0
	NotifyActivity_ALL_DATA_RECEIVED NotifyActivity_Activity = 1
)

// Enum value maps for NotifyActivity_Activity.
var (
	NotifyActivity_Activity_name = map[int32]string{
		0: "DATA_RECEIVED",
		1: "ALL_DATA_RECEIVED",
	}
	NotifyActivity_Activity_value = map[string]int32{
		"DATA_RECEIVED":     0,
		"ALL_DATA_RECEIVED": 1,
	}
)

func (x NotifyActivity_Activity) Enum() *NotifyActivity_Activity {
	p := new(NotifyActivity_Activity)
	*p = x
	return p
}

func (x NotifyActivity_Activity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotifyActivity_Activity) Descriptor() protoreflect.EnumDescriptor {
	return file_browsercontroller_v1_browsercontroller_proto_enumTypes[0].Descriptor()
}

func (NotifyActivity_Activity) Type() protoreflect.EnumType {
	return &file_browsercontroller_v1_browsercontroller_proto_enumTypes[0]
}

func (x NotifyActivity_Activity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotifyActivity_Activity.Descriptor instead.
func (NotifyActivity_Activity) EnumDescriptor() ([]byte, []int) {
	return file_browsercontroller_v1_browsercontroller_proto_rawDescGZIP(), []int{1, 0}
}

type RegisterNew struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProxyId          int32                  `protobuf:"varint,1,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"`
	Uri              string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	CrawlExecutionId string                 `protobuf:"bytes,3,opt,name=crawl_execution_id,json=crawlExecutionId,proto3" json:"crawl_execution_id,omitempty"`
	JobExecutionId   string                 `protobuf:"bytes,4,opt,name=job_execution_id,json=jobExecutionId,proto3" json:"job_execution_id,omitempty"`
	CollectionRef    *v1.ConfigRef          `protobuf:"bytes,5,opt,name=collection_ref,json=collectionRef,proto3" json:"collection_ref,omitempty"`
	Method           string                 `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"`                        // The HTTP method (GET, POST, HEAD, ...)
	RequestId        string                 `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // The browsers internal request id.
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterNew) Reset() {
	*x = RegisterNew{}
	mi := &file_browsercontroller_v1_browsercontroller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNew) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNew) ProtoMessage() {}

func (x *RegisterNew) ProtoReflect() protoreflect.Message {
	mi := &file_browsercontroller_v1_browsercontroller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNew.ProtoReflect.Descriptor instead.
func (*RegisterNew) Descriptor() ([]byte, []int) {
	return file_browsercontroller_v1_browsercontroller_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterNew) GetProxyId() int32 {
	if x != nil {
		return x.ProxyId
	}
	return 0
}

func (x *RegisterNew) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *RegisterNew) GetCrawlExecutionId() string {
	if x != nil {
		return x.CrawlExecutionId
	}
	return ""
}

func (x *RegisterNew) GetJobExecutionId() string {
	if x != nil {
		return x.JobExecutionId
	}
	return ""
}

func (x *RegisterNew) GetCollectionRef() *v1.ConfigRef {
	if x != nil {
		return x.CollectionRef
	}
	return nil
}

func (x *RegisterNew) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RegisterNew) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type NotifyActivity struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Activity      NotifyActivity_Activity `protobuf:"varint,1,opt,name=activity,proto3,enum=veidemann.api.browsercontroller.v1.NotifyActivity_Activity" json:"activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyActivity) Reset() {
	*x = NotifyActivity{}
	mi := &file_browsercontroller_v1_browsercontroller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyActivity) ProtoMessage() {}

func (x *NotifyActivity) ProtoReflect() protoreflect.Message {
	mi := &file_browsercontroller_v1_browsercontroller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyActivity.ProtoReflect.Descriptor instead.
func (*NotifyActivity) Descriptor() ([]byte, []int) {
	return file_browsercontroller_v1_browsercontroller_proto_rawDescGZIP(), []int{1}
}

func (x *NotifyActivity) GetActivity() NotifyActivity_Activity {
	if x != nil {
		return x.Activity
	}
	return NotifyActivity_DATA_RECEIVED
}

type Completed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CrawlLog      *v11.CrawlLog          `protobuf:"bytes,1,opt,name=crawl_log,json=crawlLog,proto3" json:"crawl_log,omitempty"`
	Cached        bool                   `protobuf:"varint,2,opt,name=cached,proto3" json:"cached,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Completed) Reset() {
	*x = Completed{}
	mi := &file_browsercontroller_v1_browsercontroller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Completed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Completed) ProtoMessage() {}

func (x *Completed) ProtoReflect() protoreflect.Message {
	mi := &file_browsercontroller_v1_browsercontroller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Completed.ProtoReflect.Descriptor instead.
func (*Completed) Descriptor() ([]byte, []int) {
	return file_browsercontroller_v1_browsercontroller_proto_rawDescGZIP(), []int{2}
}

func (x *Completed) GetCrawlLog() *v11.CrawlLog {
	if x != nil {
		return x.CrawlLog
	}
	return nil
}

func (x *Completed) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

type DoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Action:
	//
	//	*DoRequest_New
	//	*DoRequest_Notify
	//	*DoRequest_Completed
	Action        isDoRequest_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoRequest) Reset() {
	*x = DoRequest{}
	mi := &file_browsercontroller_v1_browsercontroller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoRequest) ProtoMessage() {}

func (x *DoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browsercontroller_v1_browsercontroller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoRequest.ProtoReflect.Descriptor instead.
func (*DoRequest) Descriptor() ([]byte, []int) {
	return file_browsercontroller_v1_browsercontroller_proto_rawDescGZIP(), []int{3}
}

func (x *DoRequest) GetAction() isDoRequest_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *DoRequest) GetNew() *RegisterNew {
	if x != nil {
		if x, ok := x.Action.(*DoRequest_New); ok {
			return x.New
		}
	}
	return nil
}

func (x *DoRequest) GetNotify() *NotifyActivity {
	if x != nil {
		if x, ok := x.Action.(*DoRequest_Notify); ok {
			return x.Notify
		}
	}
	return nil
}

func (x *DoRequest) GetCompleted() *Completed {
	if x != nil {
		if x, ok := x.Action.(*DoRequest_Completed); ok {
			return x.Completed
		}
	}
	return nil
}

type isDoRequest_Action interface {
	isDoRequest_Action()
}

type DoRequest_New struct {
	New *RegisterNew `protobuf:"bytes,1,opt,name=new,proto3,oneof"`
}

type DoRequest_Notify struct {
	Notify *NotifyActivity `protobuf:"bytes,2,opt,name=notify,proto3,oneof"`
}

type DoRequest_Completed struct {
	Completed *Completed `protobuf:"bytes,3,opt,name=completed,proto3,oneof"`
}

func (*DoRequest_New) isDoRequest_Action() {}

func (*DoRequest_Notify) isDoRequest_Action() {}

func (*DoRequest_Completed) isDoRequest_Action() {}

type NewReply struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CrawlExecutionId  string                 `protobuf:"bytes,1,opt,name=crawl_execution_id,json=crawlExecutionId,proto3" json:"crawl_execution_id,omitempty"`
	JobExecutionId    string                 `protobuf:"bytes,2,opt,name=job_execution_id,json=jobExecutionId,proto3" json:"job_execution_id,omitempty"`
	CollectionRef     *v1.ConfigRef          `protobuf:"bytes,4,opt,name=collection_ref,json=collectionRef,proto3" json:"collection_ref,omitempty"`
	ReplacementScript *v1.BrowserScript      `protobuf:"bytes,5,opt,name=replacement_script,json=replacementScript,proto3" json:"replacement_script,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NewReply) Reset() {
	*x = NewReply{}
	mi := &file_browsercontroller_v1_browsercontroller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewReply) ProtoMessage() {}

func (x *NewReply) ProtoReflect() protoreflect.Message {
	mi := &file_browsercontroller_v1_browsercontroller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewReply.ProtoReflect.Descriptor instead.
func (*NewReply) Descriptor() ([]byte, []int) {
	return file_browsercontroller_v1_browsercontroller_proto_rawDescGZIP(), []int{4}
}

func (x *NewReply) GetCrawlExecutionId() string {
	if x != nil {
		return x.CrawlExecutionId
	}
	return ""
}

func (x *NewReply) GetJobExecutionId() string {
	if x != nil {
		return x.JobExecutionId
	}
	return ""
}

func (x *NewReply) GetCollectionRef() *v1.ConfigRef {
	if x != nil {
		return x.CollectionRef
	}
	return nil
}

func (x *NewReply) GetReplacementScript() *v1.BrowserScript {
	if x != nil {
		return x.ReplacementScript
	}
	return nil
}

type DoReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Action:
	//
	//	*DoReply_New
	//	*DoReply_Cancel
	Action        isDoReply_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoReply) Reset() {
	*x = DoReply{}
	mi := &file_browsercontroller_v1_browsercontroller_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoReply) ProtoMessage() {}

func (x *DoReply) ProtoReflect() protoreflect.Message {
	mi := &file_browsercontroller_v1_browsercontroller_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoReply.ProtoReflect.Descriptor instead.
func (*DoReply) Descriptor() ([]byte, []int) {
	return file_browsercontroller_v1_browsercontroller_proto_rawDescGZIP(), []int{5}
}

func (x *DoReply) GetAction() isDoReply_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *DoReply) GetNew() *NewReply {
	if x != nil {
		if x, ok := x.Action.(*DoReply_New); ok {
			return x.New
		}
	}
	return nil
}

func (x *DoReply) GetCancel() string {
	if x != nil {
		if x, ok := x.Action.(*DoReply_Cancel); ok {
			return x.Cancel
		}
	}
	return ""
}

type isDoReply_Action interface {
	isDoReply_Action()
}

type DoReply_New struct {
	New *NewReply `protobuf:"bytes,1,opt,name=new,proto3,oneof"`
}

type DoReply_Cancel struct {
	Cancel string `protobuf:"bytes,4,opt,name=cancel,proto3,oneof"` // Roll back the request. The message should contain the reason for canceling the request.
}

func (*DoReply_New) isDoReply_Action() {}

func (*DoReply_Cancel) isDoReply_Action() {}

var File_browsercontroller_v1_browsercontroller_proto protoreflect.FileDescriptor

const file_browsercontroller_v1_browsercontroller_proto_rawDesc = "" +
	"\n" +
	",browsercontroller/v1/browsercontroller.proto\x12\"veidemann.api.browsercontroller.v1\x1a\x19config/v1/resources.proto\x1a\x16log/v1/resources.proto\"\x94\x02\n" +
	"\vRegisterNew\x12\x19\n" +
	"\bproxy_id\x18\x01 \x01(\x05R\aproxyId\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12,\n" +
	"\x12crawl_execution_id\x18\x03 \x01(\tR\x10crawlExecutionId\x12(\n" +
	"\x10job_execution_id\x18\x04 \x01(\tR\x0ejobExecutionId\x12I\n" +
	"\x0ecollection_ref\x18\x05 \x01(\v2\".veidemann.api.config.v1.ConfigRefR\rcollectionRef\x12\x16\n" +
	"\x06method\x18\x06 \x01(\tR\x06method\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\"\x9f\x01\n" +
	"\x0eNotifyActivity\x12W\n" +
	"\bactivity\x18\x01 \x01(\x0e2;.veidemann.api.browsercontroller.v1.NotifyActivity.ActivityR\bactivity\"4\n" +
	"\bActivity\x12\x11\n" +
	"\rDATA_RECEIVED\x10\x00\x12\x15\n" +
	"\x11ALL_DATA_RECEIVED\x10\x01\"`\n" +
	"\tCompleted\x12;\n" +
	"\tcrawl_log\x18\x01 \x01(\v2\x1e.veidemann.api.log.v1.CrawlLogR\bcrawlLog\x12\x16\n" +
	"\x06cached\x18\x02 \x01(\bR\x06cached\"\xf7\x01\n" +
	"\tDoRequest\x12C\n" +
	"\x03new\x18\x01 \x01(\v2/.veidemann.api.browsercontroller.v1.RegisterNewH\x00R\x03new\x12L\n" +
	"\x06notify\x18\x02 \x01(\v22.veidemann.api.browsercontroller.v1.NotifyActivityH\x00R\x06notify\x12M\n" +
	"\tcompleted\x18\x03 \x01(\v2-.veidemann.api.browsercontroller.v1.CompletedH\x00R\tcompletedB\b\n" +
	"\x06action\"\x84\x02\n" +
	"\bNewReply\x12,\n" +
	"\x12crawl_execution_id\x18\x01 \x01(\tR\x10crawlExecutionId\x12(\n" +
	"\x10job_execution_id\x18\x02 \x01(\tR\x0ejobExecutionId\x12I\n" +
	"\x0ecollection_ref\x18\x04 \x01(\v2\".veidemann.api.config.v1.ConfigRefR\rcollectionRef\x12U\n" +
	"\x12replacement_script\x18\x05 \x01(\v2&.veidemann.api.config.v1.BrowserScriptR\x11replacementScript\"o\n" +
	"\aDoReply\x12@\n" +
	"\x03new\x18\x01 \x01(\v2,.veidemann.api.browsercontroller.v1.NewReplyH\x00R\x03new\x12\x18\n" +
	"\x06cancel\x18\x04 \x01(\tH\x00R\x06cancelB\b\n" +
	"\x06action2{\n" +
	"\x11BrowserController\x12f\n" +
	"\x02do\x12-.veidemann.api.browsercontroller.v1.DoRequest\x1a+.veidemann.api.browsercontroller.v1.DoReply\"\x00(\x010\x01B\xb2\x02\n" +
	"&com.veidemann.api.browsercontroller.v1B\x16BrowsercontrollerProtoP\x01ZEgithub.com/NationalLibraryOfNorway/veidemann/api/browsercontroller/v1\xa2\x02\x03VAB\xaa\x02\"Veidemann.Api.Browsercontroller.V1\xca\x02\"Veidemann\\Api\\Browsercontroller\\V1\xe2\x02.Veidemann\\Api\\Browsercontroller\\V1\\GPBMetadata\xea\x02%Veidemann::Api::Browsercontroller::V1b\x06proto3"

var (
	file_browsercontroller_v1_browsercontroller_proto_rawDescOnce sync.Once
	file_browsercontroller_v1_browsercontroller_proto_rawDescData []byte
)

func file_browsercontroller_v1_browsercontroller_proto_rawDescGZIP() []byte {
	file_browsercontroller_v1_browsercontroller_proto_rawDescOnce.Do(func() {
		file_browsercontroller_v1_browsercontroller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_browsercontroller_v1_browsercontroller_proto_rawDesc), len(file_browsercontroller_v1_browsercontroller_proto_rawDesc)))
	})
	return file_browsercontroller_v1_browsercontroller_proto_rawDescData
}

var file_browsercontroller_v1_browsercontroller_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_browsercontroller_v1_browsercontroller_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_browsercontroller_v1_browsercontroller_proto_goTypes = []any{
	(NotifyActivity_Activity)(0), // 0: veidemann.api.browsercontroller.v1.NotifyActivity.Activity
	(*RegisterNew)(nil),          // 1: veidemann.api.browsercontroller.v1.RegisterNew
	(*NotifyActivity)(nil),       // 2: veidemann.api.browsercontroller.v1.NotifyActivity
	(*Completed)(nil),            // 3: veidemann.api.browsercontroller.v1.Completed
	(*DoRequest)(nil),            // 4: veidemann.api.browsercontroller.v1.DoRequest
	(*NewReply)(nil),             // 5: veidemann.api.browsercontroller.v1.NewReply
	(*DoReply)(nil),              // 6: veidemann.api.browsercontroller.v1.DoReply
	(*v1.ConfigRef)(nil),         // 7: veidemann.api.config.v1.ConfigRef
	(*v11.CrawlLog)(nil),         // 8: veidemann.api.log.v1.CrawlLog
	(*v1.BrowserScript)(nil),     // 9: veidemann.api.config.v1.BrowserScript
}
var file_browsercontroller_v1_browsercontroller_proto_depIdxs = []int32{
	7,  // 0: veidemann.api.browsercontroller.v1.RegisterNew.collection_ref:type_name -> veidemann.api.config.v1.ConfigRef
	0,  // 1: veidemann.api.browsercontroller.v1.NotifyActivity.activity:type_name -> veidemann.api.browsercontroller.v1.NotifyActivity.Activity
	8,  // 2: veidemann.api.browsercontroller.v1.Completed.crawl_log:type_name -> veidemann.api.log.v1.CrawlLog
	1,  // 3: veidemann.api.browsercontroller.v1.DoRequest.new:type_name -> veidemann.api.browsercontroller.v1.RegisterNew
	2,  // 4: veidemann.api.browsercontroller.v1.DoRequest.notify:type_name -> veidemann.api.browsercontroller.v1.NotifyActivity
	3,  // 5: veidemann.api.browsercontroller.v1.DoRequest.completed:type_name -> veidemann.api.browsercontroller.v1.Completed
	7,  // 6: veidemann.api.browsercontroller.v1.NewReply.collection_ref:type_name -> veidemann.api.config.v1.ConfigRef
	9,  // 7: veidemann.api.browsercontroller.v1.NewReply.replacement_script:type_name -> veidemann.api.config.v1.BrowserScript
	5,  // 8: veidemann.api.browsercontroller.v1.DoReply.new:type_name -> veidemann.api.browsercontroller.v1.NewReply
	4,  // 9: veidemann.api.browsercontroller.v1.BrowserController.do:input_type -> veidemann.api.browsercontroller.v1.DoRequest
	6,  // 10: veidemann.api.browsercontroller.v1.BrowserController.do:output_type -> veidemann.api.browsercontroller.v1.DoReply
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_browsercontroller_v1_browsercontroller_proto_init() }
func file_browsercontroller_v1_browsercontroller_proto_init() {
	if File_browsercontroller_v1_browsercontroller_proto != nil {
		return
	}
	file_browsercontroller_v1_browsercontroller_proto_msgTypes[3].OneofWrappers = []any{
		(*DoRequest_New)(nil),
		(*DoRequest_Notify)(nil),
		(*DoRequest_Completed)(nil),
	}
	file_browsercontroller_v1_browsercontroller_proto_msgTypes[5].OneofWrappers = []any{
		(*DoReply_New)(nil),
		(*DoReply_Cancel)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_browsercontroller_v1_browsercontroller_proto_rawDesc), len(file_browsercontroller_v1_browsercontroller_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_browsercontroller_v1_browsercontroller_proto_goTypes,
		DependencyIndexes: file_browsercontroller_v1_browsercontroller_proto_depIdxs,
		EnumInfos:         file_browsercontroller_v1_browsercontroller_proto_enumTypes,
		MessageInfos:      file_browsercontroller_v1_browsercontroller_proto_msgTypes,
	}.Build()
	File_browsercontroller_v1_browsercontroller_proto = out.File
	file_browsercontroller_v1_browsercontroller_proto_goTypes = nil
	file_browsercontroller_v1_browsercontroller_proto_depIdxs = nil
}
