FROM golang:1.27 AS build

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build \
    -trimpath \
    -ldflags "-s -w" \
    -o /out/app .


FROM gcr.io/distroless/base-debian12:nonroot

COPY --from=build /out/app /app

ENTRYPOINT ["/app"]
