apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - service.yaml
  - pdb.yaml
  - networkpolicy.yaml
  - configmap.yaml
  - scripts-configmap.yaml
  - statefulset.yaml
