apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kvrocks-same-namespace
  labels:
    app.kubernetes.io/name: kvrocks
    app.kubernetes.io/component: datastore
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: kvrocks
      app.kubernetes.io/component: datastore
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - port: 6666
          protocol: TCP
        - port: 26379
          protocol: TCP
        - port: 9121
          protocol: TCP