apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kvrocks
  labels:
    app.kubernetes.io/name: kvrocks
    app.kubernetes.io/component: datastore
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kvrocks
      app.kubernetes.io/component: datastore