// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: commons/v1/resources.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_commons_v1_resources_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_commons_v1_resources_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_commons_v1_resources_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Error) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type FieldMask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []string               `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldMask) Reset() {
	*x = FieldMask{}
	mi := &file_commons_v1_resources_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldMask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldMask) ProtoMessage() {}

func (x *FieldMask) ProtoReflect() protoreflect.Message {
	mi := &file_commons_v1_resources_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldMask.ProtoReflect.Descriptor instead.
func (*FieldMask) Descriptor() ([]byte, []int) {
	return file_commons_v1_resources_proto_rawDescGZIP(), []int{1}
}

func (x *FieldMask) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type ParsedUri struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The entire uri
	Href string `protobuf:"bytes,1,opt,name=href,proto3" json:"href,omitempty"`
	// The scheme (protocol) part of the uri
	Scheme string `protobuf:"bytes,2,opt,name=scheme,proto3" json:"scheme,omitempty"`
	// The hostname of the uri
	Host string `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	// The port number of the uri
	Port int32 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	// The username part of the uri
	Username string `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	// The password part of the uri
	Password string `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	// The path part of the uri
	Path string `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	// The query (search) part of the uri
	Query string `protobuf:"bytes,8,opt,name=query,proto3" json:"query,omitempty"`
	// The fragment (hash) part of the uri
	Fragment      string `protobuf:"bytes,9,opt,name=fragment,proto3" json:"fragment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParsedUri) Reset() {
	*x = ParsedUri{}
	mi := &file_commons_v1_resources_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedUri) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedUri) ProtoMessage() {}

func (x *ParsedUri) ProtoReflect() protoreflect.Message {
	mi := &file_commons_v1_resources_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedUri.ProtoReflect.Descriptor instead.
func (*ParsedUri) Descriptor() ([]byte, []int) {
	return file_commons_v1_resources_proto_rawDescGZIP(), []int{2}
}

func (x *ParsedUri) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

func (x *ParsedUri) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *ParsedUri) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ParsedUri) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ParsedUri) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ParsedUri) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ParsedUri) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ParsedUri) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ParsedUri) GetFragment() string {
	if x != nil {
		return x.Fragment
	}
	return ""
}

type ExtractedText struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WarcId         string                 `protobuf:"bytes,1,opt,name=warc_id,json=warcId,proto3" json:"warc_id,omitempty"`
	Text           string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	SentenceCount  int64                  `protobuf:"varint,3,opt,name=sentence_count,json=sentenceCount,proto3" json:"sentence_count,omitempty"`
	WordCount      int64                  `protobuf:"varint,4,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"`
	LongWordCount  int64                  `protobuf:"varint,5,opt,name=long_word_count,json=longWordCount,proto3" json:"long_word_count,omitempty"`
	CharacterCount int64                  `protobuf:"varint,6,opt,name=character_count,json=characterCount,proto3" json:"character_count,omitempty"`
	Lix            int64                  `protobuf:"varint,7,opt,name=lix,proto3" json:"lix,omitempty"`
	Language       string                 `protobuf:"bytes,8,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExtractedText) Reset() {
	*x = ExtractedText{}
	mi := &file_commons_v1_resources_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractedText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractedText) ProtoMessage() {}

func (x *ExtractedText) ProtoReflect() protoreflect.Message {
	mi := &file_commons_v1_resources_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractedText.ProtoReflect.Descriptor instead.
func (*ExtractedText) Descriptor() ([]byte, []int) {
	return file_commons_v1_resources_proto_rawDescGZIP(), []int{3}
}

func (x *ExtractedText) GetWarcId() string {
	if x != nil {
		return x.WarcId
	}
	return ""
}

func (x *ExtractedText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ExtractedText) GetSentenceCount() int64 {
	if x != nil {
		return x.SentenceCount
	}
	return 0
}

func (x *ExtractedText) GetWordCount() int64 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

func (x *ExtractedText) GetLongWordCount() int64 {
	if x != nil {
		return x.LongWordCount
	}
	return 0
}

func (x *ExtractedText) GetCharacterCount() int64 {
	if x != nil {
		return x.CharacterCount
	}
	return 0
}

func (x *ExtractedText) GetLix() int64 {
	if x != nil {
		return x.Lix
	}
	return 0
}

func (x *ExtractedText) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

var File_commons_v1_resources_proto protoreflect.FileDescriptor

const file_commons_v1_resources_proto_rawDesc = "" +
	"\n" +
	"\x1acommons/v1/resources.proto\x12\x18veidemann.api.commons.v1\"E\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"!\n" +
	"\tFieldMask\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\"\xdd\x01\n" +
	"\tParsedUri\x12\x12\n" +
	"\x04href\x18\x01 \x01(\tR\x04href\x12\x16\n" +
	"\x06scheme\x18\x02 \x01(\tR\x06scheme\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\x12\x14\n" +
	"\x05query\x18\b \x01(\tR\x05query\x12\x1a\n" +
	"\bfragment\x18\t \x01(\tR\bfragment\"\x81\x02\n" +
	"\rExtractedText\x12\x17\n" +
	"\awarc_id\x18\x01 \x01(\tR\x06warcId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12%\n" +
	"\x0esentence_count\x18\x03 \x01(\x03R\rsentenceCount\x12\x1d\n" +
	"\n" +
	"word_count\x18\x04 \x01(\x03R\twordCount\x12&\n" +
	"\x0flong_word_count\x18\x05 \x01(\x03R\rlongWordCount\x12'\n" +
	"\x0fcharacter_count\x18\x06 \x01(\x03R\x0echaracterCount\x12\x10\n" +
	"\x03lix\x18\a \x01(\x03R\x03lix\x12\x1a\n" +
	"\blanguage\x18\b \x01(\tR\blanguageB\xee\x01\n" +
	"\x1ccom.veidemann.api.commons.v1B\x0eResourcesProtoP\x01Z;github.com/NationalLibraryOfNorway/veidemann/api/commons/v1\xa2\x02\x03VAC\xaa\x02\x18Veidemann.Api.Commons.V1\xca\x02\x18Veidemann\\Api\\Commons\\V1\xe2\x02$Veidemann\\Api\\Commons\\V1\\GPBMetadata\xea\x02\x1bVeidemann::Api::Commons::V1b\x06proto3"

var (
	file_commons_v1_resources_proto_rawDescOnce sync.Once
	file_commons_v1_resources_proto_rawDescData []byte
)

func file_commons_v1_resources_proto_rawDescGZIP() []byte {
	file_commons_v1_resources_proto_rawDescOnce.Do(func() {
		file_commons_v1_resources_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_commons_v1_resources_proto_rawDesc), len(file_commons_v1_resources_proto_rawDesc)))
	})
	return file_commons_v1_resources_proto_rawDescData
}

var file_commons_v1_resources_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_commons_v1_resources_proto_goTypes = []any{
	(*Error)(nil),         // 0: veidemann.api.commons.v1.Error
	(*FieldMask)(nil),     // 1: veidemann.api.commons.v1.FieldMask
	(*ParsedUri)(nil),     // 2: veidemann.api.commons.v1.ParsedUri
	(*ExtractedText)(nil), // 3: veidemann.api.commons.v1.ExtractedText
}
var file_commons_v1_resources_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_commons_v1_resources_proto_init() }
func file_commons_v1_resources_proto_init() {
	if File_commons_v1_resources_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commons_v1_resources_proto_rawDesc), len(file_commons_v1_resources_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commons_v1_resources_proto_goTypes,
		DependencyIndexes: file_commons_v1_resources_proto_depIdxs,
		MessageInfos:      file_commons_v1_resources_proto_msgTypes,
	}.Build()
	File_commons_v1_resources_proto = out.File
	file_commons_v1_resources_proto_goTypes = nil
	file_commons_v1_resources_proto_depIdxs = nil
}
