// @generated by protoc-gen-es v2.10.1 with parameter "target=ts,import_extension=none"
// @generated from file dnsresolver/v1/dnsresolver.proto (package veidemann.api.dnsresolver.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { ConfigRef } from "../../config/v1/resources_pb";
import { file_config_v1_resources } from "../../config/v1/resources_pb";
import type { Error } from "../../commons/v1/resources_pb";
import { file_commons_v1_resources } from "../../commons/v1/resources_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dnsresolver/v1/dnsresolver.proto.
 */
export const file_dnsresolver_v1_dnsresolver: GenFile = /*@__PURE__*/
  fileDesc("CiBkbnNyZXNvbHZlci92MS9kbnNyZXNvbHZlci5wcm90bxIcdmVpZGVtYW5uLmFwaS5kbnNyZXNvbHZlci52MSKCAQoOUmVzb2x2ZVJlcXVlc3QSDAoEaG9zdBgBIAEoCRIQCgRwb3J0GAIgASgFQgIYARIUCgxleGVjdXRpb25faWQYBiABKAkSOgoOY29sbGVjdGlvbl9yZWYYByABKAsyIi52ZWlkZW1hbm4uYXBpLmNvbmZpZy52MS5Db25maWdSZWYiggEKDFJlc29sdmVSZXBseRIMCgRob3N0GAEgASgJEhAKBHBvcnQYAiABKAVCAhgBEhIKCnRleHR1YWxfaXAYAyABKAkSDgoGcmF3X2lwGAQgASgMEi4KBWVycm9yGAUgASgLMh8udmVpZGVtYW5uLmFwaS5jb21tb25zLnYxLkVycm9yMnQKC0Ruc1Jlc29sdmVyEmUKB3Jlc29sdmUSLC52ZWlkZW1hbm4uYXBpLmRuc3Jlc29sdmVyLnYxLlJlc29sdmVSZXF1ZXN0GioudmVpZGVtYW5uLmFwaS5kbnNyZXNvbHZlci52MS5SZXNvbHZlUmVwbHkiAEJ/CiZuby5uYi5ubmEudmVpZGVtYW5uLmFwaS5kbnNyZXNvbHZlci52MUISRG5zUmVzb2x2ZXJTZXJ2aWNlUAFaP2dpdGh1Yi5jb20vTmF0aW9uYWxMaWJyYXJ5T2ZOb3J3YXkvdmVpZGVtYW5uL2FwaS9kbnNyZXNvbHZlci92MWIGcHJvdG8z", [file_config_v1_resources, file_commons_v1_resources]);

/**
 * @generated from message veidemann.api.dnsresolver.v1.ResolveRequest
 */
export type ResolveRequest = Message<"veidemann.api.dnsresolver.v1.ResolveRequest"> & {
  /**
   * @generated from field: string host = 1;
   */
  host: string;

  /**
   * Deprecated: a port is application metadata and is not part of DNS resolution.
   *
   * @generated from field: int32 port = 2 [deprecated = true];
   * @deprecated
   */
  port: number;

  /**
   * @generated from field: string execution_id = 6;
   */
  executionId: string;

  /**
   * @generated from field: veidemann.api.config.v1.ConfigRef collection_ref = 7;
   */
  collectionRef?: ConfigRef;
};

/**
 * Describes the message veidemann.api.dnsresolver.v1.ResolveRequest.
 * Use `create(ResolveRequestSchema)` to create a new message.
 */
export const ResolveRequestSchema: GenMessage<ResolveRequest> = /*@__PURE__*/
  messageDesc(file_dnsresolver_v1_dnsresolver, 0);

/**
 * @generated from message veidemann.api.dnsresolver.v1.ResolveReply
 */
export type ResolveReply = Message<"veidemann.api.dnsresolver.v1.ResolveReply"> & {
  /**
   * @generated from field: string host = 1;
   */
  host: string;

  /**
   * Deprecated: a port is application metadata and is not part of DNS resolution.
   *
   * @generated from field: int32 port = 2 [deprecated = true];
   * @deprecated
   */
  port: number;

  /**
   * @generated from field: string textual_ip = 3;
   */
  textualIp: string;

  /**
   * @generated from field: bytes raw_ip = 4;
   */
  rawIp: Uint8Array;

  /**
   * Set when the DNS server returned a valid negative or failure response.
   * Error.code contains the DNS RCODE. Presence with code 0 means NODATA.
   * Transport and resolver-internal failures are returned as gRPC errors.
   *
   * @generated from field: veidemann.api.commons.v1.Error error = 5;
   */
  error?: Error;
};

/**
 * Describes the message veidemann.api.dnsresolver.v1.ResolveReply.
 * Use `create(ResolveReplySchema)` to create a new message.
 */
export const ResolveReplySchema: GenMessage<ResolveReply> = /*@__PURE__*/
  messageDesc(file_dnsresolver_v1_dnsresolver, 1);

/**
 * Service for resolving, caching and logging dns requests.
 *
 * @generated from service veidemann.api.dnsresolver.v1.DnsResolver
 */
export const DnsResolver: GenService<{
  /**
   * @generated from rpc veidemann.api.dnsresolver.v1.DnsResolver.resolve
   */
  resolve: {
    methodKind: "unary";
    input: typeof ResolveRequestSchema;
    output: typeof ResolveReplySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_dnsresolver_v1_dnsresolver, 0);

