/**
 * @fileoverview gRPC-Web generated client stub for veidemann.api.robotsevaluator.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.31.0
// source: robotsevaluator/v1/robotsevaluator.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var config_v1_resources_pb = require('../../config/v1/resources_pb.js')
const proto = {};
proto.veidemann = {};
proto.veidemann.api = {};
proto.veidemann.api.robotsevaluator = {};
proto.veidemann.api.robotsevaluator.v1 = require('./robotsevaluator_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.veidemann.api.robotsevaluator.v1.RobotsEvaluatorClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.veidemann.api.robotsevaluator.v1.RobotsEvaluatorPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.veidemann.api.robotsevaluator.v1.IsAllowedRequest,
 *   !proto.veidemann.api.robotsevaluator.v1.IsAllowedReply>}
 */
const methodDescriptor_RobotsEvaluator_isAllowed = new grpc.web.MethodDescriptor(
  '/veidemann.api.robotsevaluator.v1.RobotsEvaluator/isAllowed',
  grpc.web.MethodType.UNARY,
  proto.veidemann.api.robotsevaluator.v1.IsAllowedRequest,
  proto.veidemann.api.robotsevaluator.v1.IsAllowedReply,
  /**
   * @param {!proto.veidemann.api.robotsevaluator.v1.IsAllowedRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.veidemann.api.robotsevaluator.v1.IsAllowedReply.deserializeBinary
);


/**
 * @param {!proto.veidemann.api.robotsevaluator.v1.IsAllowedRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.veidemann.api.robotsevaluator.v1.IsAllowedReply)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.veidemann.api.robotsevaluator.v1.IsAllowedReply>|undefined}
 *     The XHR Node Readable Stream
 */
proto.veidemann.api.robotsevaluator.v1.RobotsEvaluatorClient.prototype.isAllowed =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/veidemann.api.robotsevaluator.v1.RobotsEvaluator/isAllowed',
      request,
      metadata || {},
      methodDescriptor_RobotsEvaluator_isAllowed,
      callback);
};


/**
 * @param {!proto.veidemann.api.robotsevaluator.v1.IsAllowedRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.veidemann.api.robotsevaluator.v1.IsAllowedReply>}
 *     Promise that resolves to the response
 */
proto.veidemann.api.robotsevaluator.v1.RobotsEvaluatorPromiseClient.prototype.isAllowed =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/veidemann.api.robotsevaluator.v1.RobotsEvaluator/isAllowed',
      request,
      metadata || {},
      methodDescriptor_RobotsEvaluator_isAllowed);
};


module.exports = proto.veidemann.api.robotsevaluator.v1;

