// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: controller/v1/controller.proto

package v1

import (
	v1 "github.com/NationalLibraryOfNorway/veidemann/api/config/v1"
	v11 "github.com/NationalLibraryOfNorway/veidemann/api/frontier/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunStatus int32

const (
	RunStatus_RUNNING         RunStatus = 0
	RunStatus_PAUSED          RunStatus = 1
	RunStatus_PAUSE_REQUESTED RunStatus = 2
)

// Enum value maps for RunStatus.
var (
	RunStatus_name = map[int32]string{
		0: "RUNNING",
		1: "PAUSED",
		2: "PAUSE_REQUESTED",
	}
	RunStatus_value = map[string]int32{
		"RUNNING":         0,
		"PAUSED":          1,
		"PAUSE_REQUESTED": 2,
	}
)

func (x RunStatus) Enum() *RunStatus {
	p := new(RunStatus)
	*p = x
	return p
}

func (x RunStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_controller_v1_controller_proto_enumTypes[0].Descriptor()
}

func (RunStatus) Type() protoreflect.EnumType {
	return &file_controller_v1_controller_proto_enumTypes[0]
}

func (x RunStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunStatus.Descriptor instead.
func (RunStatus) EnumDescriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{0}
}

// Kick of a crawl job immediately
// If a job is already running for this job_id, then new seeds are added to the job instead of starting a new one.
type RunCrawlRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	JobId string                 `protobuf:"bytes,5,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// If seed id is submitted, only this seed will be harvested.
	// If empty, all seeds configured with the submitted job id will be harvested.
	SeedId        string `protobuf:"bytes,6,opt,name=seed_id,json=seedId,proto3" json:"seed_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCrawlRequest) Reset() {
	*x = RunCrawlRequest{}
	mi := &file_controller_v1_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCrawlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCrawlRequest) ProtoMessage() {}

func (x *RunCrawlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCrawlRequest.ProtoReflect.Descriptor instead.
func (*RunCrawlRequest) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{0}
}

func (x *RunCrawlRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RunCrawlRequest) GetSeedId() string {
	if x != nil {
		return x.SeedId
	}
	return ""
}

type RunCrawlReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobExecutionId string                 `protobuf:"bytes,1,opt,name=job_execution_id,json=jobExecutionId,proto3" json:"job_execution_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RunCrawlReply) Reset() {
	*x = RunCrawlReply{}
	mi := &file_controller_v1_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCrawlReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCrawlReply) ProtoMessage() {}

func (x *RunCrawlReply) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCrawlReply.ProtoReflect.Descriptor instead.
func (*RunCrawlReply) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{1}
}

func (x *RunCrawlReply) GetJobExecutionId() string {
	if x != nil {
		return x.JobExecutionId
	}
	return ""
}

type RoleList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          []v1.Role              `protobuf:"varint,1,rep,packed,name=role,proto3,enum=veidemann.api.config.v1.Role" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleList) Reset() {
	*x = RoleList{}
	mi := &file_controller_v1_controller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleList) ProtoMessage() {}

func (x *RoleList) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleList.ProtoReflect.Descriptor instead.
func (*RoleList) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{2}
}

func (x *RoleList) GetRole() []v1.Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type OpenIdConnectIssuerReply struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OpenIdConnectIssuer string                 `protobuf:"bytes,1,opt,name=open_id_connect_issuer,json=openIdConnectIssuer,proto3" json:"open_id_connect_issuer,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *OpenIdConnectIssuerReply) Reset() {
	*x = OpenIdConnectIssuerReply{}
	mi := &file_controller_v1_controller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenIdConnectIssuerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenIdConnectIssuerReply) ProtoMessage() {}

func (x *OpenIdConnectIssuerReply) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenIdConnectIssuerReply.ProtoReflect.Descriptor instead.
func (*OpenIdConnectIssuerReply) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{3}
}

func (x *OpenIdConnectIssuerReply) GetOpenIdConnectIssuer() string {
	if x != nil {
		return x.OpenIdConnectIssuer
	}
	return ""
}

type CrawlerStatus struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RunStatus RunStatus              `protobuf:"varint,1,opt,name=runStatus,proto3,enum=veidemann.api.controller.v1.RunStatus" json:"runStatus,omitempty"`
	// The number of busy CrawlHostGroups which essentially is the number of web pages currently downloading
	BusyCrawlHostGroupCount int64 `protobuf:"varint,2,opt,name=busyCrawlHostGroupCount,proto3" json:"busyCrawlHostGroupCount,omitempty"`
	// Total number of queued URI's
	QueueSize     int64 `protobuf:"varint,3,opt,name=queueSize,proto3" json:"queueSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawlerStatus) Reset() {
	*x = CrawlerStatus{}
	mi := &file_controller_v1_controller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlerStatus) ProtoMessage() {}

func (x *CrawlerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_controller_v1_controller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlerStatus.ProtoReflect.Descriptor instead.
func (*CrawlerStatus) Descriptor() ([]byte, []int) {
	return file_controller_v1_controller_proto_rawDescGZIP(), []int{4}
}

func (x *CrawlerStatus) GetRunStatus() RunStatus {
	if x != nil {
		return x.RunStatus
	}
	return RunStatus_RUNNING
}

func (x *CrawlerStatus) GetBusyCrawlHostGroupCount() int64 {
	if x != nil {
		return x.BusyCrawlHostGroupCount
	}
	return 0
}

func (x *CrawlerStatus) GetQueueSize() int64 {
	if x != nil {
		return x.QueueSize
	}
	return 0
}

var File_controller_v1_controller_proto protoreflect.FileDescriptor

const file_controller_v1_controller_proto_rawDesc = "" +
	"\n" +
	"\x1econtroller/v1/controller.proto\x12\x1bveidemann.api.controller.v1\x1a\x1dcontroller/v1/resources.proto\x1a\x1afrontier/v1/frontier.proto\x1a\x1bfrontier/v1/resources.proto\x1a\x19config/v1/resources.proto\x1a\x1bgoogle/protobuf/empty.proto\"A\n" +
	"\x0fRunCrawlRequest\x12\x15\n" +
	"\x06job_id\x18\x05 \x01(\tR\x05jobId\x12\x17\n" +
	"\aseed_id\x18\x06 \x01(\tR\x06seedId\"9\n" +
	"\rRunCrawlReply\x12(\n" +
	"\x10job_execution_id\x18\x01 \x01(\tR\x0ejobExecutionId\"=\n" +
	"\bRoleList\x121\n" +
	"\x04role\x18\x01 \x03(\x0e2\x1d.veidemann.api.config.v1.RoleR\x04role\"O\n" +
	"\x18OpenIdConnectIssuerReply\x123\n" +
	"\x16open_id_connect_issuer\x18\x01 \x01(\tR\x13openIdConnectIssuer\"\xad\x01\n" +
	"\rCrawlerStatus\x12D\n" +
	"\trunStatus\x18\x01 \x01(\x0e2&.veidemann.api.controller.v1.RunStatusR\trunStatus\x128\n" +
	"\x17busyCrawlHostGroupCount\x18\x02 \x01(\x03R\x17busyCrawlHostGroupCount\x12\x1c\n" +
	"\tqueueSize\x18\x03 \x01(\x03R\tqueueSize*9\n" +
	"\tRunStatus\x12\v\n" +
	"\aRUNNING\x10\x00\x12\n" +
	"\n" +
	"\x06PAUSED\x10\x01\x12\x13\n" +
	"\x0fPAUSE_REQUESTED\x10\x022\xe1\a\n" +
	"\n" +
	"Controller\x12X\n" +
	"\x15GetRolesForActiveUser\x12\x16.google.protobuf.Empty\x1a%.veidemann.api.controller.v1.RoleList\"\x00\x12f\n" +
	"\bRunCrawl\x12,.veidemann.api.controller.v1.RunCrawlRequest\x1a*.veidemann.api.controller.v1.RunCrawlReply\"\x00\x12r\n" +
	"\x13AbortCrawlExecution\x12(.veidemann.api.controller.v1.ExecutionId\x1a/.veidemann.api.frontier.v1.CrawlExecutionStatus\"\x00\x12n\n" +
	"\x11AbortJobExecution\x12(.veidemann.api.controller.v1.ExecutionId\x1a-.veidemann.api.frontier.v1.JobExecutionStatus\"\x00\x12i\n" +
	"\x16GetOpenIdConnectIssuer\x12\x16.google.protobuf.Empty\x1a5.veidemann.api.controller.v1.OpenIdConnectIssuerReply\"\x00\x12@\n" +
	"\fPauseCrawler\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12B\n" +
	"\x0eUnPauseCrawler\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12N\n" +
	"\x06Status\x12\x16.google.protobuf.Empty\x1a*.veidemann.api.controller.v1.CrawlerStatus\"\x00\x12v\n" +
	"\x1bQueueCountForCrawlExecution\x12+.veidemann.api.frontier.v1.CrawlExecutionId\x1a(.veidemann.api.frontier.v1.CountResponse\"\x00\x12t\n" +
	"\x1bQueueCountForCrawlHostGroup\x12).veidemann.api.frontier.v1.CrawlHostGroup\x1a(.veidemann.api.frontier.v1.CountResponse\"\x00B\x81\x02\n" +
	"\x1fcom.veidemann.api.controller.v1B\x0fControllerProtoP\x01Z>github.com/NationalLibraryOfNorway/veidemann/api/controller/v1\xa2\x02\x03VAC\xaa\x02\x1bVeidemann.Api.Controller.V1\xca\x02\x1bVeidemann\\Api\\Controller\\V1\xe2\x02'Veidemann\\Api\\Controller\\V1\\GPBMetadata\xea\x02\x1eVeidemann::Api::Controller::V1b\x06proto3"

var (
	file_controller_v1_controller_proto_rawDescOnce sync.Once
	file_controller_v1_controller_proto_rawDescData []byte
)

func file_controller_v1_controller_proto_rawDescGZIP() []byte {
	file_controller_v1_controller_proto_rawDescOnce.Do(func() {
		file_controller_v1_controller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controller_v1_controller_proto_rawDesc), len(file_controller_v1_controller_proto_rawDesc)))
	})
	return file_controller_v1_controller_proto_rawDescData
}

var file_controller_v1_controller_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_controller_v1_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_controller_v1_controller_proto_goTypes = []any{
	(RunStatus)(0),                   // 0: veidemann.api.controller.v1.RunStatus
	(*RunCrawlRequest)(nil),          // 1: veidemann.api.controller.v1.RunCrawlRequest
	(*RunCrawlReply)(nil),            // 2: veidemann.api.controller.v1.RunCrawlReply
	(*RoleList)(nil),                 // 3: veidemann.api.controller.v1.RoleList
	(*OpenIdConnectIssuerReply)(nil), // 4: veidemann.api.controller.v1.OpenIdConnectIssuerReply
	(*CrawlerStatus)(nil),            // 5: veidemann.api.controller.v1.CrawlerStatus
	(v1.Role)(0),                     // 6: veidemann.api.config.v1.Role
	(*emptypb.Empty)(nil),            // 7: google.protobuf.Empty
	(*ExecutionId)(nil),              // 8: veidemann.api.controller.v1.ExecutionId
	(*v11.CrawlExecutionId)(nil),     // 9: veidemann.api.frontier.v1.CrawlExecutionId
	(*v11.CrawlHostGroup)(nil),       // 10: veidemann.api.frontier.v1.CrawlHostGroup
	(*v11.CrawlExecutionStatus)(nil), // 11: veidemann.api.frontier.v1.CrawlExecutionStatus
	(*v11.JobExecutionStatus)(nil),   // 12: veidemann.api.frontier.v1.JobExecutionStatus
	(*v11.CountResponse)(nil),        // 13: veidemann.api.frontier.v1.CountResponse
}
var file_controller_v1_controller_proto_depIdxs = []int32{
	6,  // 0: veidemann.api.controller.v1.RoleList.role:type_name -> veidemann.api.config.v1.Role
	0,  // 1: veidemann.api.controller.v1.CrawlerStatus.runStatus:type_name -> veidemann.api.controller.v1.RunStatus
	7,  // 2: veidemann.api.controller.v1.Controller.GetRolesForActiveUser:input_type -> google.protobuf.Empty
	1,  // 3: veidemann.api.controller.v1.Controller.RunCrawl:input_type -> veidemann.api.controller.v1.RunCrawlRequest
	8,  // 4: veidemann.api.controller.v1.Controller.AbortCrawlExecution:input_type -> veidemann.api.controller.v1.ExecutionId
	8,  // 5: veidemann.api.controller.v1.Controller.AbortJobExecution:input_type -> veidemann.api.controller.v1.ExecutionId
	7,  // 6: veidemann.api.controller.v1.Controller.GetOpenIdConnectIssuer:input_type -> google.protobuf.Empty
	7,  // 7: veidemann.api.controller.v1.Controller.PauseCrawler:input_type -> google.protobuf.Empty
	7,  // 8: veidemann.api.controller.v1.Controller.UnPauseCrawler:input_type -> google.protobuf.Empty
	7,  // 9: veidemann.api.controller.v1.Controller.Status:input_type -> google.protobuf.Empty
	9,  // 10: veidemann.api.controller.v1.Controller.QueueCountForCrawlExecution:input_type -> veidemann.api.frontier.v1.CrawlExecutionId
	10, // 11: veidemann.api.controller.v1.Controller.QueueCountForCrawlHostGroup:input_type -> veidemann.api.frontier.v1.CrawlHostGroup
	3,  // 12: veidemann.api.controller.v1.Controller.GetRolesForActiveUser:output_type -> veidemann.api.controller.v1.RoleList
	2,  // 13: veidemann.api.controller.v1.Controller.RunCrawl:output_type -> veidemann.api.controller.v1.RunCrawlReply
	11, // 14: veidemann.api.controller.v1.Controller.AbortCrawlExecution:output_type -> veidemann.api.frontier.v1.CrawlExecutionStatus
	12, // 15: veidemann.api.controller.v1.Controller.AbortJobExecution:output_type -> veidemann.api.frontier.v1.JobExecutionStatus
	4,  // 16: veidemann.api.controller.v1.Controller.GetOpenIdConnectIssuer:output_type -> veidemann.api.controller.v1.OpenIdConnectIssuerReply
	7,  // 17: veidemann.api.controller.v1.Controller.PauseCrawler:output_type -> google.protobuf.Empty
	7,  // 18: veidemann.api.controller.v1.Controller.UnPauseCrawler:output_type -> google.protobuf.Empty
	5,  // 19: veidemann.api.controller.v1.Controller.Status:output_type -> veidemann.api.controller.v1.CrawlerStatus
	13, // 20: veidemann.api.controller.v1.Controller.QueueCountForCrawlExecution:output_type -> veidemann.api.frontier.v1.CountResponse
	13, // 21: veidemann.api.controller.v1.Controller.QueueCountForCrawlHostGroup:output_type -> veidemann.api.frontier.v1.CountResponse
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_controller_v1_controller_proto_init() }
func file_controller_v1_controller_proto_init() {
	if File_controller_v1_controller_proto != nil {
		return
	}
	file_controller_v1_resources_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controller_v1_controller_proto_rawDesc), len(file_controller_v1_controller_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controller_v1_controller_proto_goTypes,
		DependencyIndexes: file_controller_v1_controller_proto_depIdxs,
		EnumInfos:         file_controller_v1_controller_proto_enumTypes,
		MessageInfos:      file_controller_v1_controller_proto_msgTypes,
	}.Build()
	File_controller_v1_controller_proto = out.File
	file_controller_v1_controller_proto_goTypes = nil
	file_controller_v1_controller_proto_depIdxs = nil
}
