// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: scopechecker/v1/scopechecker.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScopesCheckerService_ScopeCheck_FullMethodName = "/veidemann.api.scopechecker.v1.ScopesCheckerService/ScopeCheck"
)

// ScopesCheckerServiceClient is the client API for ScopesCheckerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for URI scope check.
type ScopesCheckerServiceClient interface {
	// Check if URI is in scope for this crawl
	ScopeCheck(ctx context.Context, in *ScopeCheckRequest, opts ...grpc.CallOption) (*ScopeCheckResponse, error)
}

type scopesCheckerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScopesCheckerServiceClient(cc grpc.ClientConnInterface) ScopesCheckerServiceClient {
	return &scopesCheckerServiceClient{cc}
}

func (c *scopesCheckerServiceClient) ScopeCheck(ctx context.Context, in *ScopeCheckRequest, opts ...grpc.CallOption) (*ScopeCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScopeCheckResponse)
	err := c.cc.Invoke(ctx, ScopesCheckerService_ScopeCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScopesCheckerServiceServer is the server API for ScopesCheckerService service.
// All implementations should embed UnimplementedScopesCheckerServiceServer
// for forward compatibility.
//
// Service for URI scope check.
type ScopesCheckerServiceServer interface {
	// Check if URI is in scope for this crawl
	ScopeCheck(context.Context, *ScopeCheckRequest) (*ScopeCheckResponse, error)
}

// UnimplementedScopesCheckerServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScopesCheckerServiceServer struct{}

func (UnimplementedScopesCheckerServiceServer) ScopeCheck(context.Context, *ScopeCheckRequest) (*ScopeCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScopeCheck not implemented")
}
func (UnimplementedScopesCheckerServiceServer) testEmbeddedByValue() {}

// UnsafeScopesCheckerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScopesCheckerServiceServer will
// result in compilation errors.
type UnsafeScopesCheckerServiceServer interface {
	mustEmbedUnimplementedScopesCheckerServiceServer()
}

func RegisterScopesCheckerServiceServer(s grpc.ServiceRegistrar, srv ScopesCheckerServiceServer) {
	// If the following call pancis, it indicates UnimplementedScopesCheckerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScopesCheckerService_ServiceDesc, srv)
}

func _ScopesCheckerService_ScopeCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScopeCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScopesCheckerServiceServer).ScopeCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScopesCheckerService_ScopeCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScopesCheckerServiceServer).ScopeCheck(ctx, req.(*ScopeCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScopesCheckerService_ServiceDesc is the grpc.ServiceDesc for ScopesCheckerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScopesCheckerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "veidemann.api.scopechecker.v1.ScopesCheckerService",
	HandlerType: (*ScopesCheckerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScopeCheck",
			Handler:    _ScopesCheckerService_ScopeCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scopechecker/v1/scopechecker.proto",
}
