// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: scopechecker/v1/scopechecker.proto

package v1

import (
	v11 "github.com/NationalLibraryOfNorway/veidemann/api/commons/v1"
	v1 "github.com/NationalLibraryOfNorway/veidemann/api/frontier/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScopeCheckResponse_Evaluation int32

const (
	ScopeCheckResponse_INCLUDE ScopeCheckResponse_Evaluation = 0
	ScopeCheckResponse_EXCLUDE ScopeCheckResponse_Evaluation = 1
)

// Enum value maps for ScopeCheckResponse_Evaluation.
var (
	ScopeCheckResponse_Evaluation_name = map[int32]string{
		0: "INCLUDE",
		1: "EXCLUDE",
	}
	ScopeCheckResponse_Evaluation_value = map[string]int32{
		"INCLUDE": 0,
		"EXCLUDE": 1,
	}
)

func (x ScopeCheckResponse_Evaluation) Enum() *ScopeCheckResponse_Evaluation {
	p := new(ScopeCheckResponse_Evaluation)
	*p = x
	return p
}

func (x ScopeCheckResponse_Evaluation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScopeCheckResponse_Evaluation) Descriptor() protoreflect.EnumDescriptor {
	return file_scopechecker_v1_scopechecker_proto_enumTypes[0].Descriptor()
}

func (ScopeCheckResponse_Evaluation) Type() protoreflect.EnumType {
	return &file_scopechecker_v1_scopechecker_proto_enumTypes[0]
}

func (x ScopeCheckResponse_Evaluation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScopeCheckResponse_Evaluation.Descriptor instead.
func (ScopeCheckResponse_Evaluation) EnumDescriptor() ([]byte, []int) {
	return file_scopechecker_v1_scopechecker_proto_rawDescGZIP(), []int{1, 0}
}

type ScopeCheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The uri to validate.
	// The type QueuedUri includes all the context needed to do scope check
	QueuedUri *v1.QueuedUri `protobuf:"bytes,1,opt,name=queued_uri,json=queuedUri,proto3" json:"queued_uri,omitempty"`
	// Name of script. Used for logging.
	ScopeScriptName string `protobuf:"bytes,2,opt,name=scope_script_name,json=scopeScriptName,proto3" json:"scope_script_name,omitempty"`
	// The Script to evaluate.
	ScopeScript string `protobuf:"bytes,3,opt,name=scope_script,json=scopeScript,proto3" json:"scope_script,omitempty"`
	// Turn on debug messages
	Debug         bool `protobuf:"varint,4,opt,name=debug,proto3" json:"debug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScopeCheckRequest) Reset() {
	*x = ScopeCheckRequest{}
	mi := &file_scopechecker_v1_scopechecker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopeCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopeCheckRequest) ProtoMessage() {}

func (x *ScopeCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scopechecker_v1_scopechecker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopeCheckRequest.ProtoReflect.Descriptor instead.
func (*ScopeCheckRequest) Descriptor() ([]byte, []int) {
	return file_scopechecker_v1_scopechecker_proto_rawDescGZIP(), []int{0}
}

func (x *ScopeCheckRequest) GetQueuedUri() *v1.QueuedUri {
	if x != nil {
		return x.QueuedUri
	}
	return nil
}

func (x *ScopeCheckRequest) GetScopeScriptName() string {
	if x != nil {
		return x.ScopeScriptName
	}
	return ""
}

func (x *ScopeCheckRequest) GetScopeScript() string {
	if x != nil {
		return x.ScopeScript
	}
	return ""
}

func (x *ScopeCheckRequest) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

type ScopeCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The outcome of the scope evaluation
	Evaluation ScopeCheckResponse_Evaluation `protobuf:"varint,1,opt,name=evaluation,proto3,enum=veidemann.api.scopechecker.v1.ScopeCheckResponse_Evaluation" json:"evaluation,omitempty"`
	// Heritrix status code indicating reason for exclude.
	// Most relevant reasons are:
	//   - -5 RUNTIME_EXCEPTION           Unexpected runtime exception.
	//   - -7 ILLEGAL_URI                 URI recognized as unsupported or illegal.
	//   - -4000 CHAFF_DETECTION             Chaff detection of traps/content with negligible value applied.
	//   - -4001 TOO_MANY_HOPS               The URI is too many link hops away from the seed.
	//   - -4002 TOO_MANY_TRANSITIVE_HOPS    The URI is too many embed/transitive hops away from the last URI in scope.
	//   - -5001 BLOCKED                     Blocked from fetch by user setting.
	//   - -5002 BLOCKED_BY_CUSTOM_PROCESSOR Blocked by a custom processor.
	ExcludeReason int32 `protobuf:"varint,2,opt,name=exclude_reason,json=excludeReason,proto3" json:"exclude_reason,omitempty"`
	// URI canonicalized for checking against already included list.
	// Examples of canonicalization could be:
	// * Removing well known session id's (e.g. jsessionid) from query parameters.
	// * Canonicalize according to the rules described for Google Safe Browsing (https://developers.google.com/safe-browsing/v4/urls-hashing)
	IncludeCheckUri *v11.ParsedUri `protobuf:"bytes,3,opt,name=include_check_uri,json=includeCheckUri,proto3" json:"include_check_uri,omitempty"`
	// Error is present if script had errors
	Error *v11.Error `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// If script outputs anything to the console (e.g. if debug is turned on in the request or script contains print() statements),
	// this field will contain the output
	Console       string `protobuf:"bytes,5,opt,name=console,proto3" json:"console,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScopeCheckResponse) Reset() {
	*x = ScopeCheckResponse{}
	mi := &file_scopechecker_v1_scopechecker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopeCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopeCheckResponse) ProtoMessage() {}

func (x *ScopeCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scopechecker_v1_scopechecker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopeCheckResponse.ProtoReflect.Descriptor instead.
func (*ScopeCheckResponse) Descriptor() ([]byte, []int) {
	return file_scopechecker_v1_scopechecker_proto_rawDescGZIP(), []int{1}
}

func (x *ScopeCheckResponse) GetEvaluation() ScopeCheckResponse_Evaluation {
	if x != nil {
		return x.Evaluation
	}
	return ScopeCheckResponse_INCLUDE
}

func (x *ScopeCheckResponse) GetExcludeReason() int32 {
	if x != nil {
		return x.ExcludeReason
	}
	return 0
}

func (x *ScopeCheckResponse) GetIncludeCheckUri() *v11.ParsedUri {
	if x != nil {
		return x.IncludeCheckUri
	}
	return nil
}

func (x *ScopeCheckResponse) GetError() *v11.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ScopeCheckResponse) GetConsole() string {
	if x != nil {
		return x.Console
	}
	return ""
}

var File_scopechecker_v1_scopechecker_proto protoreflect.FileDescriptor

const file_scopechecker_v1_scopechecker_proto_rawDesc = "" +
	"\n" +
	"\"scopechecker/v1/scopechecker.proto\x12\x1dveidemann.api.scopechecker.v1\x1a\x1bfrontier/v1/resources.proto\x1a\x1acommons/v1/resources.proto\"\xbd\x01\n" +
	"\x11ScopeCheckRequest\x12C\n" +
	"\n" +
	"queued_uri\x18\x01 \x01(\v2$.veidemann.api.frontier.v1.QueuedUriR\tqueuedUri\x12*\n" +
	"\x11scope_script_name\x18\x02 \x01(\tR\x0fscopeScriptName\x12!\n" +
	"\fscope_script\x18\x03 \x01(\tR\vscopeScript\x12\x14\n" +
	"\x05debug\x18\x04 \x01(\bR\x05debug\"\xe3\x02\n" +
	"\x12ScopeCheckResponse\x12\\\n" +
	"\n" +
	"evaluation\x18\x01 \x01(\x0e2<.veidemann.api.scopechecker.v1.ScopeCheckResponse.EvaluationR\n" +
	"evaluation\x12%\n" +
	"\x0eexclude_reason\x18\x02 \x01(\x05R\rexcludeReason\x12O\n" +
	"\x11include_check_uri\x18\x03 \x01(\v2#.veidemann.api.commons.v1.ParsedUriR\x0fincludeCheckUri\x125\n" +
	"\x05error\x18\x04 \x01(\v2\x1f.veidemann.api.commons.v1.ErrorR\x05error\x12\x18\n" +
	"\aconsole\x18\x05 \x01(\tR\aconsole\"&\n" +
	"\n" +
	"Evaluation\x12\v\n" +
	"\aINCLUDE\x10\x00\x12\v\n" +
	"\aEXCLUDE\x10\x012\x8b\x01\n" +
	"\x14ScopesCheckerService\x12s\n" +
	"\n" +
	"ScopeCheck\x120.veidemann.api.scopechecker.v1.ScopeCheckRequest\x1a1.veidemann.api.scopechecker.v1.ScopeCheckResponse\"\x00B\x8f\x02\n" +
	"!com.veidemann.api.scopechecker.v1B\x11ScopecheckerProtoP\x01Z@github.com/NationalLibraryOfNorway/veidemann/api/scopechecker/v1\xa2\x02\x03VAS\xaa\x02\x1dVeidemann.Api.Scopechecker.V1\xca\x02\x1dVeidemann\\Api\\Scopechecker\\V1\xe2\x02)Veidemann\\Api\\Scopechecker\\V1\\GPBMetadata\xea\x02 Veidemann::Api::Scopechecker::V1b\x06proto3"

var (
	file_scopechecker_v1_scopechecker_proto_rawDescOnce sync.Once
	file_scopechecker_v1_scopechecker_proto_rawDescData []byte
)

func file_scopechecker_v1_scopechecker_proto_rawDescGZIP() []byte {
	file_scopechecker_v1_scopechecker_proto_rawDescOnce.Do(func() {
		file_scopechecker_v1_scopechecker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scopechecker_v1_scopechecker_proto_rawDesc), len(file_scopechecker_v1_scopechecker_proto_rawDesc)))
	})
	return file_scopechecker_v1_scopechecker_proto_rawDescData
}

var file_scopechecker_v1_scopechecker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_scopechecker_v1_scopechecker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_scopechecker_v1_scopechecker_proto_goTypes = []any{
	(ScopeCheckResponse_Evaluation)(0), // 0: veidemann.api.scopechecker.v1.ScopeCheckResponse.Evaluation
	(*ScopeCheckRequest)(nil),          // 1: veidemann.api.scopechecker.v1.ScopeCheckRequest
	(*ScopeCheckResponse)(nil),         // 2: veidemann.api.scopechecker.v1.ScopeCheckResponse
	(*v1.QueuedUri)(nil),               // 3: veidemann.api.frontier.v1.QueuedUri
	(*v11.ParsedUri)(nil),              // 4: veidemann.api.commons.v1.ParsedUri
	(*v11.Error)(nil),                  // 5: veidemann.api.commons.v1.Error
}
var file_scopechecker_v1_scopechecker_proto_depIdxs = []int32{
	3, // 0: veidemann.api.scopechecker.v1.ScopeCheckRequest.queued_uri:type_name -> veidemann.api.frontier.v1.QueuedUri
	0, // 1: veidemann.api.scopechecker.v1.ScopeCheckResponse.evaluation:type_name -> veidemann.api.scopechecker.v1.ScopeCheckResponse.Evaluation
	4, // 2: veidemann.api.scopechecker.v1.ScopeCheckResponse.include_check_uri:type_name -> veidemann.api.commons.v1.ParsedUri
	5, // 3: veidemann.api.scopechecker.v1.ScopeCheckResponse.error:type_name -> veidemann.api.commons.v1.Error
	1, // 4: veidemann.api.scopechecker.v1.ScopesCheckerService.ScopeCheck:input_type -> veidemann.api.scopechecker.v1.ScopeCheckRequest
	2, // 5: veidemann.api.scopechecker.v1.ScopesCheckerService.ScopeCheck:output_type -> veidemann.api.scopechecker.v1.ScopeCheckResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_scopechecker_v1_scopechecker_proto_init() }
func file_scopechecker_v1_scopechecker_proto_init() {
	if File_scopechecker_v1_scopechecker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scopechecker_v1_scopechecker_proto_rawDesc), len(file_scopechecker_v1_scopechecker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scopechecker_v1_scopechecker_proto_goTypes,
		DependencyIndexes: file_scopechecker_v1_scopechecker_proto_depIdxs,
		EnumInfos:         file_scopechecker_v1_scopechecker_proto_enumTypes,
		MessageInfos:      file_scopechecker_v1_scopechecker_proto_msgTypes,
	}.Build()
	File_scopechecker_v1_scopechecker_proto = out.File
	file_scopechecker_v1_scopechecker_proto_goTypes = nil
	file_scopechecker_v1_scopechecker_proto_depIdxs = nil
}
