apiVersion: v1
kind: Service
metadata:
  name: contentwriter
  labels:
    app.kubernetes.io/name: contentwriter
    app.kubernetes.io/component: contentwriter
    metrics: prometheus
spec:
  type: ClusterIP
  ports:
    - port: 8082
      name: grpc
      targetPort: grpc
    - port: 9153
      name: http-metrics
      targetPort: http-metrics
  selector:
    app.kubernetes.io/name: contentwriter
    app.kubernetes.io/component: contentwriter
