apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kvrocks-backups
  labels:
    app.kubernetes.io/name: kvrocks
    app.kubernetes.io/component: backup
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi