// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: robotsevaluator/v1/robotsevaluator.proto

package v1

import (
	v1 "github.com/NationalLibraryOfNorway/veidemann/api/config/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IsAllowedRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobExecutionId string                 `protobuf:"bytes,1,opt,name=job_execution_id,json=jobExecutionId,proto3" json:"job_execution_id,omitempty"`
	ExecutionId    string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Uri            string                 `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	UserAgent      string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Politeness     *v1.ConfigObject       `protobuf:"bytes,5,opt,name=politeness,proto3" json:"politeness,omitempty"`
	CollectionRef  *v1.ConfigRef          `protobuf:"bytes,6,opt,name=collection_ref,json=collectionRef,proto3" json:"collection_ref,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IsAllowedRequest) Reset() {
	*x = IsAllowedRequest{}
	mi := &file_robotsevaluator_v1_robotsevaluator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAllowedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAllowedRequest) ProtoMessage() {}

func (x *IsAllowedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_robotsevaluator_v1_robotsevaluator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAllowedRequest.ProtoReflect.Descriptor instead.
func (*IsAllowedRequest) Descriptor() ([]byte, []int) {
	return file_robotsevaluator_v1_robotsevaluator_proto_rawDescGZIP(), []int{0}
}

func (x *IsAllowedRequest) GetJobExecutionId() string {
	if x != nil {
		return x.JobExecutionId
	}
	return ""
}

func (x *IsAllowedRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *IsAllowedRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *IsAllowedRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *IsAllowedRequest) GetPoliteness() *v1.ConfigObject {
	if x != nil {
		return x.Politeness
	}
	return nil
}

func (x *IsAllowedRequest) GetCollectionRef() *v1.ConfigRef {
	if x != nil {
		return x.CollectionRef
	}
	return nil
}

type IsAllowedReply struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	IsAllowed     bool                         `protobuf:"varint,1,opt,name=is_allowed,json=isAllowed,proto3" json:"is_allowed,omitempty"`
	CrawlDelay    float32                      `protobuf:"fixed32,2,opt,name=crawl_delay,json=crawlDelay,proto3" json:"crawl_delay,omitempty"`
	CacheDelay    float32                      `protobuf:"fixed32,3,opt,name=cache_delay,json=cacheDelay,proto3" json:"cache_delay,omitempty"`
	Sitemap       []string                     `protobuf:"bytes,4,rep,name=sitemap,proto3" json:"sitemap,omitempty"`
	OtherFields   []*IsAllowedReply_OtherField `protobuf:"bytes,5,rep,name=other_fields,json=otherFields,proto3" json:"other_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAllowedReply) Reset() {
	*x = IsAllowedReply{}
	mi := &file_robotsevaluator_v1_robotsevaluator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAllowedReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAllowedReply) ProtoMessage() {}

func (x *IsAllowedReply) ProtoReflect() protoreflect.Message {
	mi := &file_robotsevaluator_v1_robotsevaluator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAllowedReply.ProtoReflect.Descriptor instead.
func (*IsAllowedReply) Descriptor() ([]byte, []int) {
	return file_robotsevaluator_v1_robotsevaluator_proto_rawDescGZIP(), []int{1}
}

func (x *IsAllowedReply) GetIsAllowed() bool {
	if x != nil {
		return x.IsAllowed
	}
	return false
}

func (x *IsAllowedReply) GetCrawlDelay() float32 {
	if x != nil {
		return x.CrawlDelay
	}
	return 0
}

func (x *IsAllowedReply) GetCacheDelay() float32 {
	if x != nil {
		return x.CacheDelay
	}
	return 0
}

func (x *IsAllowedReply) GetSitemap() []string {
	if x != nil {
		return x.Sitemap
	}
	return nil
}

func (x *IsAllowedReply) GetOtherFields() []*IsAllowedReply_OtherField {
	if x != nil {
		return x.OtherFields
	}
	return nil
}

type IsAllowedReply_OtherField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAllowedReply_OtherField) Reset() {
	*x = IsAllowedReply_OtherField{}
	mi := &file_robotsevaluator_v1_robotsevaluator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAllowedReply_OtherField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAllowedReply_OtherField) ProtoMessage() {}

func (x *IsAllowedReply_OtherField) ProtoReflect() protoreflect.Message {
	mi := &file_robotsevaluator_v1_robotsevaluator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAllowedReply_OtherField.ProtoReflect.Descriptor instead.
func (*IsAllowedReply_OtherField) Descriptor() ([]byte, []int) {
	return file_robotsevaluator_v1_robotsevaluator_proto_rawDescGZIP(), []int{1, 0}
}

func (x *IsAllowedReply_OtherField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IsAllowedReply_OtherField) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_robotsevaluator_v1_robotsevaluator_proto protoreflect.FileDescriptor

const file_robotsevaluator_v1_robotsevaluator_proto_rawDesc = "" +
	"\n" +
	"(robotsevaluator/v1/robotsevaluator.proto\x12 veidemann.api.robotsevaluator.v1\x1a\x19config/v1/resources.proto\"\xa2\x02\n" +
	"\x10IsAllowedRequest\x12(\n" +
	"\x10job_execution_id\x18\x01 \x01(\tR\x0ejobExecutionId\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x12\x10\n" +
	"\x03uri\x18\x03 \x01(\tR\x03uri\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\x12E\n" +
	"\n" +
	"politeness\x18\x05 \x01(\v2%.veidemann.api.config.v1.ConfigObjectR\n" +
	"politeness\x12I\n" +
	"\x0ecollection_ref\x18\x06 \x01(\v2\".veidemann.api.config.v1.ConfigRefR\rcollectionRef\"\xa3\x02\n" +
	"\x0eIsAllowedReply\x12\x1d\n" +
	"\n" +
	"is_allowed\x18\x01 \x01(\bR\tisAllowed\x12\x1f\n" +
	"\vcrawl_delay\x18\x02 \x01(\x02R\n" +
	"crawlDelay\x12\x1f\n" +
	"\vcache_delay\x18\x03 \x01(\x02R\n" +
	"cacheDelay\x12\x18\n" +
	"\asitemap\x18\x04 \x03(\tR\asitemap\x12^\n" +
	"\fother_fields\x18\x05 \x03(\v2;.veidemann.api.robotsevaluator.v1.IsAllowedReply.OtherFieldR\votherFields\x1a6\n" +
	"\n" +
	"OtherField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value2\x86\x01\n" +
	"\x0fRobotsEvaluator\x12s\n" +
	"\tisAllowed\x122.veidemann.api.robotsevaluator.v1.IsAllowedRequest\x1a0.veidemann.api.robotsevaluator.v1.IsAllowedReply\"\x00B\xa4\x02\n" +
	"$com.veidemann.api.robotsevaluator.v1B\x14RobotsevaluatorProtoP\x01ZCgithub.com/NationalLibraryOfNorway/veidemann/api/robotsevaluator/v1\xa2\x02\x03VAR\xaa\x02 Veidemann.Api.Robotsevaluator.V1\xca\x02 Veidemann\\Api\\Robotsevaluator\\V1\xe2\x02,Veidemann\\Api\\Robotsevaluator\\V1\\GPBMetadata\xea\x02#Veidemann::Api::Robotsevaluator::V1b\x06proto3"

var (
	file_robotsevaluator_v1_robotsevaluator_proto_rawDescOnce sync.Once
	file_robotsevaluator_v1_robotsevaluator_proto_rawDescData []byte
)

func file_robotsevaluator_v1_robotsevaluator_proto_rawDescGZIP() []byte {
	file_robotsevaluator_v1_robotsevaluator_proto_rawDescOnce.Do(func() {
		file_robotsevaluator_v1_robotsevaluator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_robotsevaluator_v1_robotsevaluator_proto_rawDesc), len(file_robotsevaluator_v1_robotsevaluator_proto_rawDesc)))
	})
	return file_robotsevaluator_v1_robotsevaluator_proto_rawDescData
}

var file_robotsevaluator_v1_robotsevaluator_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_robotsevaluator_v1_robotsevaluator_proto_goTypes = []any{
	(*IsAllowedRequest)(nil),          // 0: veidemann.api.robotsevaluator.v1.IsAllowedRequest
	(*IsAllowedReply)(nil),            // 1: veidemann.api.robotsevaluator.v1.IsAllowedReply
	(*IsAllowedReply_OtherField)(nil), // 2: veidemann.api.robotsevaluator.v1.IsAllowedReply.OtherField
	(*v1.ConfigObject)(nil),           // 3: veidemann.api.config.v1.ConfigObject
	(*v1.ConfigRef)(nil),              // 4: veidemann.api.config.v1.ConfigRef
}
var file_robotsevaluator_v1_robotsevaluator_proto_depIdxs = []int32{
	3, // 0: veidemann.api.robotsevaluator.v1.IsAllowedRequest.politeness:type_name -> veidemann.api.config.v1.ConfigObject
	4, // 1: veidemann.api.robotsevaluator.v1.IsAllowedRequest.collection_ref:type_name -> veidemann.api.config.v1.ConfigRef
	2, // 2: veidemann.api.robotsevaluator.v1.IsAllowedReply.other_fields:type_name -> veidemann.api.robotsevaluator.v1.IsAllowedReply.OtherField
	0, // 3: veidemann.api.robotsevaluator.v1.RobotsEvaluator.isAllowed:input_type -> veidemann.api.robotsevaluator.v1.IsAllowedRequest
	1, // 4: veidemann.api.robotsevaluator.v1.RobotsEvaluator.isAllowed:output_type -> veidemann.api.robotsevaluator.v1.IsAllowedReply
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_robotsevaluator_v1_robotsevaluator_proto_init() }
func file_robotsevaluator_v1_robotsevaluator_proto_init() {
	if File_robotsevaluator_v1_robotsevaluator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_robotsevaluator_v1_robotsevaluator_proto_rawDesc), len(file_robotsevaluator_v1_robotsevaluator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_robotsevaluator_v1_robotsevaluator_proto_goTypes,
		DependencyIndexes: file_robotsevaluator_v1_robotsevaluator_proto_depIdxs,
		MessageInfos:      file_robotsevaluator_v1_robotsevaluator_proto_msgTypes,
	}.Build()
	File_robotsevaluator_v1_robotsevaluator_proto = out.File
	file_robotsevaluator_v1_robotsevaluator_proto_goTypes = nil
	file_robotsevaluator_v1_robotsevaluator_proto_depIdxs = nil
}
