{
 "title": "Veidemann / Frontier JVM",
 "description": "JVM metrics Dashboard for Veidemann frontier",
 "tags": [
  "JVM",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(up{service=\"veidemann-frontier\"}, pod)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Memory used",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(jvm_memory_bytes_used{pod=~\"$pod\"}, \"pod\", \"$1\", \"pod\", \"veidemann-frontier-(.*)\")",
     "legendFormat": "{{area}} memory [{{pod}}]"
    },
    {
     "expr": "sum(deriv(jvm_memory_bytes_used{area=\"heap\", pod=~\"$pod\"}[5m])) by (service)",
     "legendFormat": "total for {{ service }}"
    },
    {
     "expr": "sum(avg_over_time(jvm_memory_bytes_used{area=\"heap\", pod=~\"$pod\"}[5m])) / count(jvm_memory_bytes_used{area=\"heap\", pod=~\"$pod\"})",
     "legendFormat": "average heap use"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(jvm_threads_current{pod=~\"$pod\"}, \"pod\", \"$1\", \"pod\", \"veidemann-frontier-(.*)\")",
     "legendFormat": "current [{{pod}}]"
    },
    {
     "expr": "label_replace(jvm_threads_daemon{pod=~\"$pod\"}, \"pod\", \"$1\", \"pod\", \"veidemann-frontier-(.*)\")",
     "legendFormat": "daemon [{{pod}}]"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(jvm_classes_loaded{pod=~\"$pod\"}, \"pod\", \"$1\", \"pod\", \"veidemann-frontier-(.*)\")",
     "legendFormat": "loaded [{{pod}}]"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(jvm_gc_collection_seconds_sum{pod=~\"$pod\"}[1m]), \"pod\", \"$1\", \"pod\", \"veidemann-frontier-(.*)\")",
     "legendFormat": "{{gc}} [{{pod}}]"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(jvm_gc_collection_seconds_count{pod=~\"$pod\"}, \"pod\", \"$1\", \"pod\", \"veidemann-frontier-(.*)\")",
     "legendFormat": "{{gc}} [{{pod}}]"
    }
   ]
  }
 ]
}