{
 "title": "Veidemann / Harvesters",
 "tags": [ "veidemann" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(up{service=\"veidemann-harvester\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Sider besøkt per sekund",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(veidemann_harvester_pages_total{pod=~\"$pod\"}[5m]), \"pod\", \"$1\", \"pod\", \"veidemann-harvester-(.*)\")",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Antall sidebesøk som feiler per sekund",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(veidemann_harvester_pages_failed_total{pod=~\"$pod\"}[5m]), \"pod\", \"$1\", \"pod\", \"veidemann-harvester-(.*)\")",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Tid per side",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(veidemann_harvester_pages_fetch_seconds_bucket{pod=~\"$pod\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Feilede sider fordelt på statuskode",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(veidemann_harvester_pages_failed_total[5m])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Gjennomsnitlig tid per side",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(veidemann_harvester_pages_fetch_seconds_sum{pod=~\"$pod\"}[1m])) / sum(rate(veidemann_harvester_pages_fetch_seconds_count{pod=~\"$pod\"}[1m]))"
    }
   ]
  },
  {
   "title": "Tilgjengelige Chrome instanser",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(veidemann_harvester_browser_sessions{pod=~\"$pod\"}, \"pod\", \"$1\", \"pod\", \"veidemann-harvester-(.*)\")",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Aktive Chrome instanser",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(veidemann_harvester_active_browser_sessions{pod=~\"$pod\"}, \"pod\", \"$1\", \"pod\", \"veidemann-harvester-(.*)\")",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Antall harvestere",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{service=\"veidemann-harvester\"})"
    }
   ]
  }
 ]
}