// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: report/v1/report.proto

package v1

import (
	v11 "github.com/NationalLibraryOfNorway/veidemann/api/commons/v1"
	v1 "github.com/NationalLibraryOfNorway/veidemann/api/frontier/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteDbQueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The query to execute
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Maximum number of rows to return. A limit of -1 indicates no limit. If unset or zero, use default limit.
	Limit         int32 `protobuf:"varint,14,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteDbQueryRequest) Reset() {
	*x = ExecuteDbQueryRequest{}
	mi := &file_report_v1_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteDbQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteDbQueryRequest) ProtoMessage() {}

func (x *ExecuteDbQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteDbQueryRequest.ProtoReflect.Descriptor instead.
func (*ExecuteDbQueryRequest) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteDbQueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ExecuteDbQueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ExecuteDbQueryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        string                 `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteDbQueryReply) Reset() {
	*x = ExecuteDbQueryReply{}
	mi := &file_report_v1_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteDbQueryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteDbQueryReply) ProtoMessage() {}

func (x *ExecuteDbQueryReply) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteDbQueryReply.ProtoReflect.Descriptor instead.
func (*ExecuteDbQueryReply) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteDbQueryReply) GetRecord() string {
	if x != nil {
		return x.Record
	}
	return ""
}

type CrawlExecutionsListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Select objects by one or more id's
	Id                 []string                        `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	State              []v1.CrawlExecutionStatus_State `protobuf:"varint,2,rep,packed,name=state,proto3,enum=veidemann.api.frontier.v1.CrawlExecutionStatus_State" json:"state,omitempty"`
	StartTimeFrom      *timestamppb.Timestamp          `protobuf:"bytes,3,opt,name=start_time_from,json=startTimeFrom,proto3" json:"start_time_from,omitempty"`
	StartTimeTo        *timestamppb.Timestamp          `protobuf:"bytes,4,opt,name=start_time_to,json=startTimeTo,proto3" json:"start_time_to,omitempty"`
	HasError           bool                            `protobuf:"varint,5,opt,name=has_error,json=hasError,proto3" json:"has_error,omitempty"`
	QueryTemplate      *v1.CrawlExecutionStatus        `protobuf:"bytes,6,opt,name=query_template,json=queryTemplate,proto3" json:"query_template,omitempty"`
	QueryMask          *v11.FieldMask                  `protobuf:"bytes,7,opt,name=query_mask,json=queryMask,proto3" json:"query_mask,omitempty"`
	ReturnedFieldsMask *v11.FieldMask                  `protobuf:"bytes,8,opt,name=returned_fields_mask,json=returnedFieldsMask,proto3" json:"returned_fields_mask,omitempty"`
	OrderByPath        string                          `protobuf:"bytes,9,opt,name=order_by_path,json=orderByPath,proto3" json:"order_by_path,omitempty"`
	OrderDescending    bool                            `protobuf:"varint,10,opt,name=order_descending,json=orderDescending,proto3" json:"order_descending,omitempty"`
	Watch              bool                            `protobuf:"varint,13,opt,name=watch,proto3" json:"watch,omitempty"`
	PageSize           int32                           `protobuf:"varint,14,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Offset             int32                           `protobuf:"varint,15,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CrawlExecutionsListRequest) Reset() {
	*x = CrawlExecutionsListRequest{}
	mi := &file_report_v1_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlExecutionsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlExecutionsListRequest) ProtoMessage() {}

func (x *CrawlExecutionsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlExecutionsListRequest.ProtoReflect.Descriptor instead.
func (*CrawlExecutionsListRequest) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{2}
}

func (x *CrawlExecutionsListRequest) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *CrawlExecutionsListRequest) GetState() []v1.CrawlExecutionStatus_State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *CrawlExecutionsListRequest) GetStartTimeFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTimeFrom
	}
	return nil
}

func (x *CrawlExecutionsListRequest) GetStartTimeTo() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTimeTo
	}
	return nil
}

func (x *CrawlExecutionsListRequest) GetHasError() bool {
	if x != nil {
		return x.HasError
	}
	return false
}

func (x *CrawlExecutionsListRequest) GetQueryTemplate() *v1.CrawlExecutionStatus {
	if x != nil {
		return x.QueryTemplate
	}
	return nil
}

func (x *CrawlExecutionsListRequest) GetQueryMask() *v11.FieldMask {
	if x != nil {
		return x.QueryMask
	}
	return nil
}

func (x *CrawlExecutionsListRequest) GetReturnedFieldsMask() *v11.FieldMask {
	if x != nil {
		return x.ReturnedFieldsMask
	}
	return nil
}

func (x *CrawlExecutionsListRequest) GetOrderByPath() string {
	if x != nil {
		return x.OrderByPath
	}
	return ""
}

func (x *CrawlExecutionsListRequest) GetOrderDescending() bool {
	if x != nil {
		return x.OrderDescending
	}
	return false
}

func (x *CrawlExecutionsListRequest) GetWatch() bool {
	if x != nil {
		return x.Watch
	}
	return false
}

func (x *CrawlExecutionsListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *CrawlExecutionsListRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type JobExecutionsListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Select objects by one or more id's
	Id                 []string                      `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	State              []v1.JobExecutionStatus_State `protobuf:"varint,2,rep,packed,name=state,proto3,enum=veidemann.api.frontier.v1.JobExecutionStatus_State" json:"state,omitempty"`
	StartTimeFrom      *timestamppb.Timestamp        `protobuf:"bytes,3,opt,name=start_time_from,json=startTimeFrom,proto3" json:"start_time_from,omitempty"`
	StartTimeTo        *timestamppb.Timestamp        `protobuf:"bytes,4,opt,name=start_time_to,json=startTimeTo,proto3" json:"start_time_to,omitempty"`
	QueryTemplate      *v1.JobExecutionStatus        `protobuf:"bytes,6,opt,name=query_template,json=queryTemplate,proto3" json:"query_template,omitempty"`
	QueryMask          *v11.FieldMask                `protobuf:"bytes,7,opt,name=query_mask,json=queryMask,proto3" json:"query_mask,omitempty"`
	ReturnedFieldsMask *v11.FieldMask                `protobuf:"bytes,8,opt,name=returned_fields_mask,json=returnedFieldsMask,proto3" json:"returned_fields_mask,omitempty"`
	OrderByPath        string                        `protobuf:"bytes,9,opt,name=order_by_path,json=orderByPath,proto3" json:"order_by_path,omitempty"`
	OrderDescending    bool                          `protobuf:"varint,10,opt,name=order_descending,json=orderDescending,proto3" json:"order_descending,omitempty"`
	Watch              bool                          `protobuf:"varint,13,opt,name=watch,proto3" json:"watch,omitempty"`
	PageSize           int32                         `protobuf:"varint,14,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Offset             int32                         `protobuf:"varint,15,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *JobExecutionsListRequest) Reset() {
	*x = JobExecutionsListRequest{}
	mi := &file_report_v1_report_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobExecutionsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobExecutionsListRequest) ProtoMessage() {}

func (x *JobExecutionsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobExecutionsListRequest.ProtoReflect.Descriptor instead.
func (*JobExecutionsListRequest) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{3}
}

func (x *JobExecutionsListRequest) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *JobExecutionsListRequest) GetState() []v1.JobExecutionStatus_State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *JobExecutionsListRequest) GetStartTimeFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTimeFrom
	}
	return nil
}

func (x *JobExecutionsListRequest) GetStartTimeTo() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTimeTo
	}
	return nil
}

func (x *JobExecutionsListRequest) GetQueryTemplate() *v1.JobExecutionStatus {
	if x != nil {
		return x.QueryTemplate
	}
	return nil
}

func (x *JobExecutionsListRequest) GetQueryMask() *v11.FieldMask {
	if x != nil {
		return x.QueryMask
	}
	return nil
}

func (x *JobExecutionsListRequest) GetReturnedFieldsMask() *v11.FieldMask {
	if x != nil {
		return x.ReturnedFieldsMask
	}
	return nil
}

func (x *JobExecutionsListRequest) GetOrderByPath() string {
	if x != nil {
		return x.OrderByPath
	}
	return ""
}

func (x *JobExecutionsListRequest) GetOrderDescending() bool {
	if x != nil {
		return x.OrderDescending
	}
	return false
}

func (x *JobExecutionsListRequest) GetWatch() bool {
	if x != nil {
		return x.Watch
	}
	return false
}

func (x *JobExecutionsListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *JobExecutionsListRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_report_v1_report_proto protoreflect.FileDescriptor

const file_report_v1_report_proto_rawDesc = "" +
	"\n" +
	"\x16report/v1/report.proto\x12\x17veidemann.api.report.v1\x1a\x1acommons/v1/resources.proto\x1a\x1bfrontier/v1/resources.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"C\n" +
	"\x15ExecuteDbQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x0e \x01(\x05R\x05limit\"-\n" +
	"\x13ExecuteDbQueryReply\x12\x16\n" +
	"\x06record\x18\x01 \x01(\tR\x06record\"\xa7\x05\n" +
	"\x1aCrawlExecutionsListRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x03(\tR\x02id\x12K\n" +
	"\x05state\x18\x02 \x03(\x0e25.veidemann.api.frontier.v1.CrawlExecutionStatus.StateR\x05state\x12B\n" +
	"\x0fstart_time_from\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rstartTimeFrom\x12>\n" +
	"\rstart_time_to\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vstartTimeTo\x12\x1b\n" +
	"\thas_error\x18\x05 \x01(\bR\bhasError\x12V\n" +
	"\x0equery_template\x18\x06 \x01(\v2/.veidemann.api.frontier.v1.CrawlExecutionStatusR\rqueryTemplate\x12B\n" +
	"\n" +
	"query_mask\x18\a \x01(\v2#.veidemann.api.commons.v1.FieldMaskR\tqueryMask\x12U\n" +
	"\x14returned_fields_mask\x18\b \x01(\v2#.veidemann.api.commons.v1.FieldMaskR\x12returnedFieldsMask\x12\"\n" +
	"\rorder_by_path\x18\t \x01(\tR\vorderByPath\x12)\n" +
	"\x10order_descending\x18\n" +
	" \x01(\bR\x0forderDescending\x12\x14\n" +
	"\x05watch\x18\r \x01(\bR\x05watch\x12\x1b\n" +
	"\tpage_size\x18\x0e \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06offset\x18\x0f \x01(\x05R\x06offset\"\x84\x05\n" +
	"\x18JobExecutionsListRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x03(\tR\x02id\x12I\n" +
	"\x05state\x18\x02 \x03(\x0e23.veidemann.api.frontier.v1.JobExecutionStatus.StateR\x05state\x12B\n" +
	"\x0fstart_time_from\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rstartTimeFrom\x12>\n" +
	"\rstart_time_to\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vstartTimeTo\x12T\n" +
	"\x0equery_template\x18\x06 \x01(\v2-.veidemann.api.frontier.v1.JobExecutionStatusR\rqueryTemplate\x12B\n" +
	"\n" +
	"query_mask\x18\a \x01(\v2#.veidemann.api.commons.v1.FieldMaskR\tqueryMask\x12U\n" +
	"\x14returned_fields_mask\x18\b \x01(\v2#.veidemann.api.commons.v1.FieldMaskR\x12returnedFieldsMask\x12\"\n" +
	"\rorder_by_path\x18\t \x01(\tR\vorderByPath\x12)\n" +
	"\x10order_descending\x18\n" +
	" \x01(\bR\x0forderDescending\x12\x14\n" +
	"\x05watch\x18\r \x01(\bR\x05watch\x12\x1b\n" +
	"\tpage_size\x18\x0e \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06offset\x18\x0f \x01(\x05R\x06offset2\xf3\x02\n" +
	"\x06Report\x12r\n" +
	"\x0eExecuteDbQuery\x12..veidemann.api.report.v1.ExecuteDbQueryRequest\x1a,.veidemann.api.report.v1.ExecuteDbQueryReply\"\x000\x01\x12z\n" +
	"\x0eListExecutions\x123.veidemann.api.report.v1.CrawlExecutionsListRequest\x1a/.veidemann.api.frontier.v1.CrawlExecutionStatus\"\x000\x01\x12y\n" +
	"\x11ListJobExecutions\x121.veidemann.api.report.v1.JobExecutionsListRequest\x1a-.veidemann.api.frontier.v1.JobExecutionStatus\"\x000\x01B\xe5\x01\n" +
	"\x1bcom.veidemann.api.report.v1B\vReportProtoP\x01Z:github.com/NationalLibraryOfNorway/veidemann/api/report/v1\xa2\x02\x03VAR\xaa\x02\x17Veidemann.Api.Report.V1\xca\x02\x17Veidemann\\Api\\Report\\V1\xe2\x02#Veidemann\\Api\\Report\\V1\\GPBMetadata\xea\x02\x1aVeidemann::Api::Report::V1b\x06proto3"

var (
	file_report_v1_report_proto_rawDescOnce sync.Once
	file_report_v1_report_proto_rawDescData []byte
)

func file_report_v1_report_proto_rawDescGZIP() []byte {
	file_report_v1_report_proto_rawDescOnce.Do(func() {
		file_report_v1_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_report_v1_report_proto_rawDesc), len(file_report_v1_report_proto_rawDesc)))
	})
	return file_report_v1_report_proto_rawDescData
}

var file_report_v1_report_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_report_v1_report_proto_goTypes = []any{
	(*ExecuteDbQueryRequest)(nil),      // 0: veidemann.api.report.v1.ExecuteDbQueryRequest
	(*ExecuteDbQueryReply)(nil),        // 1: veidemann.api.report.v1.ExecuteDbQueryReply
	(*CrawlExecutionsListRequest)(nil), // 2: veidemann.api.report.v1.CrawlExecutionsListRequest
	(*JobExecutionsListRequest)(nil),   // 3: veidemann.api.report.v1.JobExecutionsListRequest
	(v1.CrawlExecutionStatus_State)(0), // 4: veidemann.api.frontier.v1.CrawlExecutionStatus.State
	(*timestamppb.Timestamp)(nil),      // 5: google.protobuf.Timestamp
	(*v1.CrawlExecutionStatus)(nil),    // 6: veidemann.api.frontier.v1.CrawlExecutionStatus
	(*v11.FieldMask)(nil),              // 7: veidemann.api.commons.v1.FieldMask
	(v1.JobExecutionStatus_State)(0),   // 8: veidemann.api.frontier.v1.JobExecutionStatus.State
	(*v1.JobExecutionStatus)(nil),      // 9: veidemann.api.frontier.v1.JobExecutionStatus
}
var file_report_v1_report_proto_depIdxs = []int32{
	4,  // 0: veidemann.api.report.v1.CrawlExecutionsListRequest.state:type_name -> veidemann.api.frontier.v1.CrawlExecutionStatus.State
	5,  // 1: veidemann.api.report.v1.CrawlExecutionsListRequest.start_time_from:type_name -> google.protobuf.Timestamp
	5,  // 2: veidemann.api.report.v1.CrawlExecutionsListRequest.start_time_to:type_name -> google.protobuf.Timestamp
	6,  // 3: veidemann.api.report.v1.CrawlExecutionsListRequest.query_template:type_name -> veidemann.api.frontier.v1.CrawlExecutionStatus
	7,  // 4: veidemann.api.report.v1.CrawlExecutionsListRequest.query_mask:type_name -> veidemann.api.commons.v1.FieldMask
	7,  // 5: veidemann.api.report.v1.CrawlExecutionsListRequest.returned_fields_mask:type_name -> veidemann.api.commons.v1.FieldMask
	8,  // 6: veidemann.api.report.v1.JobExecutionsListRequest.state:type_name -> veidemann.api.frontier.v1.JobExecutionStatus.State
	5,  // 7: veidemann.api.report.v1.JobExecutionsListRequest.start_time_from:type_name -> google.protobuf.Timestamp
	5,  // 8: veidemann.api.report.v1.JobExecutionsListRequest.start_time_to:type_name -> google.protobuf.Timestamp
	9,  // 9: veidemann.api.report.v1.JobExecutionsListRequest.query_template:type_name -> veidemann.api.frontier.v1.JobExecutionStatus
	7,  // 10: veidemann.api.report.v1.JobExecutionsListRequest.query_mask:type_name -> veidemann.api.commons.v1.FieldMask
	7,  // 11: veidemann.api.report.v1.JobExecutionsListRequest.returned_fields_mask:type_name -> veidemann.api.commons.v1.FieldMask
	0,  // 12: veidemann.api.report.v1.Report.ExecuteDbQuery:input_type -> veidemann.api.report.v1.ExecuteDbQueryRequest
	2,  // 13: veidemann.api.report.v1.Report.ListExecutions:input_type -> veidemann.api.report.v1.CrawlExecutionsListRequest
	3,  // 14: veidemann.api.report.v1.Report.ListJobExecutions:input_type -> veidemann.api.report.v1.JobExecutionsListRequest
	1,  // 15: veidemann.api.report.v1.Report.ExecuteDbQuery:output_type -> veidemann.api.report.v1.ExecuteDbQueryReply
	6,  // 16: veidemann.api.report.v1.Report.ListExecutions:output_type -> veidemann.api.frontier.v1.CrawlExecutionStatus
	9,  // 17: veidemann.api.report.v1.Report.ListJobExecutions:output_type -> veidemann.api.frontier.v1.JobExecutionStatus
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_report_v1_report_proto_init() }
func file_report_v1_report_proto_init() {
	if File_report_v1_report_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_report_v1_report_proto_rawDesc), len(file_report_v1_report_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_report_v1_report_proto_goTypes,
		DependencyIndexes: file_report_v1_report_proto_depIdxs,
		MessageInfos:      file_report_v1_report_proto_msgTypes,
	}.Build()
	File_report_v1_report_proto = out.File
	file_report_v1_report_proto_goTypes = nil
	file_report_v1_report_proto_depIdxs = nil
}
