// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: report/v1/resources.proto

package v1

import (
	v1 "github.com/NationalLibraryOfNorway/veidemann/api/frontier/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusDetail struct {
	state               protoimpl.MessageState        `protogen:"open.v1"`
	Id                  string                        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State               v1.CrawlExecutionStatus_State `protobuf:"varint,2,opt,name=state,proto3,enum=veidemann.api.frontier.v1.CrawlExecutionStatus_State" json:"state,omitempty"`
	JobId               string                        `protobuf:"bytes,3,opt,name=jobId,proto3" json:"jobId,omitempty"`
	Seed                string                        `protobuf:"bytes,4,opt,name=seed,proto3" json:"seed,omitempty"`
	StartTime           *timestamppb.Timestamp        `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime             *timestamppb.Timestamp        `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	DocumentsCrawled    int64                         `protobuf:"varint,7,opt,name=documents_crawled,json=documentsCrawled,proto3" json:"documents_crawled,omitempty"`
	BytesCrawled        int64                         `protobuf:"varint,8,opt,name=bytes_crawled,json=bytesCrawled,proto3" json:"bytes_crawled,omitempty"`
	UrisCrawled         int64                         `protobuf:"varint,9,opt,name=uris_crawled,json=urisCrawled,proto3" json:"uris_crawled,omitempty"`
	DocumentsFailed     int64                         `protobuf:"varint,10,opt,name=documents_failed,json=documentsFailed,proto3" json:"documents_failed,omitempty"`
	DocumentsOutOfScope int64                         `protobuf:"varint,11,opt,name=documents_out_of_scope,json=documentsOutOfScope,proto3" json:"documents_out_of_scope,omitempty"`
	DocumentsRetried    int64                         `protobuf:"varint,12,opt,name=documents_retried,json=documentsRetried,proto3" json:"documents_retried,omitempty"`
	DocumentsDenied     int64                         `protobuf:"varint,13,opt,name=documents_denied,json=documentsDenied,proto3" json:"documents_denied,omitempty"`
	QueueSize           int64                         `protobuf:"varint,14,opt,name=queue_size,json=queueSize,proto3" json:"queue_size,omitempty"`
	CurrentUri          string                        `protobuf:"bytes,20,opt,name=current_uri,json=currentUri,proto3" json:"current_uri,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StatusDetail) Reset() {
	*x = StatusDetail{}
	mi := &file_report_v1_resources_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusDetail) ProtoMessage() {}

func (x *StatusDetail) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_resources_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusDetail.ProtoReflect.Descriptor instead.
func (*StatusDetail) Descriptor() ([]byte, []int) {
	return file_report_v1_resources_proto_rawDescGZIP(), []int{0}
}

func (x *StatusDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StatusDetail) GetState() v1.CrawlExecutionStatus_State {
	if x != nil {
		return x.State
	}
	return v1.CrawlExecutionStatus_State(0)
}

func (x *StatusDetail) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *StatusDetail) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

func (x *StatusDetail) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *StatusDetail) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *StatusDetail) GetDocumentsCrawled() int64 {
	if x != nil {
		return x.DocumentsCrawled
	}
	return 0
}

func (x *StatusDetail) GetBytesCrawled() int64 {
	if x != nil {
		return x.BytesCrawled
	}
	return 0
}

func (x *StatusDetail) GetUrisCrawled() int64 {
	if x != nil {
		return x.UrisCrawled
	}
	return 0
}

func (x *StatusDetail) GetDocumentsFailed() int64 {
	if x != nil {
		return x.DocumentsFailed
	}
	return 0
}

func (x *StatusDetail) GetDocumentsOutOfScope() int64 {
	if x != nil {
		return x.DocumentsOutOfScope
	}
	return 0
}

func (x *StatusDetail) GetDocumentsRetried() int64 {
	if x != nil {
		return x.DocumentsRetried
	}
	return 0
}

func (x *StatusDetail) GetDocumentsDenied() int64 {
	if x != nil {
		return x.DocumentsDenied
	}
	return 0
}

func (x *StatusDetail) GetQueueSize() int64 {
	if x != nil {
		return x.QueueSize
	}
	return 0
}

func (x *StatusDetail) GetCurrentUri() string {
	if x != nil {
		return x.CurrentUri
	}
	return ""
}

var File_report_v1_resources_proto protoreflect.FileDescriptor

const file_report_v1_resources_proto_rawDesc = "" +
	"\n" +
	"\x19report/v1/resources.proto\x12\x17veidemann.api.report.v1\x1a\x1bfrontier/v1/resources.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf4\x04\n" +
	"\fStatusDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12K\n" +
	"\x05state\x18\x02 \x01(\x0e25.veidemann.api.frontier.v1.CrawlExecutionStatus.StateR\x05state\x12\x14\n" +
	"\x05jobId\x18\x03 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04seed\x18\x04 \x01(\tR\x04seed\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12+\n" +
	"\x11documents_crawled\x18\a \x01(\x03R\x10documentsCrawled\x12#\n" +
	"\rbytes_crawled\x18\b \x01(\x03R\fbytesCrawled\x12!\n" +
	"\furis_crawled\x18\t \x01(\x03R\vurisCrawled\x12)\n" +
	"\x10documents_failed\x18\n" +
	" \x01(\x03R\x0fdocumentsFailed\x123\n" +
	"\x16documents_out_of_scope\x18\v \x01(\x03R\x13documentsOutOfScope\x12+\n" +
	"\x11documents_retried\x18\f \x01(\x03R\x10documentsRetried\x12)\n" +
	"\x10documents_denied\x18\r \x01(\x03R\x0fdocumentsDenied\x12\x1d\n" +
	"\n" +
	"queue_size\x18\x0e \x01(\x03R\tqueueSize\x12\x1f\n" +
	"\vcurrent_uri\x18\x14 \x01(\tR\n" +
	"currentUriB\xe8\x01\n" +
	"\x1bcom.veidemann.api.report.v1B\x0eResourcesProtoP\x01Z:github.com/NationalLibraryOfNorway/veidemann/api/report/v1\xa2\x02\x03VAR\xaa\x02\x17Veidemann.Api.Report.V1\xca\x02\x17Veidemann\\Api\\Report\\V1\xe2\x02#Veidemann\\Api\\Report\\V1\\GPBMetadata\xea\x02\x1aVeidemann::Api::Report::V1b\x06proto3"

var (
	file_report_v1_resources_proto_rawDescOnce sync.Once
	file_report_v1_resources_proto_rawDescData []byte
)

func file_report_v1_resources_proto_rawDescGZIP() []byte {
	file_report_v1_resources_proto_rawDescOnce.Do(func() {
		file_report_v1_resources_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_report_v1_resources_proto_rawDesc), len(file_report_v1_resources_proto_rawDesc)))
	})
	return file_report_v1_resources_proto_rawDescData
}

var file_report_v1_resources_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_report_v1_resources_proto_goTypes = []any{
	(*StatusDetail)(nil),               // 0: veidemann.api.report.v1.StatusDetail
	(v1.CrawlExecutionStatus_State)(0), // 1: veidemann.api.frontier.v1.CrawlExecutionStatus.State
	(*timestamppb.Timestamp)(nil),      // 2: google.protobuf.Timestamp
}
var file_report_v1_resources_proto_depIdxs = []int32{
	1, // 0: veidemann.api.report.v1.StatusDetail.state:type_name -> veidemann.api.frontier.v1.CrawlExecutionStatus.State
	2, // 1: veidemann.api.report.v1.StatusDetail.start_time:type_name -> google.protobuf.Timestamp
	2, // 2: veidemann.api.report.v1.StatusDetail.end_time:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_report_v1_resources_proto_init() }
func file_report_v1_resources_proto_init() {
	if File_report_v1_resources_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_report_v1_resources_proto_rawDesc), len(file_report_v1_resources_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_report_v1_resources_proto_goTypes,
		DependencyIndexes: file_report_v1_resources_proto_depIdxs,
		MessageInfos:      file_report_v1_resources_proto_msgTypes,
	}.Build()
	File_report_v1_resources_proto = out.File
	file_report_v1_resources_proto_goTypes = nil
	file_report_v1_resources_proto_depIdxs = nil
}
