// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: contentwriter/v1/resources.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordType int32

const (
	RecordType_WARCINFO     RecordType = 0
	RecordType_RESPONSE     RecordType = 1
	RecordType_RESOURCE     RecordType = 2
	RecordType_REQUEST      RecordType = 3
	RecordType_METADATA     RecordType = 4
	RecordType_REVISIT      RecordType = 5
	RecordType_CONVERSION   RecordType = 6
	RecordType_CONTINUATION RecordType = 7
)

// Enum value maps for RecordType.
var (
	RecordType_name = map[int32]string{
		0: "WARCINFO",
		1: "RESPONSE",
		2: "RESOURCE",
		3: "REQUEST",
		4: "METADATA",
		5: "REVISIT",
		6: "CONVERSION",
		7: "CONTINUATION",
	}
	RecordType_value = map[string]int32{
		"WARCINFO":     0,
		"RESPONSE":     1,
		"RESOURCE":     2,
		"REQUEST":      3,
		"METADATA":     4,
		"REVISIT":      5,
		"CONVERSION":   6,
		"CONTINUATION": 7,
	}
)

func (x RecordType) Enum() *RecordType {
	p := new(RecordType)
	*p = x
	return p
}

func (x RecordType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecordType) Descriptor() protoreflect.EnumDescriptor {
	return file_contentwriter_v1_resources_proto_enumTypes[0].Descriptor()
}

func (RecordType) Type() protoreflect.EnumType {
	return &file_contentwriter_v1_resources_proto_enumTypes[0]
}

func (x RecordType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecordType.Descriptor instead.
func (RecordType) EnumDescriptor() ([]byte, []int) {
	return file_contentwriter_v1_resources_proto_rawDescGZIP(), []int{0}
}

type CrawledContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        string                 `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	WarcId        string                 `protobuf:"bytes,2,opt,name=warc_id,json=warcId,proto3" json:"warc_id,omitempty"`
	TargetUri     string                 `protobuf:"bytes,3,opt,name=target_uri,json=targetUri,proto3" json:"target_uri,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawledContent) Reset() {
	*x = CrawledContent{}
	mi := &file_contentwriter_v1_resources_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawledContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawledContent) ProtoMessage() {}

func (x *CrawledContent) ProtoReflect() protoreflect.Message {
	mi := &file_contentwriter_v1_resources_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawledContent.ProtoReflect.Descriptor instead.
func (*CrawledContent) Descriptor() ([]byte, []int) {
	return file_contentwriter_v1_resources_proto_rawDescGZIP(), []int{0}
}

func (x *CrawledContent) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *CrawledContent) GetWarcId() string {
	if x != nil {
		return x.WarcId
	}
	return ""
}

func (x *CrawledContent) GetTargetUri() string {
	if x != nil {
		return x.TargetUri
	}
	return ""
}

func (x *CrawledContent) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type StorageRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WarcId        string                 `protobuf:"bytes,1,opt,name=warc_id,json=warcId,proto3" json:"warc_id,omitempty"`
	RecordType    RecordType             `protobuf:"varint,2,opt,name=record_type,json=recordType,proto3,enum=veidemann.api.contentwriter.v1.RecordType" json:"record_type,omitempty"`
	StorageRef    string                 `protobuf:"bytes,3,opt,name=storage_ref,json=storageRef,proto3" json:"storage_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageRef) Reset() {
	*x = StorageRef{}
	mi := &file_contentwriter_v1_resources_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageRef) ProtoMessage() {}

func (x *StorageRef) ProtoReflect() protoreflect.Message {
	mi := &file_contentwriter_v1_resources_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageRef.ProtoReflect.Descriptor instead.
func (*StorageRef) Descriptor() ([]byte, []int) {
	return file_contentwriter_v1_resources_proto_rawDescGZIP(), []int{1}
}

func (x *StorageRef) GetWarcId() string {
	if x != nil {
		return x.WarcId
	}
	return ""
}

func (x *StorageRef) GetRecordType() RecordType {
	if x != nil {
		return x.RecordType
	}
	return RecordType_WARCINFO
}

func (x *StorageRef) GetStorageRef() string {
	if x != nil {
		return x.StorageRef
	}
	return ""
}

var File_contentwriter_v1_resources_proto protoreflect.FileDescriptor

const file_contentwriter_v1_resources_proto_rawDesc = "" +
	"\n" +
	" contentwriter/v1/resources.proto\x12\x1eveidemann.api.contentwriter.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x01\n" +
	"\x0eCrawledContent\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\tR\x06digest\x12\x17\n" +
	"\awarc_id\x18\x02 \x01(\tR\x06warcId\x12\x1d\n" +
	"\n" +
	"target_uri\x18\x03 \x01(\tR\ttargetUri\x12.\n" +
	"\x04date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\"\x93\x01\n" +
	"\n" +
	"StorageRef\x12\x17\n" +
	"\awarc_id\x18\x01 \x01(\tR\x06warcId\x12K\n" +
	"\vrecord_type\x18\x02 \x01(\x0e2*.veidemann.api.contentwriter.v1.RecordTypeR\n" +
	"recordType\x12\x1f\n" +
	"\vstorage_ref\x18\x03 \x01(\tR\n" +
	"storageRef*\x80\x01\n" +
	"\n" +
	"RecordType\x12\f\n" +
	"\bWARCINFO\x10\x00\x12\f\n" +
	"\bRESPONSE\x10\x01\x12\f\n" +
	"\bRESOURCE\x10\x02\x12\v\n" +
	"\aREQUEST\x10\x03\x12\f\n" +
	"\bMETADATA\x10\x04\x12\v\n" +
	"\aREVISIT\x10\x05\x12\x0e\n" +
	"\n" +
	"CONVERSION\x10\x06\x12\x10\n" +
	"\fCONTINUATION\x10\aB\x92\x02\n" +
	"\"com.veidemann.api.contentwriter.v1B\x0eResourcesProtoP\x01ZAgithub.com/NationalLibraryOfNorway/veidemann/api/contentwriter/v1\xa2\x02\x03VAC\xaa\x02\x1eVeidemann.Api.Contentwriter.V1\xca\x02\x1eVeidemann\\Api\\Contentwriter\\V1\xe2\x02*Veidemann\\Api\\Contentwriter\\V1\\GPBMetadata\xea\x02!Veidemann::Api::Contentwriter::V1b\x06proto3"

var (
	file_contentwriter_v1_resources_proto_rawDescOnce sync.Once
	file_contentwriter_v1_resources_proto_rawDescData []byte
)

func file_contentwriter_v1_resources_proto_rawDescGZIP() []byte {
	file_contentwriter_v1_resources_proto_rawDescOnce.Do(func() {
		file_contentwriter_v1_resources_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contentwriter_v1_resources_proto_rawDesc), len(file_contentwriter_v1_resources_proto_rawDesc)))
	})
	return file_contentwriter_v1_resources_proto_rawDescData
}

var file_contentwriter_v1_resources_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_contentwriter_v1_resources_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contentwriter_v1_resources_proto_goTypes = []any{
	(RecordType)(0),               // 0: veidemann.api.contentwriter.v1.RecordType
	(*CrawledContent)(nil),        // 1: veidemann.api.contentwriter.v1.CrawledContent
	(*StorageRef)(nil),            // 2: veidemann.api.contentwriter.v1.StorageRef
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_contentwriter_v1_resources_proto_depIdxs = []int32{
	3, // 0: veidemann.api.contentwriter.v1.CrawledContent.date:type_name -> google.protobuf.Timestamp
	0, // 1: veidemann.api.contentwriter.v1.StorageRef.record_type:type_name -> veidemann.api.contentwriter.v1.RecordType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_contentwriter_v1_resources_proto_init() }
func file_contentwriter_v1_resources_proto_init() {
	if File_contentwriter_v1_resources_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contentwriter_v1_resources_proto_rawDesc), len(file_contentwriter_v1_resources_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contentwriter_v1_resources_proto_goTypes,
		DependencyIndexes: file_contentwriter_v1_resources_proto_depIdxs,
		EnumInfos:         file_contentwriter_v1_resources_proto_enumTypes,
		MessageInfos:      file_contentwriter_v1_resources_proto_msgTypes,
	}.Build()
	File_contentwriter_v1_resources_proto = out.File
	file_contentwriter_v1_resources_proto_goTypes = nil
	file_contentwriter_v1_resources_proto_depIdxs = nil
}
